### ISSUE TITLE
CloudKit Integration

### ISSUE THREAD

**Issue by shsteven** [yapstudios/YapDatabase#101]
YapDB API looks very similar to CloudKit APIs.
@robbiehanson Any plan to integrate CloudKit into YapDB for easy sync solution?

**Comment by Onetaway** [comment]
I run on iOS 7 device ,it crashed and said 
```
dyld: Library not loaded: /System/Library/Frameworks/CloudKit.framework/CloudKit
  Referenced from: /private/var/mobile/Applications/B487DA6C-765B-4D24-9342-CBE074E39925/BaoZouCamera.app/Frameworks/YapDatabase.framework/YapDatabase
  Reason: image not found
```
How can I solve this problem.

**Comment by chrisballinger** [comment]
You can't use dynamic frameworks on iOS 7.
