### ISSUE TITLE
Passing in custom connection to registerExtension with a higher objectCacheLimit

### ISSUE THREAD

**Issue by chrisballinger** [yapstudios/YapDatabase#108]
When registering extensions that have thousands of pre-existing items it can be helpful to increase the objectCacheLimit. It seems that registerExtension in 2.5 already uses an internal registrationConnection that can use customized objectCacheLimit database defaults. 

However, in some cases you might wish to use a different objectCacheLimit limit for each registerExtension call.

In our case it seems that simply using a very high database-level objectCacheLimit helps a lot.

**Comment by robbiehanson** [comment]
Fixed in the 2.6 branch
