### ISSUE TITLE
Create a framework we can add to our apps

### ISSUE THREAD

**Issue by mike-lischke** [yapstudios/YapDatabase#131]
Please add a project to create a framework which we can include in our apps, instead of adding the source code. Also, remove the code from CocoaLumberjack and let the new framework reference the CocoaLumberjack framework instead.

**Comment by cmittendorf** [comment]
+1 👍

**Comment by DarthMike** [comment]
I think that would very useful. Podspec needs to add public_headers to support being imported as frameworks as with cocoapods.

:+1:

**Comment by robbiehanson** [comment]
Done via pull request #177
