### ISSUE TITLE
YapDatabase registrationConnection can keep a database alive for up to 10 seconds

### ISSUE THREAD

**Issue by Canis-UK** [yapstudios/YapDatabase#132]
In YapDatabase.m, `[YapDatabase registrationConnection]` creates a temporary connection (if one doesn't already exist), and sets it to be nilled out automatically after 10 seconds. I'm guessing this is a caching strategy to avoid churning through connections, especially since a bunch of registrations are likely to occur quickly after a database is first opened, then relatively few after.

However, a side effect is that it holds a reference to the database, keeping it from being destructed, for those 10 seconds. Which, in apps that create a single database at launch and then never close it, isn't an issue.

But, if you're writing a document-based app, with a database per document, it means that if the user opens a document, then closes it again right away, they can't re-open it for up to 10 seconds (because the previous database is still registered with YapDatabaseManager, so attempting to create the YapDatabase returns nil).

Various solutions came to mind:

1. Universally shorten the timeout (simple, but might have performance consequences)
2. Make the timeout configurable by the app at start-of-day (e.g. as a YapDatabaseOption) so the app can decide its own performance tradeoff
3. Make the timeout variable at any time, so it can be left at 10 seconds during normal usage, but the app can set the timeout to zero before releasing the database, and expect it to go away promptly
4. Make the timeout very short but based on last-usage, so each use extends the timeout by a little bit, rather than a flat timeout from the first time the registrationConnect is requested (this seems like the "cleanest" solution, but I might be misunderstanding the performance characteristics)
5. Add some kind of shutdown method (that cancels the timeout similarly to option 3, but leaves that fact as an implementation detail, rather than an official part of the API)

- - -

As an experiment, I've taken approach 3 in my own codebase. The implementation is kinda messy though, since GCD doesn't allow you to change the trigger time of a block after it's been dispatched, so I came up with a way to implement that. But it balloons out the implementation of the `registrationConnection` method, so I suspect you probably don't want to use it :) (Or you might just be philosophically opposed to exposing that timeout as a part of the API). But I'm happy to share it if you want it.

**Comment by robbiehanson** [comment]
Fixed in the 2.6 branch:

- The default timeout was reduced from 10 seconds to 5 seconds
- Added extension registration methods that take a custom YapDatabaseConnection (so you can control its lifetime)
