### ISSUE TITLE
YapDatabaseQuery and Swift

### ISSUE THREAD

**Issue by calebd** [yapstudios/YapDatabase#136]
Using `YapDatabaseQuery` from Swift could be better.

First, any good variadic argument API has two forms: one that takes a `va_list`, and one that takes variadic arguments. API consumers can switch between them with ease, one calls the other, and it means the API can be used from Swift with a simple wrapper.

Second, I see no reason that the class methods that build queries can't be initializers. Changing `queryWithFormat:` to `initWithFormat:` cleans up the Swift syntax quite a bit. `YapDatabaseQuery.queryWithFormat(...)` becomes `YapDatabaseQuery(format: "", arguments: ...)`.

I will open a pull request with these changes.

**Comment by calebd** [comment]
On second thought, `queryWithFormat:arguments:` does a lot that would be messy in an initializer. Going with this for now.

**Comment by calebd** [comment]
If everyone is ok with northtech/YapDatabase#7cc0f34012a96dc9ab2ec5e97a9883885a48248e I will send a pull request. I prefixed the function name so it wouldn't show up in normal API usage since it is purely a shim for Swift code. Would love some feedback!

**Comment by robbiehanson** [comment]
> any good variadic argument API has two forms: one that takes a va_list, and one that takes variadic arguments.

Good point.
