### ISSUE TITLE
Prehooks: Hooks that trigger before an operation, as well as after?

### ISSUE THREAD

**Issue by Canis-UK** [yapstudios/YapDatabase#140]
I've been looking into pre-hooks for extensions, that fire before an operation occurs, unlike the current ones that fire after the operation — analogous to KVO's willChange/didChange pairs. My motivation is that I'm experimenting with writing an extension that allows you to undo/redo database commits — for every change in a read/write transaction, it stores a command that reverses that change. Play these in reverse-order in a new read/write transaction, and the change is undone (and the same system observes *those* changes, and stores *their* inverse to create the redo buffer). In order to do this, it needs to be able to see what the state was before the change occurred.

I have this up and running on my own machine, but, I wanted to sound out how you felt about the idea? There are some small performance considerations: Obviously, twice as many hook-messages are sent, and also in some cases it requires generating the `cacheKey` sooner than it would normally, so that it can be passed in to the hooks. Maybe there are other issues with the idea, as well.

I've implemented this in a branch (c79ca355689d1045ac8c996c0d6eeb00fd920cac) if you want to take a look at my implementation. I can create a pull request, if that's the right thing to do (not really sure what the appropriate GitHub etiquette is, sorry) or you may have a better idea of how to implement this — or, a reason why this is a bad idea :)

**Comment by robbiehanson** [comment]
I love the idea !  I've been planning on adding something like this another upcoming extension: YapDatabaseHooks. (Something I've been wanting to write that exposes bits of these hooks in an accessible manner for those who just want to write a tiny bit of "glue code.)

> I can create a pull request, if that's the right thing to do
Yup. If you create it, I'll merge it. 

> (not really sure what the appropriate GitHub etiquette is, sorry)
No worries. Yeah, that's the appropriate thing for me to request, as that way your commit goes into the repository, and therefore you get credit for the work. (As opposed to me copying your diff, and then submitting my own commit.)

**Comment by Canis-UK** [comment]
Great! I've just fired off the pull request.

**Comment by robbiehanson** [comment]
Merged into v2.6 branch. (Which I'm planning on releasing very soon.)
