### ISSUE TITLE
CocoaLumberjack Update

### ISSUE THREAD

**Issue by donholly** [yapstudios/YapDatabase#142]
Looks like the required version of CocoaLumberjack is < 2.0.0. Any plans to update this?

**Comment by robbiehanson** [comment]
:) Apparently I'm having trouble keeping up with the project I started. Haha (I originally wrote CocoaLumberjack.)

But yes, let's get CocoaLumberjack up to speed.

**Comment by Soryu** [comment]
Is this still on the radar? Do you need a PR? Does it only boil down to the use of `LOG_OBJC_MAYBE` which is not in CocoaLumberjack 2.0 anymore? At least that is what I saw at a first glance.

**Comment by robbiehanson** [comment]
YapDatabase v2.7 will use CocoaLumberjack 2.0+. In fact, it's already available in the 2.7 branch.
