### ISSUE TITLE
[Feature request] range query support

### ISSUE THREAD

**Issue by tianzhou** [yapstudios/YapDatabase#144]
First of all. Really amazing work and make it open source!

I read a bit of the implementation. I think one thing really prevents it from being used in some applications is its inability to specify range query. (e.g. Show the first 10 records or show 10 records starting from the 10th record). This is useful and important for application storing many rows and only wanting to load what's needed.

**Comment by corristo** [comment]
View mappings can do this: https://github.com/yapstudios/YapDatabase/wiki/Views#fixed_ranges
Also it seems that you can use `LIMIT` and `OFFSET` with `YapDatabaseQuery`: https://github.com/yapstudios/YapDatabase/wiki/Secondary-Indexes#using-secondary-indexes

**Comment by tianzhou** [comment]
Yup, but my concern here is the performance and to only load the row what's needed. It seems like YapDatabase still needs to do a full table scan to find the records. If there are millions of records and the record contains blob, then it would be quite expensive. 

As a comparison, for direct sql manipulation and when the field is properly indexed, the LIMIT and OFFSET will normally just load the rows what's needed.

**Comment by tianzhou** [comment]
Ok, after reading the YapDatabaseSecondaryIndexTransaction.m implementation. I think it actually could  do range query without a full table scan. Thanks corristo!

**Comment by robbiehanson** [comment]
_It's now 2016_

This is a response for those who may later stumble upon this same question.

> Yup, but my concern here is the performance and to only load the row what's needed. It seems like YapDatabase still needs to do a full table scan to find the records.

A YapDatabaseView doesn't perform queries on the fly. Instead, it performs the query once (when the view is first setup), and then it updates itself in the same atomic readWrite transactions in which you modify the database. In other words, once you've setup a YapDatabaseView, no queries need to be performed. So no table scans. If you have a YDBView, then using mappings, and setting range properties on the mappings will result in near-zero overhead.

Another way to think of it is like this:

Think of a YapDatabaseView as an array of (collection, key) tuples from your database. The array is already in-memory. Is there any significant overhead to ask for NSRange(10, 10) in the array? Of course not. Same thing with a YapDatabaseView.
