### ISSUE TITLE
Not working enumerateKeysMatching: on iOS 8.3 beta

### ISSUE THREAD

**Issue by Spetruk** [yapstudios/YapDatabase#145]
On iOS 8.3 beta don't enter in block, on previous iOS version it work. If i write @"%@" - work for match strings.
```
[[transaction extension:kProviderTreeItemsFTSExtensionName] enumerateKeysMatching:[NSString stringWithFormat:@"*%@*", [searchQuery lowercaseString]]
                                                           usingBlock:^(NSString *collection, NSString *key, BOOL *stop) {
                                                               [result addObject:[transaction objectForKey:key inCollection:collection]];
                                                           }];
```

**Comment by robbiehanson** [comment]
Did the sqlite version change in iOS 8.3 beta ?

(The 2.6 branch has a property to get the sqlite version as a NSString: database.sqliteVersion)

**Comment by Spetruk** [comment]
iOS 8.1 sqlite version 3.7.13
iOS 8.3 sqlite version 3.8.5

**Comment by robbiehanson** [comment]
To my knowledge, FTS doesn't support suffix matching:

- term* -> supported
- *term -> not supported (directly)
- *term* -> not supported (directly)

I made a comment about this is issue #24 (awhile back) that may be helpful:

    One common problem that iOS/Mac developers will encounter with sqlite's FTS module is that it only supports prefix matching. That is, if you have the term "robbie" in the index, and you search for "*obbie", it won't match. This might work for some apps, but I think many people will find this to feel foreign to how search usually works on the platform.
    
    There's a good description of the problem, and the solution, here:
    http://blog.kapeli.com/sqlite-fts-contains-and-suffix-matches

**Comment by Spetruk** [comment]
@robbiehanson thanks for helpful answer. i made term* and method:
```
- (void)buildFTSCache
{
     id block = ^(NSMutableDictionary *dict, NSString *collection, NSString *key, id object) {
         TTProvider *provider = object;
         dict[@"title"] = [self updateTextForFastSearch:provider.title];// string tring ring ing ng g
     };
    YapDatabaseFullTextSearchHandler *fullTextSearchHandler = [YapDatabaseFullTextSearchHandler withObjectBlock:block];
    YapDatabaseExtension *extension = [[YapDatabaseFullTextSearch alloc] initWithColumnNames:@[@"title"] handler:fullTextSearchHandler versionTag:@"5"];
    [self.database registerExtension:extension withName:TTProviderTreeItemsFTSExtensionName];
}
```

**Comment by PeterWong2015** [comment]
[[transaction ext:@"fts"] enumerateKeysMatching:@"author:john tweet:\\"board meeting\\""
                                         usingBlock:^(NSString *collection, NSString *key, BOOL *stop) {
        // ...
    }];

it's working now on ios 8.1?
