### ISSUE TITLE
Change elements order in the same view

### ISSUE THREAD

**Issue by apascual** [yapstudios/YapDatabase#149]
Hi,

Thank you for the great framework! 🍻

I am trying to animate the cells of a tableview according to different ways of sorting the data, but I can't find an easy way of doing this. Can you help me?

*EDIT:* I found this closed issue #12 with the very same topic, the recommendation was using one new view and mapping for each case, but then the db change notifications will also be view-dependant, right? There won't be a way of animating the cells from/to the new position.

**Comment by calebd** [comment]
https://github.com/yapstudios/YapDatabase/wiki/Views#animating-updates-in-tableviews--collectionviews

**Comment by robbiehanson** [comment]
Thanks @calebd 

> the recommendation was using one new view and mapping for each case, but then the db change notifications will also be view-dependant, right? There won't be a way of animating the cells from/to the new position.

Good question. Let's consider two similar, but very different models that may drive a tableView / collectionView:

1. Something akin to an IM buddy list. In this scenario, user A is in one of the following groups/sections: Available, Away, Offline. What we want, in terms of UI, is if user A transitions from Offline to Available, then we should see him/her move from the Offline section to the Available section. If we break this down, then in terms of YapDatabaseView, an object should only be allowed in a single group at a time. And Mappings should detect a change from one group to another, and emit the proper Move operation (which allows us to properly animate our view).

2. Some kind of "tagging" solution, where an article might have multiple tags such as: Economics, Oregon. What we want, in terms of UI, if if the "Economics" tag is removed, and "Brewing" is added, then we don't want a Move operation. We actually want two different operations: Delete from Economics section & Insert into Brewing section. If we break this down, then in terms of YapDatabaseView, and object should be allowed in multiple groups at a time. And Mappings should ignore inter-group movement (only emit operations per group).

For people in situation 1, YapDatabaseView + Mappings is perfect. For people in situation 2, it's far from ideal currently. The goal, long term, is to modify YapDatabaseView & Mappings to be configurable such that it supports both 1 & 2.

For now, there are workarounds. Let's say you want to display 3 "tags" in a tableView. You could create 3 YapDatabaseView instances, one for each tag. And then you decide the order of these tags within your tableView. E.g.: section0=planes, section1=trains, section2=automobiles. Thus, you'd have 3 YDBViews, and 3 YDBMappings. And you would simply ask each of the 3 mappings for it's rowChanges. And then simply adapt the rowChanges to match the proper section that you're using. For example:

- You ask the mappings for "automobiles" for its rowChanges
- Enumerate over these
- And modify the section to be 2 for each rowChange

**Comment by apascual** [comment]
@robbiehanson Thank you very much for your answer, I was actually thinking in something simpler:

For example a list of books, imagine a model class *Book* with different properties such as **publisher**, **edition**, **IBSN**, **title**, **pages**... Now, I want to display my books, but I want to change dynamically the way the books are sorted in the view (and animate the cell repositioning).

After reading more carefully the Wiki, I think this might be possible to achieve by using the **Secondary indexes** but I haven't tried it yet.

**Comment by robbiehanson** [comment]
Another option to contemplate: You can modify the groupingBlock & sortingBlock of an existing YDBView on-the-fly.

For example: You can create a YDBView that initially has the books sorted by title. And then, if the user changes the option to sort by publisher (for example), you could do something like this:

```objective-c
[databaseConnection asyncReadWriteWithBlock:^(YapDatabaseReadWriteTransaction *transaction){

    [[transaction ext:"MyView"] setGrouping:newGrouping sorting:newSorting versionTag:@"byPublisher"];
}];
```

The end result being that you'll get a change-set (sectionChanges & rowChanges via YDBView + Mappings) that you can use to easily animate the view.
