### ISSUE TITLE
CKErrorInternalError

### ISSUE THREAD

**Issue by cobysy** [yapstudios/YapDatabase#151]
It's not a code issue per se but I'm getting a CKErrorInternalError back in the opErrorBlock (in setupCloudKitExtension). 
I'm using Xcode 6.2, iPhone simulator, and made sure that I'm signed into iCloud in the simulator phone settings. 
What am I missing here?

```
2015-03-26 03:33:18:371 CloudKitTodo[48245:607] RootViewController - resumeButtonTapped:
2015-03-26 03:33:18:372 CloudKitTodo[48245:607] YapDatabaseCloudKit: => RESUMED
2015-03-26 03:33:18:372 CloudKitTodo[48245:607] YapDatabaseCloudKit: asyncMaybeDispatchNextOperation:
2015-03-26 03:33:18:372 CloudKitTodo[48245:4c27] YapDatabaseCloudKit: Queueing operation: <YDBCKChangeSet: 0x7ffec3f27a00>
2015-03-26 03:33:18:372 CloudKitTodo[48245:4c27] YapDatabaseCloudKit: queueOperationForChangeSet:
2015-03-26 03:33:18:372 CloudKitTodo[48245:4c27] YapDatabaseCloudKit: CKModifyRecordsOperation UPLOADING: databaseIdentifier = (null):
  recordsToSave: (
    "<CKRecord: 0x7ffec550a160; recordType=todo, recordID=D81FA3F3-6E80-4374-B3C8-E0BC4F397F08:(zone1:__defaultOwner__), recordChangeTag=(null), values={\n    created = \"2015-03-26 02:26:02 +0000\";\n    isDone = 0;\n    lastModified = \"2015-03-26 02:26:02 +0000\";\n    priority = 0;\n    title = a;\n    uuid = \"D81FA3F3-6E80-4374-B3C8-E0BC4F397F08\";\n}>"
)
  recordIDsToDelete: (null)
2015-03-26 03:33:18:406 CloudKitTodo[48245:607] CloudKitManager - cloudKitInFlightChangeSetChanged:
2015-03-26 03:33:18:409 CloudKitTodo[48245:681b] YapDatabaseCloudKit: CKModifyRecordsOperation error: databaseIdentifier = (null)
  error = <CKError 0x7ffec5008ca0: "Internal Error" (1/2005)>
2015-03-26 03:33:18:420 CloudKitTodo[48245:681b] YapDatabaseCloudKit: handleFailedOperationWithChangeSet:error:
2015-03-26 03:33:18:420 CloudKitTodo[48245:681b] YapDatabaseCloudKit: => SUSPENDED : incremented suspendCount == 1
2015-03-26 03:33:18:420 CloudKitTodo[48245:607] CloudKitManager - cloudKitInFlightChangeSetChanged:
2015-03-26 03:33:18:420 CloudKitTodo[48245:607] Unhandled ckErrorCode: 1
```

**Comment by cobysy** [comment]
Sorry, I'm completely new to CloudKit so bear with me.

So far I've found out that I need to change the Bundle Identifier in order to ensure uniqueness in the CloudKit container name. That got rid of the ckErrorCode: 1 error.

Next I figured that I needed to define a "todo" Record Type in the CloudKit Dashboard. 
So far I've defined
creationDate  : Date/Time
lastModified : Date/Time
uuid : String
title : String
isDone : Integer
priority : Integer

That has fixed all my troubles (for now).

**Comment by robbiehanson** [comment]
> So far I've found out that I need to change the Bundle Identifier

Ah, yes. You likely have to change the bundle ID, and setup the provisioning profile, etc. I always forget about these steps. I should mention this in a readme...

> Next I figured that I needed to define a "todo" Record Type in the CloudKit Dashboard.

For future reference, you shouldn't have to do this. They are created automatically via CloudKit.

**Comment by cobysy** [comment]
Thanks Robbie,
just for the sake of it I deleted my manually created "todo" record type and tried again.
Works seamlessly like you said. Not sure why it was complaining before (must have something messed up on my side).

P.S. I'm trying to switch to Swift, would you have any objections against porting the DatabaseManager and CloudKitManager classes from the CloudKitTodo project (as in: completely rewriting them in Swift) or should I use them as is in ObjC form and make use of them from Swift via bridging (and some configuration of course). I kind of see them as a "reference implementation" so aiming for "the path of least resistance" if any changes (fixes) are made to them.

**Comment by aminas** [comment]
This works great. Good work. I also look forward to get to work with this feature. The code is not that easy to grasp in 1st glance though. A readme or tutorial is really necessary for todo app.

**Comment by robbiehanson** [comment]
> would you have any objections against porting the DatabaseManager and CloudKitManager classes [to Swift]

Nope, you’re welcome to do that. They are simply “reference implementations”, and/or starter implementations. My expectation is that someone might take them, copy them into their own project, and then begin to modify them as needed, or as they see fit. So you’re more than welcome to convert them to Swift.

(Basically, the CloudKitManager just gives a reference implementation of all the boiler plate code that is needed to properly interact with Apple’s CloudKit framework. So it’s just a sample to get you started in the right direction.)

-Robbie Hanson



On March 26, 2015 at 4:49:45 PM, cobysy (notifications@github.com) wrote:

Thanks Robbie,
just for the sake of it I deleted my manually created "todo" record type and tried again.
Works seamlessly like you said. Not sure why it was complaining before (must have something messed up on my side).

P.S. I'm trying to switch to Swift, would you have any objections against porting the DatabaseManager and CloudKitManager classes from the CloudKitTodo project (as in: completely rewriting them in Swift) or should I use them as is in ObjC form and make use of them from Swift via bridging (and some configuration of course). I kind of see them as a "reference implementation" so aiming for "the path of least resistance" if any changes (fixes) are made to them.
