### ISSUE TITLE
Add Nullability Annotations

### ISSUE THREAD

**Issue by danthorpe** [yapstudios/YapDatabase#162]
Adding nullability annotations would significantly aid in the reasoning of YapDatabase's APIs, and vastly improve their Swift representations. There are a number of classes to update, but the significant ones are...

- [ ] YapDatabase
- [ ] YapDatabaseConnection
- [ ] YapDatabaseTransaction

**Comment by danthorpe** [comment]
I'm working on adding these at the moment, so will submit a PR against this today hopefully.

**Comment by robbiehanson** [comment]
Merged pull request #163
