### ISSUE TITLE
Support for UITableView/UICollectionView move animations

### ISSUE THREAD

**Issue by datwelk** [yapstudios/YapDatabase#164]
I'm using YapDatabaseView to display a homogeneous array of objects in the same collection. The objects feature a property `foo` by which they are sorted. 

The UI allows the user to change the value of `foo`. As a consequence of such a change, Yap generates row changes with type `YapDatabaseViewChangeMove`. Unlike the name suggests, these changes are tailored to `UITableView`'s `-insertItemsAtIndexPaths:` and `-deleteItemsAtIndexPaths:` methods as opposed to `-moveItemAtIndexPath:toIndexPath:`. 

What I'm looking for is a way for Yap to generate `YapDatabaseViewChangeMove` changes such that they can be used in combination with `-[UICollectionView moveItemAtIndexPath:toIndexPath:]`.

**Comment by jj0b** [comment]
I'm also trying to get a YapDatabaseView updating a UICollectionView and having difficulty. I'm trying in Swift, which is making it even more difficult.

**Comment by robbiehanson** [comment]
Are you processing all the YapDatabaseViewRowChange items within ```[UICollectionView performBatchUpdates:completion:]``` ?

**Comment by jj0b** [comment]
In a Swift app I'm working on I've got collection views updating correctly using performBatchUpdates:completion:. I broke the updating of the sections and rows into two different methods. I actually have these methods in my DatabaseManager class, but you could also just do the same thing directly in your UICollectionView subclass. Hope this might help you @datwelk 

    func processSectionChanges(sectionChanges: NSArray) {
        collectionView?.performBatchUpdates({ () -> Void in
            for sectionChange in sectionChanges {
                if let sectionChange = sectionChange as? YapDatabaseViewSectionChange {
                    switch (sectionChange.type) {
                    case YapDatabaseViewChangeType.Delete:
                        let indexSet = NSIndexSet(index: Int(sectionChange.index))
                        self.collectionView?.deleteSections(indexSet)
                    case YapDatabaseViewChangeType.Insert:
                        let indexSet = NSIndexSet(index: Int(sectionChange.index))
                        self.collectionView?.insertSections(indexSet)
                    default:
                        println("nothing to do here")
                    }
                }
            }
            }, completion: { (finished) -> Void in
        })
    }
    
    func processRowChanges(rowChanges: NSArray) {
        collectionView?.performBatchUpdates({ () -> Void in
            for rowChange in rowChanges {
                if let rowChange = rowChange as? YapDatabaseViewRowChange {
                    switch (rowChange.type) {
                    case YapDatabaseViewChangeType.Delete:
                        self.collectionView?.deleteItemsAtIndexPaths([rowChange.indexPath])
                    case YapDatabaseViewChangeType.Insert:
                        self.collectionView?.insertItemsAtIndexPaths([rowChange.newIndexPath])
                    case YapDatabaseViewChangeType.Move:
                        self.collectionView?.moveItemAtIndexPath(rowChange.indexPath, toIndexPath: rowChange.newIndexPath)
                    case YapDatabaseViewChangeType.Update:
                        self.collectionView?.reloadItemsAtIndexPaths([rowChange.indexPath])
                    default:
                        println("nothing to do here")
                    }
                }
            }
            }, completion: { (finished) -> Void in
        })
    }
