### ISSUE TITLE
YDB_NodeDeleteRules is a C-style enum

### ISSUE THREAD

**Issue by jj0b** [yapstudios/YapDatabase#165]
Because YDB_NodeDeleteRules is a C-style enum it does not work well with Swift. This should be changed to an NS_OPTIONS enumeration so that you can access the items in the enumeration with simple dot syntax.

**Comment by jj0b** [comment]
Pull Request issued that fixes this.

**Comment by robbiehanson** [comment]
Fixed via pull request #166
