### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by kodayashi** [yapstudios/YapDatabase#169]
It'd be great if release notes or a changelog was included in new releases. This would help developers with production apps decide when to consume to new versions.

**Comment by robbiehanson** [comment]
Action item: Update changelog for all releases up to 2.6.2

https://github.com/yapstudios/YapDatabase/wiki/Changelog

**Comment by kodayashi** [comment]
No problem, thanks for the quick triage! I'll let our team know that the changelog will be updated.

**Comment by robbiehanson** [comment]
Done - https://github.com/yapstudios/YapDatabase/wiki/Changelog

**Comment by accatyyc** [comment]
Hi! Just got this: `Installing YapDatabase 2.8.1 (was 2.7.7)`

Very exciting! Requesting an update to the Changelog as well.

**Comment by robbiehanson** [comment]
Updated through 2.8.1 - https://github.com/yapstudios/YapDatabase/wiki/Changelog

**Comment by accatyyc** [comment]
@robbiehanson Thanks! 😊
