### ISSUE TITLE
Can't create YapDatabaseQuery in Swift

### ISSUE THREAD

**Issue by jj0b** [yapstudios/YapDatabase#170]
I'm struggling to create a query in Swift and I'm not sure if this is due to a bug or a lack of understanding of how to create a query. 

I've added the YapDatabase extension detailed in the YapDatabaseQuery header and I've tried:

    var query: YapDatabaseQuery = YapDatabaseQuery(format: "WHERE authToken IS NOT NULL", arguments:nil)

this gives the error:

    Cannot find an initializer for type 'YapDatabaseQuery' that accepts an argument list of type '(format: String, arguments: nil)'

I assumed this was because arguments need to be Objective-C types according to the header, so I then tried this:

    var query: YapDatabaseQuery = YapDatabaseQuery(format: "WHERE authToken ?", arguments:NSString(string: "IS NOT NULL"))

But I still get an error even with passing an NSString:

    Cannot find an initializer for type 'YapDatabaseQuery' that accepts an argument list of type '(format: String, arguments: NSString)'

**Comment by jeremiegirault** [comment]
Yes variable arguments list functions in objc are not available in swift
I made a small wrapper using objc bridging :
````
@interface YapDatabaseQuery (Swift)

+(instancetype)queryWithFormatSimple:(NSString*)format;
+(instancetype)queryWithFormat:(NSString*)format arg1:(id)arg;

@end

@implementation YapDatabaseQuery (Swift)

+(instancetype)queryWithFormatSimple:(NSString*)format {
    return [self queryWithFormat:format];
}

+(instancetype)queryWithFormat:(NSString*)format arg1:(id)arg {
    return [self queryWithFormat:format, arg];
}

@end
````
You can add as many arguments as you want.

A function with an NSArray argument list would be convenient for people using swift

**Comment by jj0b** [comment]
Thanks, I'll give this a try.

Looking at YapDatabaseQuery, it looks like all that may be needed would be to expose this existing method in the header:

    - (id)initWithQueryString:(NSString *)inQueryString queryParameters:(NSArray *)inQueryParameters;

**Comment by jj0b** [comment]
Thanks @jeremiegirault your solution worked perfectly.

**Comment by maelp** [comment]
Here is another way :)

```
var arguments: [CVarArgType] = [minLon, maxLon, minLat, maxLat].map({NSNumber(double: $0)}) // must be var to get a pointer, must be a NSObject to be formatted
let queryString = "WHERE \"minLon\" >= ? AND \"maxLon\" <= ? AND \"minLat\" >= ? AND \"maxLat\" <= ?"
let query = withVaList(arguments, { (pointer: CVaListPointer) -> YapDatabaseQuery in
    return YapDatabaseQuery(format: queryString, arguments: pointer)
})
```

**Comment by robbiehanson** [comment]
I refactored the internals of YapDatabaseQuery in order to expose this method for Swift :

```objective-c
/**
 * Alternative initializer - generally preferred for Swift code.
**/
+ (instancetype)queryWithString:(NSString *)queryString parameters:(NSArray *)queryParameters;
```
