### ISSUE TITLE
Restrictions for view naming

### ISSUE THREAD

**Issue by estbyright** [yapstudios/YapDatabase#176]
I heve complex view names in my application and got errors on extensions logic.

For example classes.scopeKey=-JiVgq2C77zdH35Eekce

Log:

YapDatabaseViewTransaction: prepareIfNeeded (classes.scopeKey=-JiVgq2C77zdH35Eekce): Cannot create 'enumerate_stmt': 1 no such table: view_classes.scopeKey=-JiVgq2C77zdH35Eekce_page
  
2015-05-26 11:15:27:915[12878:607] YapDatabaseViewTransaction: prepareIfNeeded (classes.scopeKey=-JiVgq2C77zdH35Eekce): Cannot create 'enumerate_stmt': 1 no such table: view_classes.scopeKey=-JiVgq2C77zdH35Eekce_page
2015-05-26 11:15:27:916[12878:607] YapDatabaseViewTransaction: prepareIfNeeded (classes.scopeKey=-JiVgq2C77zdH35Eekce): Cannot create 'enumerate_stmt': 1 no such table: view_classes.scopeKey=-JiVgq2C77zdH35Eekce_page

I found this http://stackoverflow.com/questions/3694276/what-are-valid-table-names-in-sqlite
I think it limited with SQLite table naming restrictions. For example "." and "-" both are illegal for table names. To make these allowed, we may have to quote them in "". 
example CREATE TABLE "123.abc"

Think it should be described in method documentation. (Mean previousVersionTagForRegisteredViewName:)

**Comment by robbiehanson** [comment]
I'm been unable to reproduce this. I tried creating a view with the name "classes.scopeKey=-JiVgq2C77zdH35Eekce", and everything worked fine for me. The code in question is this:

```objective-c
NSString *string = [NSString stringWithFormat:
  @"SELECT \"pageKey\", \"group\", \"prevPageKey\", \"count\" FROM \"%@\";", [self pageTableName]];

int const column_idx_pageKey     = SQLITE_COLUMN_START + 0;
int const column_idx_group       = SQLITE_COLUMN_START + 1;
int const column_idx_prevPageKey = SQLITE_COLUMN_START + 2;
int const column_idx_count       = SQLITE_COLUMN_START + 3;

sqlite3_stmt *statement = NULL;

int status = sqlite3_prepare_v2(db, [string UTF8String], -1, &statement, NULL);
if (status != SQLITE_OK)
{
	YDBLogError(@"%@ (%@): Cannot create 'enumerate_stmt': %d %s",
		THIS_METHOD, [self registeredName], status, sqlite3_errmsg(db));
	return NO;
}
```

So the table name is being quoted. In fact, I try hard to quote every such user input.

Was there anything else in the log? Perhaps from earlier warnings?

**Comment by estbyright** [comment]
No, nothing else. Maybe it is my badcode. Sorry for inconvinience.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On Mon, Jun 1, 2015 at 1:14 AM, yapstudios/YapDatabase
<reply@reply.github.com>
wrote:
I'm been unable to reproduce this. I tried creating a view with the name
"classes.scopeKey=-JiVgq2C77zdH35Eekce", and everything worked fine for me. The
code in question is this:

NSString *string = [NSStringstringWithFormat:@"SELECT \"pageKey\", \"group\", \"prevPageKey\", \"count\" FROM \"%@\";", [selfpageTableName]];

intconst column_idx_pageKey     = SQLITE_COLUMN_START + 0;
intconst column_idx_group       = SQLITE_COLUMN_START + 1;
intconst column_idx_prevPageKey = SQLITE_COLUMN_START + 2;
intconst column_idx_count       = SQLITE_COLUMN_START + 3;

sqlite3_stmt *statement = NULL;

int status = sqlite3_prepare_v2(db, [string UTF8String], -1, &statement, NULL);
if (status != SQLITE_OK)
{
    YDBLogError(@"%@ (%@): Cannot create 'enumerate_stmt': %d%s",
        THIS_METHOD, [selfregisteredName], status, sqlite3_errmsg(db));
    returnNO;
}

So the table name is being quoted. In fact, I try hard to quote every such user
input.

Was there anything else in the log? Perhaps from earlier warnings?

—
Reply to this email directly or view it on GitHub
[https://github.com/yapstudios/YapDatabase/issues/176#issuecomment-107252610] .[https://github.com/notifications/beacon/ACK7UyEo_5JG9DYkgEPnq1PVAvOXZd3Iks5oO39AgaJpZM4Ep15_.gif]

**Comment by estbyright** [comment]
Logic that causes that behaviour based on FTS implementation. I check out
later on fresh project something similar to :

Creation of YapDatabaseSearchResultsView instance and YapDatabaseFullTextSearch
for it's columns and try to search.

 YapDatabaseSearchResultsViewOptions *options = [
YapDatabaseSearchResultsViewOptions new];

    NSSet *groups = [NSSet setWithArray:@[@"all"]];

    YapWhitelistBlacklist *allowedGroups = [[YapWhitelistBlacklist alloc]
initWithWhitelist:groups];

    YapWhitelistBlacklist *allowedCollections =

        [[YapWhitelistBlacklist alloc] initWithWhitelist: [NSSet
setWithArray:@[@"test"]]];

    options.allowedCollections = allowedCollections;

    options.allowedGroups = allowedGroups;

    options.isPersistent = NO;

    options.skipInitialViewPopulation = YES;


    YapDatabaseSearchResultsView *result =

        [[YapDatabaseSearchResultsView alloc] initWithFullTextSearchName
:FTSName

                                                          parentViewName
:parentView.name

                                                              versionTag:
self.versionTag

                                                                 options
:options];

YapDatabaseFullTextSearch *result =

        [[YapDatabaseFullTextSearch alloc] initWithColumnNames:columnNames

                                                       handler:self.handler

                                                    versionTag:@"version=1"
];



NSCharacterSet *whitespace = [NSCharacterSet whitespaceCharacterSet];

    NSArray *searchComponents = [sequence
componentsSeparatedByCharactersInSet:whitespace];

    NSMutableString *query = [NSMutableString string];



    for (NSString *term in searchComponents)

    {

        if ([term length] > 0)

            [query appendString:@""];



        [query appendFormat:@"%@*", term];

    }

    YapDatabaseSearchQueue *searchQueue = [[YapDatabaseSearchQueue alloc]
init];

    [searchQueue enqueueQuery:query];

    [self.connection asyncReadWriteWithBlock:^(
YapDatabaseReadWriteTransaction *transaction) {

        [[transaction ext:self.view.name] performSearchWithQueue:
 searchQueue];

    } completionBlock:completion];




2015-06-01 10:46 GMT+03:00 Konstantin Bucha <estbyright@gmail.com>:

**Comment by estbyright** [comment]
Think should be closed. It was my fault in implementation.
