### ISSUE TITLE
-weak_library Conflicts with ENABLE_BITCODE=YES

### ISSUE THREAD

**Issue by samus** [yapstudios/YapDatabase#180]
Xcode 7 enables the new Bitcode App Thinning technology by default resulting in a linker error.

`ld: warning: -weak_library is treated as a regular library when used with -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES). Weak linking may still happen based on availability mark-up in headers
ld: -weak_library and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together`

**Comment by pbassut** [comment]
+1, same issue here.

**Comment by chrisballinger** [comment]
It seems that libc++ could be strongly linked as long as only newer platforms are targeted (10.9+ and iOS 7+)

**Comment by simonlinj** [comment]
Are you using Xcode 7 beta? You probably having ENABLE_BITCODE option enabled.  Disable it for the time being.

Note: ENABLE_BITCODE is mandatory when building for watchOS. hence your have include the bit-code for each library or framework you are using

**Comment by michaelhenry** [comment]
+1

**Comment by sbhhbs** [comment]
+1

**Comment by aranasaurus** [comment]
+1 :(

**Comment by TomCarey** [comment]
+1 though I noticed that someone did this in a fork recently https://github.com/ello/YapDatabase/commit/0c0345d69ded9b1ce41040f911fb5d95ece4faf7

**Comment by robbiehanson** [comment]
The v2.7.3 podspec is now pushed, which should fix this issue.
