### ISSUE TITLE
how to disable logging

### ISSUE THREAD

**Issue by xinwo** [yapstudios/YapDatabase#182]
#define YapDatabaseLoggingTechnique_Lumberjack 2 // optimal
#define YapDatabaseLoggingTechnique_NSLog      1 // slower
#define YapDatabaseLoggingTechnique_Disabled   0 // disabled

if I define YapDatabaseLoggingTechnique to 0 in Build setting,
there will be compiler error

YapDatabase/Extensions/CloudKit/YapDatabaseCloudKit.m:22:1: Expected identifier

--------------------------------------------------------------------------------------------
		if (newSuspendCount == 0)
			YDBLogInfo(@"=> RESUMED");
		else
			YDBLogInfo(@"=> SUSPENDED : decremented suspendCount == %lu", (unsigned long)newSuspendCount);
		
		[self postSuspendCountChangedNotification];
--------------------------------------------------------------------------------------------

**Comment by robbiehanson** [comment]
Pushed a fix. Let me know if you encounter any other problems concerning this issue.

**Comment by robbiehanson** [comment]
By the way, in case you're wondering, the build error was because the code was compiled into this (via macros):

```objective-c
if (newSuspendCount == 0)
        {};
else
        {};
```

**Comment by xinwo** [comment]
thank you
