### ISSUE TITLE
Crash on replaceMetadata:forKey:inCollection with filtered views

### ISSUE THREAD

**Issue by vkovtash** [yapstudios/YapDatabase#186]
Hi guys. Thanks for such a nice tool.
I found a strange crash in some cases while using filtered views.
Here some tests to reproduce it https://github.com/vkovtash/YapDbFilteredViewCrash

**Comment by robbiehanson** [comment]
Many thanks!

I was able to quickly identify the problem thanks to your unit tests. I was also able to copy their design in the official unit tests in order to add test coverage for the offending code paths.
