### ISSUE TITLE
dyld: Library not loaded: /System/Library/Frameworks/CloudKit.framework/CloudKit

### ISSUE THREAD

**Issue by Onetaway** [yapstudios/YapDatabase#193]
On a iPad with iOS 7 . I got this error when the app run.

```
dyld: Library not loaded: /System/Library/Frameworks/CloudKit.framework/CloudKit
  Referenced from: /private/var/mobile/Applications/B487DA6C-765B-4D24-9342-CBE074E39925/BaoZouCamera.app/Frameworks/YapDatabase.framework/YapDatabase
  Reason: image not found
```

I wonder if YapDatabase use CloudKit. How can I solve this problem.

**Comment by robbiehanson** [comment]
As you know, Apple's CloudKit is new in iOS 8, and thus requires iOS 8 or later.

YapDatabase contains an optional extension for using CloudKit. The extension is called YapDatabaseCloudKit, and all related source code files reside in "Extensions/CloudKit". To target iOS 7, you can exclude these files from your project.
