### ISSUE TITLE
Backup a database

### ISSUE THREAD

**Issue by maelp** [yapstudios/YapDatabase#194]
Is there a easy way to create or load a compressed backup of a database?

**Comment by robbiehanson** [comment]
Yes, take a look at YapDatabaseConnection within the 2.7 branch:
https://github.com/yapstudios/YapDatabase/blob/2.7/YapDatabase/YapDatabaseConnection.h

There are various methods (such as this one) to enable a simple/quick backup :

```objective-c
/**
 * This method backs up the database by exporting all the tables to another sqlite database.
 *
 * This method operates as an asynchronous readWrite "transaction".
 * That is, it behaves in a similar fashion, and you may treat it as if it is a ReadWrite transaction.
 * 
 * The database will be backed up as it exists at the moment this transaction operates.
 * That is, it will backup everything in the sqlite file, as well as everything in the WAL file.
 * 
 * An optional completion block may be used.
 * The completionBlock will be invoked on the main thread (dispatch_get_main_queue()).
 *
 * For more information on the BACKUP operation, see the sqlite docs:
 * https://www.sqlite.org/c3ref/backup_finish.html
 *
 * As stated in the sqlite docs, it is your responsibilty to ensure that nothing else is
 * currently using the backupDatabase.
 *
 * @return
 *   A NSProgress instance that may be used to track the backup progress.
 *   The progress in cancellable, meaning that invoking [progress cancel] will abort the backup operation.
**/
- (NSProgress *)asyncBackupToPath:(NSString *)backupDatabasePath
                  completionBlock:(nullable void (^)(NSError *error))completionBlock;
```

Concerning compression, that is something that will have to be performed separately. You can likely use something like zlib to do a quick compression.

**Comment by maelp** [comment]
Thanks!

**Comment by zubko** [comment]
I'm using the backup API to grab a generated DB and to copy it to the project to be used for the 1st install of the app. Is it safe to just copy `*.sqlite` file? Most of times there is only `*.sqlite` file but rarely there is also `*.sqlite-shm` one. I haven't seen `*.sqlite-wal` yet.

**Comment by robbiehanson** [comment]
> I'm using the backup API to grab a generated DB

While YapDatabase itself uses sqlite in WAL mode (and therefore creates a *.sqlite-wal file), I believe the backup API only exports a *.sqlite file. From what I understand, it enumerates the pages in the current *.sqlite & *.sqlite-wal in order to generate the backup *.sqlite file.

> Is it safe to just copy *.sqlite file?

In this particular case (using the backup API to grab a generated DB): yes that is safe

**Comment by zubko** [comment]
Thanks. That's good to know.
