### ISSUE TITLE
Swift, YDB 2.7, YapDatabaseLoggingTechniqueDisabled and Foundation problem

### ISSUE THREAD

**Issue by onfoot** [yapstudios/YapDatabase#195]
Hi,
if I disable logging for YapDatabase, a compile error is emitted in YapDatabaseLogging.h file because of an unknown type NSString. Adding importing Foundation to that file helps, though I'm not sure if that's a correct solution, since I'm not that familiar with YapDatabase's codebase and would like to be able to use straight 2.7 branch, without my local uncommitted modifications, which causes Xcode Server builds fail.

Could you please add the line to the 2.7 branch. I can of course submit a pull request, if that makes things easier.

**Comment by robbiehanson** [comment]
Thanks for the report. Should be fixed now. Let me know if you encounter any other problems.

**Comment by onfoot** [comment]
Great, exactly what I needed. Thanks!
