### ISSUE TITLE
Swift & YapDatabaseCloudKitRecordHandler.withObjectBlock

### ISSUE THREAD

**Issue by askay** [yapstudios/YapDatabase#198]
I'm trying to write my record handler in swift, but I'm running into a couple of problems. The signature for the block is:

typealias YapDatabaseCloudKitRecordWithObjectBlock = (inOutObject: AutoreleasingUnsafeMutablePointer<CKRecord?>, YDBCKRecordInfo!, String!, String!, AnyObject!) -> Void

How do I access the CKRecord in the AUMP? I tried
            let record = inOutObject as? CKRecord
and I get a warning: Cast from 'AutoreleasingUnsafeMutablePointer<CKRecord?>' to unrelated type 'CKRecord' always fails

I also attempt to assign a new record to the var:
           inOutObject = newRecord
and I get the error: Cannot assign a value of type 'CKRecord' to a value of type 'AutoreleasingUnsafeMutablePointer<CKRecord?>'

I haven't been able to find anything about accessing the variable from within a callee. Any ideas?

**Comment by SofteqDG** [comment]
You can get access to CKRecord through the "memory" property of the AutoreleasingUnsafeMutablePointer var.
