### ISSUE TITLE
Adding documentation & sample code for RTreeIndex

### ISSUE THREAD

**Issue by chrisballinger** [yapstudios/YapDatabase#199]
Finally got around to implementing R-Tree in [iBurn](https://github.com/burning-man-earth/iburn-ios). So far so good! Turns out RTree is available in the builtin sqlite as of iOS 8.

Considering the vast majority of this is basically boilerplate, it would probably help people if I added a wiki page and some standalone sample code in Swift and Obj-C.

* Swift sample code: https://gist.github.com/maelp/06f621741acf70390252
* [Obj-C R-Tree query](https://github.com/Burning-Man-Earth/iBurn-iOS/blob/1f4ed5ba4388a444e9c1eb30727943f32a65db25/iBurn/BRCDatabaseManager.m#L626) 
* [Obj-C R-Tree setup](https://github.com/Burning-Man-Earth/iBurn-iOS/blob/1f4ed5ba4388a444e9c1eb30727943f32a65db25/iBurn/BRCDatabaseManager.m#L269)

**Comment by robbiehanson** [comment]
> it would probably help people if I added a wiki page

Let me know if you need anything. Currently the wiki is editable by any user, so you should be able to create the wiki page, and add it to the index.

**Comment by chrisballinger** [comment]
Added https://github.com/yapstudios/YapDatabase/wiki/R-Tree-Index

:beer:

**Comment by robbiehanson** [comment]
Nice !
