### ISSUE TITLE
Getting a crash inside YDBCKChangeQueue - updatePendingQueue

### ISSUE THREAD

**Issue by danthorpe** [yapstudios/YapDatabase#200]
This is the crash:

    2015-08-11 17:58:44.932 XXXXX[8677:2260888] *** Terminating app due to uncaught exception   'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
    *** First throw call stack:
    (0x182da42d8 0x194a200e4 0x182c8b4c0 0x10091a4a8 0x100958dd4 0x182c8dd40 0x182c8dc20  0x100957d28 0x1009f5090 0x182c8dd40 0x182c8dc20 0x1009f4d64 0x10096cd5c 0x10096a6cc 0x1013c0f94 0x1013cb08c 0x10096a54c 0x1013c0fd4 0x1013c0f94 0x1013cbdb8 0x1013c42c4 0x1013ce5d4 0x1013d0248 0x19527d22c 0x19527cef0)
    libc++abi.dylib: terminating with uncaught exception of type NSException

I've done a bit of work to follow the crash, and it happens inside:

```
[self postReadWriteTransaction:transaction];
```

then
```
[transaction preCommitReadWriteTransaction];
```

then
```
[(YapDatabaseExtensionTransaction *)extTransactionObj flushPendingChangesToExtensionTables];
```
for my registered CloudKitExtension - bog standard YapDatabaseViews seem okay. Will post more info if I find any...

**Comment by danthorpe** [comment]
Okay, bit more information - and this error is not related to v2.7.

The crash occurs here:

```
[currentChangeSet->deletedRecordIDs addObject:recordID];
```

line 790 in YDBCKChangeQueue because `recordID` is nil.

![yapdatabase cloudkittransaction](https://cloud.githubusercontent.com/assets/309420/9205882/992faac2-405c-11e5-8ac5-d4639eb0e7b2.png)

This occurs in my fetch record changes code - which is mostly copied/adapted from the CloudKitToDo example. I'm going to investigate further to see if there were any errors which I'm ignoring. The scenario that has happened is that I've deleted the app, but there is still content in CloudKit which should appear.

But, regardless of this, the YDBCKChangeQueue shouldn't be trying to add nil onto an array.

**Comment by danthorpe** [comment]
Yep, don't get any errors back from CloudKit. Not sure how but somehow the CloudKitExtension is able to get into this state.

**Comment by robbiehanson** [comment]
I added a commit to a new branch: "issue200". Any chance you could pull that down and test with it?

Make sure you have NSAssert enabled. I added several checks within YDBCKRecordTableInfo. I'm trying to figure out why recordID is nil. The call stack seems to be:

- [YDBCKChangeQueue updatePendingQueue:withDeletedRecordID:databaseIdentifier:]
- [YapDatabaseCloudKitTransaction flushPendingChangesToExtensionTables]

Which is using, as the recordID parameter: dirtyRecordTableInfo.recordID

My hunch is that a code path has allows a dirtryRecordTableInfo instance to become instantiated with a nil recordID property. The code change should hopefully fix this. And the additional asserts will hopefully catch it in other places I may have overlooked.

**Comment by danthorpe** [comment]
Hmm, unfortunately, I've had to reset my cloud kit development environment, so I can no longer reproduce this issue. Sorry - I've got deadlines, but I know that makes this almost impossible to diagnose and fix.

I can share my fetch changes code with you if that would help?

**Comment by robbiehanson** [comment]
Your report was pretty solid in terms of being able to track down what the root cause of the issue was. I'm going to go ahead and merge the issue branch into master.

Let me know if this issue pops up for you again. Hopefully we now have the tools in place to catch it early.

**Comment by danthorpe** [comment]
Thanks Robbie will let you know if it happens again.
