### ISSUE TITLE
Changelog for 2.7

### ISSUE THREAD

**Issue by chrisballinger** [yapstudios/YapDatabase#201]
https://github.com/yapstudios/YapDatabase/compare/2.6.5...2.7

Can some of these be added to the release tag for 2.7? https://github.com/yapstudios/YapDatabase/releases

Looks like the big changes are backups, CLJ 2.0 and mmap. Anything else cool that I'm missing?

**Comment by corristo** [comment]
https://github.com/yapstudios/YapDatabase/wiki/Changelog

**Comment by chrisballinger** [comment]
Durrrrrrrrr

Thanks!
