### ISSUE TITLE
Collecting list of apps that use YapDatabase

### ISSUE THREAD

**Issue by chrisballinger** [yapstudios/YapDatabase#202]
You've got some good install stats: https://cocoapods.org/pods/YapDatabase

> Apps	126
> Apps This Week	77

Here's some (open source) apps that I know are using Yap:

* [iBurn](https://github.com/burning-man-earth/iburn-ios) - offline map and guide for the Burning Man art festival.
* [Signal](https://github.com/WhisperSystems/Signal-iOS) - Free, world-wide, private messaging and phone calls for iPhone.
* [ChatSecure](https://github.com/chatsecure/chatsecure-ios) -  free and open source encrypted chat client that supports OTR encryption over XMPP.
* [Courier](https://github.com/guardianproject/securereader_ios/issues) - Secure Tor-enabled RSS reader

Any other cool ones I should know about?

Btw, we use pretty much every Yap feature in iBurn, including the new R-Tree support :)

**Comment by robbiehanson** [comment]
I didn't know about the CocoaPods stats. That's cool !

Maybe we should make a Wiki page for this? And allow people to add links to their own apps.

**Comment by chrisballinger** [comment]
Ya a wiki page is a good idea. Yeah they added stats in 0.38 :)

**Comment by robbiehanson** [comment]
https://github.com/yapstudios/YapDatabase/wiki/Apps-that-use-YapDatabase

**Comment by chrisballinger** [comment]
:)
