### ISSUE TITLE
Best practices for monitoring for when extension is registered

### ISSUE THREAD

**Issue by chrisballinger** [yapstudios/YapDatabase#203]
In order to speed up my app launch, I register all my extensions in the background, but immediately pass the extensionName to all of the views controllers that will need it. This usually results in some missing UI elements the first time you load the view.

One solution would be to set an observable property for each YapDatabaseExtension on my databaseManager, and then use KVO to refresh my UI when they are registered, but perhaps there is a better way?

**Comment by robbiehanson** [comment]
There are a couple options. From the existing UI code, you can check to see if an extension is registered like this:

```objective-c
[databaseConnection readWithBlock:^(YapDatabaseReadTransaction *transaction){

    if ([transaction ext:Ext_I_Seek] == nil) {
        // extension not registered yet
    }
}];
```

For UI code, the databaseConnection is generally a longLivedReadTransaction too. Which also means it's listening for YapDatabaseModifiedNotifications. And every-time an extension is registered, it will fire this notification. Which means you could plug in the above code into your databaseModified method.

So, in a way, YapDatabase is already posting a notification. To handle this situation, I usually have boiler-plate code that looks something like this:

```objective-c
- (void)initializeMappings
{
    [databaseConnection readWithBlock:^(YapDatabaseReadTransaction *transaction) {

        if ([transaction ext:Ext_View_Order])
        {
            mappings = ...
            [mappings updateWithTransaction:transaction];
        }
        else
        {
            // The view isn't ready yet.
            // We'll try again when we get a databaseConnectionDidUpdate notification.
        }
    }];
}

- (void)databaseConnectionDidUpdate:(NSNotification *)notification
{
    if (mappings == nil)
    {
        [self initializeMappings];
        [self.tableView reloadData];

        return;
    }

    // boiler-plate update code ...
}
```

An alternative is what you mentioned. The asyncRegisterExtension method has a completionBlock. Which you could use to fire a notification/KVO from the databaseManager.

There is one gotcha to look out for. A possible crash actually.

If the extension isn't ready when you launch the app, then your UI will init with an empty tableView. But shortly thereafter, a YapDatabaseModifiedNotification will fire, and the datasource of the tableView will jump from zero to X ... with no row/section insertions. Obviously, this makes sense to us. But boiler-plate update code may cause the tableView to crash. That is, the code may run a beginUpdates / endUpdates, process zero changes, and then report a different sectionCount / rowCount.

What I'm getting at, is that you generally have to add some code to your UI to handle this situation within your databaseModified: method.

Also, keep in mind the order in which the notifications would fire:
1. YapDatabaseModifiedNotification
2. asyncRegisterExtension completionBlock

Let me know if you have any questions about any of this.

**Comment by chrisballinger** [comment]
Ah thank you! I'm only using mappings on some of the views (for instance, not on the R-Tree), so firing off notifications from the completion block is probably my best bet
