### ISSUE TITLE
Examples for relationships with files?

### ISSUE THREAD

**Issue by jasongrlicky** [yapstudios/YapDatabase#207]
Hi there! I've been using YapDatabase for an upcoming Mac app and have been absolutely loving it! That said, I've run into a snag creating a reference-counted relationship from an object. The creation method I chose is to make my model object conform to the `YapDatabaseRelationshipNode` protocol.

```objective-c
- (NSArray *)yapDatabaseRelationshipEdges
{
    YapDatabaseRelationshipEdge *previewImagePathEdge =
        [YapDatabaseRelationshipEdge edgeWithName:@"previewImage"
                              destinationFilePath:@"previewImagePath"
                                  nodeDeleteRules:YDB_DeleteDestinationIfAllSourcesDeleted];
    
    return @[previewImagePathEdge];
}
```
The model object also has a property for the preview image path string:

```objective-c
@property (nonatomic, copy) NSString *previewImagePath;
```

The problem I'm running into is that when I delete the model object in question, the file at the location "`previewImagePath`" isn't also deleted. I can't help but think that I'm misunderstanding the API. Normally I'd turn to sample code in this case, but I couldn't find any sample code in the documentation that deals with file references. Would someone mind giving me an example of how to use this feature? I'll look into how integrate it into the documentation once I understand the right way to use the API. Thank you so much!

**Comment by robbiehanson** [comment]
The destinationFilePath parameter should be something like: @"/path/to/file/preview.png"
What you're passing is the literal string of @"previewImagePath"

Assuming that self.previewImagePath is something like @"/path/to/file/preview.png", then you just need to change the code to this:

```objective-c
- (NSArray *)yapDatabaseRelationshipEdges
{
    YapDatabaseRelationshipEdge *previewImagePathEdge =
        [YapDatabaseRelationshipEdge edgeWithName:@"previewImage"
                              destinationFilePath:self.previewImagePath // <-- changed
                                  nodeDeleteRules:YDB_DeleteDestinationIfAllSourcesDeleted];

    return @[previewImagePathEdge];
}
```
