### ISSUE TITLE
YapDatabaseReadTransaction in YapDatabaseCloudKitRecordBlock

### ISSUE THREAD

**Issue by SofteqDG** [yapstudios/YapDatabase#210]
Hello

First, thanks for YapDB. It's really awesome!

I'm working on CloudKit synchronization. There are objects with many-to-many relationships in my database. I want to add `CKReferences` to `CKRecord`, but i can't do this because there is no `YapDatabaseReadTransaction` argument in `YapDatabaseCloudKitRecordBlock` and i can't enumerate edges. Can you please add an `YapDatabaseReadTransaction` argument in `YapDatabaseCloudKitRecordBlock`? It will be very useful.

Thanks!

PS: Sorry for my English :)

**Comment by robbiehanson** [comment]
Good idea! I added a YapDatabaseReadTransaction as the first parameter.

**Comment by robbiehanson** [comment]
Available in v2.7.2 (just pushed updated podspec)
