### ISSUE TITLE
YapDatabaseHooks causes bug in YapDatabaseFilteredView

### ISSUE THREAD

**Issue by tommylitang** [yapstudios/YapDatabase#216]
Scenario (In the order of extension registration):
-  View A for displaying O
-  Hooks H that updates P when O is inserted
-  Filtered view with parent F

Steps to reproduce the error:
-  Insert O
-  handleInsertObject action of A triggered
   -  lastHandledGroup of A set
-  handleInsertObject action of H triggered
   -  P updated
   -  handleUpdateObject action of A triggered
      - lastHandledGroup of A set to nil since it does't handle P
-  handleInsertObject action of F triggered
  - Ignoring O since parent A has nil lastHandledGroup <~ ERROR

Maybe the lastHandedGroup should be a stack instead of a single value, or flatten the handling of nested extension handlers.

**Comment by robbiehanson** [comment]
> Maybe the lastHandedGroup should be a stack instead of a single value

My thoughts exactly. In fact, there are a couple other places where a stack is needed. Such as the mutatedCollections ivar within YDBTransaction.

**Comment by tommylitang** [comment]
Is there any quick fix for this issue? I've changed the parent view group checking to using the groupForKey:inCollection instead of relying on lastHandledGroup. What do you think?

**Comment by robbiehanson** [comment]
Perhaps a quicker fix would be to change the order of your extension registration?

If you registered hooks AFTER the filtered view, that would temporarily fix the issue right? (Or is the filtered view something you register/unregister on the fly?)

**Comment by tommylitang** [comment]
Yes you're right. It is registered/unregistered on the fly.

**Comment by robbiehanson** [comment]
> I've changed the parent view group checking to using the groupForKey:inCollection instead of relying on lastHandledGroup. What do you think?

I think that would work just fine. In fact, if I remember correctly, the lastHandledGroup was simply an optimization to avoid the overhead of doing just that. However, that method does contain proper caching, so the overhead is likely very minimal for your use case.

**Comment by robbiehanson** [comment]
I decided to merge your fix into the repo. In order to retain the lastHandledGroup optimization, significant architecture changes would be required to support converting it to a stack. And these likely won't be implemented for several versions.
