### ISSUE TITLE
crash at "YapDatabaseTransaction.m, serializedObject = connection->database->objectSerializer(collection, key, object);" when using xcode7

### ISSUE THREAD

**Issue by xinwo** [yapstudios/YapDatabase#219]
I can NOT reopen
https://github.com/yapstudios/YapDatabase/issues/218
so that I create this new one

>It looks like the objectSerializer block is throwing an exception.
>If you're using the default serializer, then perhaps the object you're attempting to write to the database doesn't support NSCoding.
>This wiki article should help:
>https://github.com/yapstudios/YapDatabase/wiki/Storing-Objects

I'm using
YapDatabase.propertyListSerializer()
and, the object I pass to it is a String(json format)
Any idea why it crashes?

BTW:
XCode7
Swift2

EXC_BAD_ACCESS

connection
database
objectSerializer
all have value (not nil)

collection
key
object
are all strings (not nil, not empty)

**Comment by xinwo** [comment]
The error is
EXC_BAD_ACCESS

**Comment by robbiehanson** [comment]
Duplicate of issue #218
