### ISSUE TITLE
Dynamic sorting

### ISSUE THREAD

**Issue by sbooth** [yapstudios/YapDatabase#222]
I'm converting a Core Data project on Mac OS X to use YapDatabase and while I have most of the basic functionality working I've run in to a few conceptual roadblocks.  Currently I'm struggling with how to sort objects in a view for display in a table (`NSTableView`) based on the the table's `sortDescriptors`.  I've created a view in YapDatabase that contains all of the objects of the type I'd like to display in the table.  I can display them correctly in the table and they are sorted according to the view's sort block.  What is the appropriate way to sort the objects in a different manner?  Is the best solution to register a view on the fly where the sorting block handles sorting using the table's `sortDescriptors`?

**Comment by robbiehanson** [comment]
You can change the sorting of an existing view using [YapDatabaseViewTransaction setGrouping:sorting:versionTag:]. So the code would look something like this:

```objective-c
[readWriteConnection readWriteWithBlock:^(YapDatabaseReadWriteTransaction *transaction){
    [[transaction ext:@"MyView"] setGrouping:sameGrouping sorting:newSorting versionTag:diffVersionTag];
}];
```

Also, keep in mind that you have the option of creating persistent or non-persistent YDBViews. That is, storing the view results (grouping & sorting results) to the disk, or simply keeping them in memory. So if the view isn't very big, and you expect to be changing sortDescriptors often, you might consider non-persistent views.

Let me know if you have any questions.

**Comment by sbooth** [comment]
Thanks for clarifying things.  I wasn't sure if there was something akin to a filtered view except for sorting, because I figured it might be faster to re-sort an existing view (since grouping has already taken place) than to create a new one.  For my particular use case I think I'll just create a new view on the fly.

**Comment by robbiehanson** [comment]
One of the things on my todo list: [YapDatabaseViewTransaction setSorting:versionTag:]

Which would be a way to simply re-sort the existing set. (E.g. the grouping instance remains the same, sorting instance is swapped out, and only a re-sort operation occurs.)
