### ISSUE TITLE
Nullability annotation and generics

### ISSUE THREAD

**Issue by sbooth** [yapstudios/YapDatabase#225]
I believe it would improve the usability of YapDatabase from Swift to add nullability annotations and generic support.  One example of the type of change I'm referring to is in the `YapDatabaseRelationshipNode` protocol:

`- (NSArray *)yapDatabaseRelationshipEdges;`
becomes
 `- (nonnull NSArray<YapDatabaseRelationshipEdge *> *)yapDatabaseRelationshipEdges;`

This would let Swift code using relationships look like

```
func yapDatabaseRelationshipEdges() -> [YapDatabaseRelationshipEdge] {
	let artistEdge = YapDatabaseRelationshipEdge(name: "album_artist", destinationKey: artistUUID, collection: "artists", nodeDeleteRules: [.DeleteDestinationIfAllSourcesDeleted])
	return [artistEdge]
}
```
instead of
```
func yapDatabaseRelationshipEdges() -> [AnyObject] {
	let artistEdge = YapDatabaseRelationshipEdge(name: "album_artist", destinationKey: artistUUID, collection: "artists", nodeDeleteRules: [.DeleteDestinationIfAllSourcesDeleted])
	return [artistEdge]
}
```
I'd be happy to work on a pull request if there is any interest.

**Comment by sbooth** [comment]
Also, `__kindof` would be helpful.

`- (id)ext:(NSString *)extensionName; `
in `YapDatabaseConnection.h` would become
`- (__kindof YapDatabaseExtensionConnection *)ext:(NSString *)extensionName; `
after adding a forward declaration for `YapDatabaseExtensionConnection`

**Comment by chrisballinger** [comment]
<3 generics and nullability

**Comment by robbiehanson** [comment]
> I'd be happy to work on a pull request if there is any interest.

There is definitely interest ! I'd be happy to merge such a pull request.

One note though:
```objective-c
- (nonnull NSArray<YapDatabaseRelationshipEdge *> *)yapDatabaseRelationshipEdges;
```

This method does support returning nil if there are no relationship edges.

**Comment by sbooth** [comment]
> This method does support returning nil if there are no relationship edges

That's something I overlooked in my hasty quest for an example 😀.

I will start work on a pull request with this functionality.

**Comment by jj0b** [comment]
+1 for this. :-)

**Comment by sbooth** [comment]
See #228

**Comment by robbiehanson** [comment]
Pull request #228 has been merged.

**Comment by danthorpe** [comment]
@sbooth just seen all your changes in 2.7.4 - great stuff working on the nullability compatibility. Thanks so much!

As a side note, if you're looking for Swift generics support in YapDatabase take a look at [YapDatabaseExtensions](https://github.com/danthorpe/YapDatabaseExtensions).
