### ISSUE TITLE
dealing with asyncRegisterExtension in Swift

### ISSUE THREAD

**Issue by jj0b** [yapstudios/YapDatabase#226]
When registering view extensions asynchronously it is sometimes important to check if the extension is setup. In Objective-C you can check if an extension has already been setup with:

```if ([transaction ext:Ext_View_SomeView]) { ... }```

This isn't possible in Swift because `transaction.ext(Ext_View_SomeView)` returns 'AnyObject' which does not conform to the 'BooleanType' protocol. The compiler won't let you do a nil check on that. You similarly cannot do a nil check on that, as the binary operator '!=' cannot be applied to operands of type 'AnyObject' and 'NilLiteralConvertible'.

I've tried 

```if let _ = transaction.ext(Ext_View_SomeView) as? YapDatabaseView { ... }```

but though that will compile, this never unwraps the optional so whatever conditional code you have in the braces is never run.

Is there a recommended way to check if an extension is setup that will work in Swift?

**Comment by robbiehanson** [comment]
Possibly related to issue #225

**Comment by jj0b** [comment]
I opened a PR [#227](https://github.com/yapstudios/YapDatabase/pull/227) which makes extension and ext both nullable so that you can now check if an extension is setup in Swift.

**Comment by jj0b** [comment]
PR [#228](https://github.com/yapstudios/YapDatabase/pull/228) changed the ext method to be nullable, so that in Swift you can now do this to check if an extension has been initialized or not:

```if (transaction.ext(Ext_View_SomeView) != nil) { ... }```
