### ISSUE TITLE
Retrieving indexed values from a secondary index

### ISSUE THREAD

**Issue by sbooth** [yapstudios/YapDatabase#232]
I'm working on a music player that stores tracks in a library.  The tracks are related to a file on disk by their URL.  I've created a secondary index on the URL.  Each track should only be in the library once so I use the secondary index to aid in a find-or-create pattern when importing tracks.  Currently the code looks something like this:

```
connection.readWithBlock { (transaction: YapDatabaseReadTransaction) -> Void in
	let urlStrings = URLsToProcess.map {
		$0.absoluteString
	}

	let query = YapDatabaseQuery(string: "WHERE url IN (?)", parameters: [urlStrings])
	(transaction.ext("track_url_index") as! YapDatabaseSecondaryIndexTransaction).enumerateKeysAndObjectsMatchingQuery(query, usingBlock: { (collection: String!, key: String!, object: AnyObject!, stop: UnsafeMutablePointer<ObjCBool>) -> Void in
		if let track = object as? Track {
			existingURLs.append(track.url)
		}
	})
}
```

The code would be much more efficient if instead of retrieving individual track objects and extracting the URL from them (incurring a trip to the cache and possible deserialization overhead) it was possible to just retrieve the matching URL (the indexed property) directly from the secondary index.  I'm envisioning a query like:

`SELECT rowid, url FROM secondaryIndex_track_url_index WHERE url in (?)`

I browsed `YapDatabaseSecondaryIndexTransaction` and didn't see a way to accomplish this easily.  Do you have any suggestions?

**Comment by sbooth** [comment]
I came up with a workable solution at https://gist.github.com/sbooth/c2a295e7b6436d702e56

I'm not sure if this is something anyone else would be interested in.  If so, I'm happy to create  PR.

**Comment by robbiehanson** [comment]
> The code would be much more efficient if instead of [deserializing the objects] it was possible to just retrieve the matching [column]

Excellent point !

> I'm happy to create a PR

Please do. Also I have some ideas for improving upon this idea.
