### ISSUE TITLE
Docs/Wiki out of date for using Encryption

### ISSUE THREAD

**Issue by billburgess** [yapstudios/YapDatabase#237]
The documents and wiki still show examples for encrypting the database with options. Passphrase is no longer used and should be updated to reflect correct usage of options.cipherKeyBlock.

**Comment by robbiehanson** [comment]
Thanks for pointing this out. Wiki page has been updated:

https://github.com/yapstudios/YapDatabase/wiki/Encryption

**Comment by billburgess** [comment]
Thanks for taking care of it! I managed to figure out how to make it work without it, but should help anyone else in the future.
