### ISSUE TITLE
tvOS Support?

### ISSUE THREAD

**Issue by donholly** [yapstudios/YapDatabase#238]
```[!] The platform of the target (tvOS 9.0) is not compatible with `YapDatabase (2.7.4)`, which does not support `tvos`.```

Haven't dug into why yet - anything that will prevent us from Yap in tvOS apps in the short-term?

**Comment by robbiehanson** [comment]
It doesn't look there's any issues:
https://github.com/yapstudios/YapDatabase/commit/b5edcb84c03d2557c8375feab1ba7e54830a77be

**Comment by robbiehanson** [comment]
Pushing a new podspec for it now (v2.7.7).
