### ISSUE TITLE
The secondary index wiki page has code that does not compile

### ISSUE THREAD

**Issue by jsutwanttohelp** [yapstudios/YapDatabase#250]
On https://github.com/yapstudios/YapDatabase/wiki/Secondary-Indexes these types don't exist:
    YapDatabaseSecondaryIndexBlockType blockType = YapDatabaseSecondaryIndexBlockTypeWithObject;

and this function also doesn't exist:
YapDatabaseSecondaryIndex *secondaryIndex =
    [[YapDatabaseSecondaryIndex alloc] initWithSetup:setup block:block blockType:blockType];

Also the example doesn't contain any imports which means that I need to find or grep for the classnames to guess which file to include. That seems unhelpful.

**Comment by robbiehanson** [comment]
Fixed.
https://github.com/yapstudios/YapDatabase/wiki/Secondary-Indexes

Let me know if I missed anything else.

**Comment by jsutwanttohelp** [comment]
Looks good!
