### ISSUE TITLE
nil AnyObject returned from metadataForKey:inCollection

### ISSUE THREAD

**Issue by rgigger** [yapstudios/YapDatabase#253]
I am using swift. I have a object stored in the database for a certain key and I can retrieve it just fine. There is no metadata stored for this key/object.

But if I use metadataForKey:inCollection for that same object I get back an object of type AnyObject, not (`AnyObject?`). But it is a nil pointer. (debugger says: instance_type = (BuiltIn.RawPointer) 0x0. This is the code:

`let rawMeta = transaction.metadataForKey(key, inCollection: "my_collection_name)`

I have walked through the code for metadataForKey:inCollection and it is indeed returning a nil id pointer. But I can't unwrap it because it's not coming back as an optional. I can't even test it for nil. Am I doing something wrong here? Is this a bug in swift? When I try to get an object for a key that doesn't exist it gives me back an AnyObject? and I can test it for nil.

**Comment by rgigger** [comment]
This workaround works for me. Without the nullable it returned AnyObject! but with _Nullable it returns what it should be AnyObject?

I don't know why the objective-c swift conversion generates different types for different methods that all return id.

Are there any plans to add nullability markings to Yap? Would you accept a pull request with them in?

```
+ (id _Nullable)metadataForKey:(NSString *)key inCollection:(NSString *)collection usingTransaction:(YapDatabaseReadTransaction*)transaction
{
    id metadata = [transaction metadataForKey:key inCollection:collection];
    
    if(metadata)
        return metadata;
    
    return nil;
}

```

**Comment by rgigger** [comment]
Oh, also I guess I can just do this:

`let rawMeta: AnyObject? = transaction.metadataForKey(key, inCollection: "my_collection_name)`

So it's just the type inference that goes awry. Still it would be nice to have nullability info right in Yap

**Comment by robbiehanson** [comment]
Thanks for letting me know about the missing 'nullable' annotation. Fixed in master branch.
