### ISSUE TITLE
YapDatabase + SQLCipher hangs during initialization

### ISSUE THREAD

**Issue by jmnavarro** [yapstudios/YapDatabase#260]
Hey @robbiehanson !

We're trying use encryption with SQLCipher in [our project](https://github.com/liferay/liferay-screens) and we're getting stuck.

Just an empty project, with latest pods for YapDatabase (2.7.7) and YapDatabase/SQLCipher (3.3.1) with this basic code is enough to make it hang (a ready-to-reproduce project can be found [here](https://dl.dropboxusercontent.com/u/7640575/YapDatabase-SQLCipher-hang.zip))

```
NSString *path = ...

YapDatabaseOptions *opts = [[YapDatabaseOptions alloc] init];
opts.cipherKeyBlock = ^NSData * (void) {
	return [@"my-passphrase" dataUsingEncoding:NSUTF8StringEncoding];
};

YapDatabase *db = [[YapDatabase alloc] initWithPath:path serializer:nil deserializer:nil options:opts];
```
It hangs during the init, and it seems to be blocked by the master mutex in the `sqlite3_initialize` function.

Diving deeper and comparing against [other code](https://github.com/sqlcipher/SQLCipherSpeed) it seems `sqlite3_initialize()` isn't called during `sqlite3_open_v2()` (`sqlite3GlobalConfig.isInit` is always 0)

Also, I changed some code in few sqlite functions (just testing) and it isn't get executed, so my guess is the app is running two versions of sqlite: the built-in shipped with iOS and the one shipped with SQLite (and/or YapDatabase)

Is this possible? Any clue or sample project to use YapDatabase with SQLCipher?

Thanks for your project!

**Comment by robbiehanson** [comment]
Change Podfile from this:

```
pod 'YapDatabase'
pod 'YapDatabase/SQLCipher'
```

to just this:

```
pod 'YapDatabase/SQLCipher'
```

I tested this in the ready-to-reproduce project (PRU-OBJ), and it fixed the issue for me.

Let me know if you have any other questions.

**Comment by robbiehanson** [comment]
More info:

If you look the the [podspec](https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase.podspec), you'll see two subsections:
- standard
- SQLCipher

And this line:
```
s.default_subspec = 'standard' 
```

Which means that ```pod 'YapDatabase'``` really means ```pod 'YapDatabase/standard'```. AKA non-SQLCipher. So you were telling the  Podfile to install both the non-SQLCipher version & the SQLCipher version.

**Comment by jmnavarro** [comment]
Makes sense, and that's why I had two different sqlite instances running.

I'll contribute some kind of compile-time checking or better documentation
at least because the symptom is quite confusing.

Thanks!




---
Desde el móvil - From my phone
On 5 ene 2016, at 23:51, Robbie Hanson <notifications@github.com> wrote:

More info:

If you look the the podspec
<https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase.podspec>,
you'll see two subsections:

   - standard
   - SQLCipher

And this line:

s.default_subspec = 'standard'

Which means that pod 'YapDatabase' really means pod 'YapDatabase/standard'.
AKA non-SQLCipher. So you were telling the Podfile to install both the
non-SQLCipher version & the SQLCipher version.

—
Reply to this email directly or view it on GitHub
<https://github.com/yapstudios/YapDatabase/issues/260#issuecomment-169159670>
.

**Comment by robbiehanson** [comment]
> I'll contribute some kind of compile-time checking or better documentation
at least because the symptom is quite confusing.

Great idea. If you can find an improvement here I'll happily merge it.
