### ISSUE TITLE
Malicious SQL Query vulnerability in full-text search examples?

### ISSUE THREAD

**Issue by grgcombs** [yapstudios/YapDatabase#261]
I didn't see anything mentioned in the wiki related to information security when utilizing the full text search / filter functionality with user-provided input.

The search/filter examples I've seen all execute a YAP full text query from the user's search bar input -- with minimal sanitizing.  Is it plausible that a malicious attacker could use this pattern to their advantage, executing arbitrary SQL code?

Hopefully most people would have full-text search running from a read-only connection, but that wouldn't prevent SQL commands from making data changes, right? And with the right malicious query, wouldn't the user be able to access SQL tables other than the one we initially intended?

Any advice on mitigating this?

**Comment by robbiehanson** [comment]
This is prevented by using prepared statements, and then binding values to the parameters:

It works like this:
- first, you create a generic query string with question marks '?' where you want parameters to go (these parameters may come from a malicious user)
- then you [compile](https://www.sqlite.org/c3ref/prepare.html) the the query statement
- and finally you [bind](https://www.sqlite.org/c3ref/bind_blob.html) parameters to the compiled statement

When done this way, SQLite automatically handles properly escaping everything for you. So you don't have to worry about SQL injection attacks.
