### ISSUE TITLE
crash case about deletedRecordIDs in YDBCKChangeQueue.

### ISSUE THREAD

**Issue by ainopara** [yapstudios/YapDatabase#269]
![Image of Crash Info](https://i.v2ex.co/TT411Bnf.png)
Recently I have observed some crash about cloudkit extension. 
I searched about the exception info, get hint that [assigning a NSArray instance to a NSMutableArray property may cause the crash](http://stackoverflow.com/questions/16483294/crash-while-removing-objects-from-nsmutablearray).
Then I search the project with `deletedRecordIDs`, I found 2 lines use copy rather than mutableCopy to assign `deletedRecordIDs` to `deletedRecordIDs` in `YDBCKChangeQueue.m` file. 
I think this may be the source of that crash.

**Comment by robbiehanson** [comment]
Fixed via pull request #270
