### ISSUE TITLE
How to do string search

### ISSUE THREAD

**Issue by xiongcaixing1986** [yapstudios/YapDatabase#272]
Such as: SQL statement “select column_name from table_name where column_name like %abc%”

**Comment by robbiehanson** [comment]
You're likely looking for the [Full Text Search](https://github.com/yapstudios/YapDatabase/wiki/Full-Text-Search) extension.

If you want to do only precise searches (e.g. where field == "abc"), then the [Secondary Index](https://github.com/yapstudios/YapDatabase/wiki/Secondary-Indexes) extension would work.

**Comment by xiongcaixing1986** [comment]
Thanks
