### ISSUE TITLE
Can not get a valid YapDatabaseViewTransaction from LongLivedReadTransaction

### ISSUE THREAD

**Issue by robyzhou** [yapstudios/YapDatabase#275]
Hi,

It's confusion that I can not get a valid YapDatabaseViewTransaction from LongLivedReadTransaction, which I did not read from the wiki doc, could anybody help point it out for me?

Please take a look at my code bellow:

```
    ....
    //initialize YapDatabase
    {
    self.db = [[YapDatabase alloc] initWithPath:dbPath];

    self.readConnection = [self.db newConnection];
    [self.readConnection beginLongLivedReadTransaction];
    self.readConnection.objectCacheLimit = 1000;
    
    self.writeConnection = [self.db newConnection];
    self.writeConnection.objectCacheLimit = 1000;
    }

    //register YapDatabaseView
    {
        YapDatabaseViewGrouping* grouping = [YapDatabaseViewGrouping withObjectBlock:^NSString * _Nullable(YapDatabaseReadTransaction * _Nonnull transaction, NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object) {
            NSString* groupingName = nil;
            if ([object isKindOfClass:[Group class]]) {
                groupingName = GroupingName_Group;
            }
            
            return groupingName;
        }];
        
        YapDatabaseViewSorting* sorting = [YapDatabaseViewSorting withObjectBlock:^NSComparisonResult(YapDatabaseReadTransaction * _Nonnull transaction, NSString * _Nonnull group, NSString * _Nonnull collection1, NSString * _Nonnull key1, id  _Nonnull object1, NSString * _Nonnull collection2, NSString * _Nonnull key2, id  _Nonnull object2) {
            NSComparisonResult result = NSOrderedSame;
            if ([group isEqualToString:GroupingName_Group]) {
                Group* group1 = (Group*)object1;
                Group* group2 = (Group*)object2;
                if ([group1.lastmessagetime longLongValue] > [group2.lastmessagetime longLongValue]) {
                    result = NSOrderedDescending;
                }
            }
            
            return result;
        }];
        
        YapDatabaseView* view = [[YapDatabaseView alloc] initWithGrouping:grouping
                                                                  sorting:sorting
                                                               versionTag:YapDatabaseViewVersion];
        
        [delegate.db registerExtension:view withName:YapDatabaseViewName];
    }
    
    {
        //try to enumerate the objects from a common connection
        [delegate.writeConnection readWriteWithBlock:^(YapDatabaseReadWriteTransaction * _Nonnull transaction) {
            YapDatabaseViewTransaction* realTransaction = [transaction ext:YapDatabaseViewName];
            [realTransaction enumerateKeysAndObjectsInGroup:GroupingName_Group usingBlock:^(NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object, NSUInteger index, BOOL * _Nonnull stop) {
                if ([object isKindOfClass:[Group class]]) {
                    NSLog(@"");
                }
            }];
        }];
        
        //try to enumerate the objects from a LongLivedReadTransaction connection
        [delegate.readConnection readWithBlock:^(YapDatabaseReadTransaction * _Nonnull transaction) {
            YapDatabaseViewTransaction* realTransaction = [transaction ext:YapDatabaseViewName_Group];
            [realTransaction enumerateKeysAndObjectsInGroup:GroupingName_Group usingBlock:^(NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object, NSUInteger index, BOOL * _Nonnull stop) {
                if ([object isKindOfClass:[Group class]]) {
                    NSLog(@"");
                }
            }];
        }];
    }
```

As above code, I get a valid YapDatabaseViewTransaction from writeConnection, but a nil YapDatabaseViewTransaction from the readConnection.

I doubt maybe this is a issue from LongLivedReadTransaction connection, but I did not read that info from wiki, could anyone do me favor tell me the reason? I have already add a  notification on YapDatabaseModifiedNotification to call beginLongLivedReadTransaction on the readConnection.

Thanks a lot!

-roby

**Comment by SofteqDG** [comment]
Hello
Seems that you have a typo. You have registered view with **YapDatabaseViewName** name.
First time you are trying to get view transaction with **YapDatabaseViewName**. In this case everything works fine.
Second time you are trying to get view transaction with **YapDatabaseViewName_Group**. This is doesn't work because there is no view with this name.

**Comment by robyzhou** [comment]
@SofteqDG @robbiehanson I have checked my code, it's a typo here, but on my computer. Just because the name is too long, so I changed it to a short name when I post issue here. please take a look at the complete code bellow:

`    //YapDatabaseViewName_Group_LastMessageTimeDescending
    {
        YapDatabaseViewGrouping* grouping = [YapDatabaseViewGrouping withObjectBlock:^NSString * _Nullable(YapDatabaseReadTransaction * _Nonnull transaction, NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object) {
            NSString* groupingName = nil;
            if ([object isKindOfClass:[LuxyGroup class]]) {
                groupingName = GroupingName_Group;
            }
            
            return groupingName;
        }];
        
        YapDatabaseViewSorting* sorting = [YapDatabaseViewSorting withObjectBlock:^NSComparisonResult(YapDatabaseReadTransaction * _Nonnull transaction, NSString * _Nonnull group, NSString * _Nonnull collection1, NSString * _Nonnull key1, id  _Nonnull object1, NSString * _Nonnull collection2, NSString * _Nonnull key2, id  _Nonnull object2) {
            NSComparisonResult result = NSOrderedSame;
            if ([group isEqualToString:GroupingName_Group]) {
                LuxyGroup* group1 = (LuxyGroup*)object1;
                LuxyGroup* group2 = (LuxyGroup*)object2;
                if ([group1.lastmessagetime longLongValue] > [group2.lastmessagetime longLongValue]) {
                    result = NSOrderedDescending;
                }
            }
            
            return result;
        }];
        
        YapDatabaseView* view = [[YapDatabaseView alloc] initWithGrouping:grouping
                                                                  sorting:sorting
                                                               versionTag:YapDatabaseViewVersion_Group_LastMessageTimeDescending];
        
        [delegate.db registerExtension:view withName:YapDatabaseViewName_Group_LastMessageTimeDescending];
    }
    
    {
        //try to enumerate the objects from a common connection
        [delegate.writeConnection readWriteWithBlock:^(YapDatabaseReadWriteTransaction * _Nonnull transaction) {
            YapDatabaseViewTransaction* realTransaction = [transaction ext:YapDatabaseViewName_Group_LastMessageTimeDescending];
            [realTransaction enumerateKeysAndObjectsInGroup:GroupingName_Group usingBlock:^(NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object, NSUInteger index, BOOL * _Nonnull stop) {
                if ([object isKindOfClass:[LuxyGroup class]]) {
                    NSLog(@"");
                }
            }];
        }];
        
        //try to enumerate the objects from a LongLivedReadTransaction connection
        [delegate.readConnection readWithBlock:^(YapDatabaseReadTransaction * _Nonnull transaction) {
            YapDatabaseViewTransaction* realTransaction = [transaction ext:YapDatabaseViewName_Group_LastMessageTimeDescending];
            [realTransaction enumerateKeysAndObjectsInGroup:GroupingName_Group usingBlock:^(NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object, NSUInteger index, BOOL * _Nonnull stop) {
                if ([object isKindOfClass:[LuxyGroup class]]) {
                    NSLog(@"");
                }
            }];
        }];
    }`

I attached the screenshot to show the debug info, I got a nil transaction from LongLivedReadTransaction.

Please take a look.



![fbcf4214-bfe2-463b-a6a1-c42f952b2b12](https://cloud.githubusercontent.com/assets/6167223/12707177/6ee61e8e-c8cb-11e5-9fe4-0aad25872e7e.png)

**Comment by robbiehanson** [comment]
A ```registerExtension:::``` method is conceptually a readWriteTransaction. (In other words, you should think of it as a readWriteTransaction. And it basically is.) So you're essentially doing this:

```objective-c
[connection1 beginLongLivedReadTransaction]; // Freeze on commit #7

// Add commit #8
[connection2 readWriteWithBlock:^(YapDatabaseReadWriteTransaction *transaction){

    [transaction setObject:@"what?" forKey:@"foo" inCollection:@"bar"];
}];

// Still frozen on commit #7
[connection1 readWithBlock:^(YapDatabaseReadTransaction *transaction){

    NSString *what = [transaction objectForKey:@"foo" inCollection:@"bar"];
    // what is nil, see why ?
}];
```

Does that make sense ?
Let me know if you have other questions concerning extension registration.

FYI: When an extension is registered, it will post a YapDatabaseModifiedNotification to the main thread.

**Comment by robyzhou** [comment]
@robbiehanson Yes, that make sense to me. But I have already added a notification on YapDatabaseModifiedNotification after I create the LongLivedReadTransction on readConnection, and before I register the extension. In the handler of YapDatabaseModifiedNotification, I have called beginLongLivedReadTransaction on the readConnection.

I tried to change my code to use readWithBlock only, that will not toggle a commit on connection, and I still get nil transaction.

Code is pasted bellow:

```
    
    {
        //try to enumerate the objects from a common connection
        [delegate.writeConnection readWithBlock:^(YapDatabaseReadTransaction * _Nonnull transaction) {
            YapDatabaseViewTransaction* realTransaction = [transaction ext:YapDatabaseViewName_Group_LastMessageTimeDescending];
            [realTransaction enumerateKeysAndObjectsInGroup:GroupingName_Group usingBlock:^(NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object, NSUInteger index, BOOL * _Nonnull stop) {
                if ([object isKindOfClass:[LuxyGroup class]]) {
                    NSLog(@"");
                }
            }];
        }];
        
        //try to enumerate the objects from a LongLivedReadTransaction connection
        [delegate.readConnection readWithBlock:^(YapDatabaseReadTransaction * _Nonnull transaction) {
            YapDatabaseViewTransaction* realTransaction = [transaction ext:YapDatabaseViewName_Group_LastMessageTimeDescending];
            [realTransaction enumerateKeysAndObjectsInGroup:GroupingName_Group usingBlock:^(NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object, NSUInteger index, BOOL * _Nonnull stop) {
                if ([object isKindOfClass:[LuxyGroup class]]) {
                    NSLog(@"");
                }
            }];
        }];
    }
```

I just use readWithBlock on the writeConnection and readConnection, here readConnection is a LongLivedReadTransaction.

screenshot attached bellow:

![161881a2-f08f-43e2-a585-3d4bb2e0ca1d](https://cloud.githubusercontent.com/assets/6167223/12707535/6ba0b2de-c8d0-11e5-8814-59d77db5cefc.png)

**Comment by robyzhou** [comment]
@robbiehanson  I modified my code to get the snapshots and the transactions, the snapshot are the same, but transaction from readConnection is still nil.

Please take a look at my code:

```
   //initialize YapDatabase
    {
        self.db = [[YapDatabase alloc] initWithPath:dbPath];

        self.readConnection = [self.db newConnection];
        [self.readConnection beginLongLivedReadTransaction];
        self.readConnection.objectCacheLimit = 1000;

        self.writeConnection = [self.db newConnection];
        self.writeConnection.objectCacheLimit = 1000;
    }


    //YapDatabaseViewName_Group_LastMessageTimeDescending
    {
        YapDatabaseViewGrouping* grouping = [YapDatabaseViewGrouping withObjectBlock:^NSString * _Nullable(YapDatabaseReadTransaction * _Nonnull transaction, NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object) {
            NSString* groupingName = nil;
            if ([object isKindOfClass:[LuxyGroup class]]) {
                groupingName = GroupingName_Group;
            }
            
            return groupingName;
        }];
        
        YapDatabaseViewSorting* sorting = [YapDatabaseViewSorting withObjectBlock:^NSComparisonResult(YapDatabaseReadTransaction * _Nonnull transaction, NSString * _Nonnull group, NSString * _Nonnull collection1, NSString * _Nonnull key1, id  _Nonnull object1, NSString * _Nonnull collection2, NSString * _Nonnull key2, id  _Nonnull object2) {
            NSComparisonResult result = NSOrderedSame;
            if ([group isEqualToString:GroupingName_Group]) {
                LuxyGroup* group1 = (LuxyGroup*)object1;
                LuxyGroup* group2 = (LuxyGroup*)object2;
                if ([group1.lastmessagetime longLongValue] > [group2.lastmessagetime longLongValue]) {
                    result = NSOrderedDescending;
                }
            }
            
            return result;
        }];
        
        YapDatabaseView* view = [[YapDatabaseView alloc] initWithGrouping:grouping
                                                                  sorting:sorting
                                                               versionTag:YapDatabaseViewVersion_Group_LastMessageTimeDescending];
        
        [delegate.db registerExtension:view withName:YapDatabaseViewName_Group_LastMessageTimeDescending];
    }
    
    {
        //try to enumerate the objects from a common connection
        uint64_t writeConnectionSnapshot = delegate.writeConnection.snapshot;
        __block YapDatabaseViewTransaction* writeConnectionTransaction = nil;
        [delegate.writeConnection readWithBlock:^(YapDatabaseReadTransaction * _Nonnull transaction) {
            writeConnectionTransaction = [transaction ext:YapDatabaseViewName_Group_LastMessageTimeDescending];
            [writeConnectionTransaction enumerateKeysAndObjectsInGroup:GroupingName_Group usingBlock:^(NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object, NSUInteger index, BOOL * _Nonnull stop) {
                if ([object isKindOfClass:[LuxyGroup class]]) {
                    NSLog(@"");
                }
            }];
        }];
        
        //try to enumerate the objects from a LongLivedReadTransaction connection
        uint64_t readConnectionSnapshot = delegate.writeConnection.snapshot;
        __block YapDatabaseViewTransaction* readConnectionTransaction = nil;
        [delegate.readConnection readWithBlock:^(YapDatabaseReadTransaction * _Nonnull transaction) {
            readConnectionTransaction = [transaction ext:YapDatabaseViewName_Group_LastMessageTimeDescending];
            [readConnectionTransaction enumerateKeysAndObjectsInGroup:GroupingName_Group usingBlock:^(NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object, NSUInteger index, BOOL * _Nonnull stop) {
                if ([object isKindOfClass:[LuxyGroup class]]) {
                    NSLog(@"");
                }
            }];
        }];
        
        NSLog(@"");
    }
```

The attached screen shot show the debug info:
![cc4cae55-6850-41f1-8738-95e975452555](https://cloud.githubusercontent.com/assets/6167223/12712370/d77a9858-c902-11e5-84ef-085c417adaf3.png)

**Comment by robyzhou** [comment]
@robbiehanson I have debug the code carefully, I found that there is **0** pending change sets in write connection and **16** extensions registered in it, but there is **16** pending change sets in read connection and **0** extensions registered in it, here read connection is a **LongLivedReadTransaction**.

Please take a look at the screenshot bellow:

1. screenshot for write connection
![13f81c98-219b-49c6-a7fd-62b305267bc4](https://cloud.githubusercontent.com/assets/6167223/12712975/06aadb0c-c907-11e5-98d2-7f3b9e6535fa.png)

2. screenshot for read connection (LongLivedReadTransaction)
![75c92be4-ea80-4206-9507-4aa016eac4cf](https://cloud.githubusercontent.com/assets/6167223/12713022/34b12786-c907-11e5-9b3c-05fe9b852db6.png)


And I found that the `registerExtension:::` method post YapDatabaseModifiedNotification asynchronously, I call beginLongLivedReadTransaction for readConnection at there every time.

**I think this may be the answer, I MUST register extension before I create connections.**

I have tested it, and it works well! I think we should add this in the wiki pages, it's really confusion.

Thanks a lot!
-roby

**Comment by robbiehanson** [comment]
There's another typo:

```objective-c
uint64_t writeConnectionSnapshot = delegate.writeConnection.snapshot;
uint64_t readConnectionSnapshot = delegate.writeConnection.snapshot;
```

I think, after you fix this, you'll find the snapshots are not the same.

> And I found that the registerExtension::: method post YapDatabaseModifiedNotification asynchronously,

Yes, in fact all readWriteTransactions post YapDatabaseModifiedNotification asynchronously.

You may be interested in this FAQ question:
https://github.com/yapstudios/YapDatabase/wiki/Frequently-Asked-Questions#asyncRegisterExtension

**Comment by robyzhou** [comment]
Oh, no......typo again. I'm really really sorry.

Thank you robbie for your help!

In my project, it's not needed to register extension dynamically. Is it OK to create connection after register extension to resolve the issue, like above? So far, it works good. I just don't know is it a standard or recommended way. Hope your reply. Thanks a lot!

Best Regards,
-roby

**Comment by robbiehanson** [comment]
> Is it OK to create connection after register extension to resolve the issue, like above?

Yes, this is perfectly acceptable from a technical standpoint.

The only reason I pointed out the FAQ regarding async extension registration has to do with performance. I was worried that you'd notice a lag in the UI due to the synchronous write. (You very well may not, I have no idea.) And I didn't want you to feel that your solution was the only possibility. If it works in your case, then great. And if you ever run into issues with it, then we can revisit the async approach, and dive deeper into the YapDatabaseModifiedNotifcation, etc.

**Comment by robyzhou** [comment]
Thank you @robbiehanson for your patiently help!
