### ISSUE TITLE
Is it possible to query NSDate in SecondaryIndex?

### ISSUE THREAD

**Issue by robyzhou** [yapstudios/YapDatabase#276]
Hi,

I stored NSDate in database, like bellow:

```
@interface ITPerson : NSObject

@property (nonatomic, retain) NSNumber * id;
@property (nonatomic, retain) NSString * name;
@property (nonatomic, retain) NSString * gender;
@property (nonatomic, retain) NSNumber * age;
@property (nonatomic, retain) NSDate * date;
```

And I tried to create a SecondaryIndex like bellow:
```
YapDatabaseSecondaryIndexSetup* setup = [[YapDatabaseSecondaryIndexSetup alloc] init];
[setup addColumn:@"date" withType:YapDatabaseSecondaryIndexTypeText];
[setup addColumn:@"name" withType:YapDatabaseSecondaryIndexTypeText];
        
YapDatabaseSecondaryIndexHandler* handler = [YapDatabaseSecondaryIndexHandler withRowBlock:^(NSMutableDictionary * _Nonnull dict, NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object, id  _Nonnull metadata) {
    if ([object isKindOfClass:[ITPerson class]]) {
        ITPerson* person = (ITPerson*)object;
        dict[@"date"] = person.date;
        dict[@"name"] = person.name;
    }
}];
        
YapDatabaseSecondaryIndex* secondaryIndex = [[YapDatabaseSecondaryIndex alloc] initWithSetup:setup handler:handler versionTag:@"1"];

[self.db registerExtension:secondaryIndex withName:@"SecIndex"];
```

Then I try to query some item refer to date, like bellow:
```
- (void)yapDatabaseModified:(NSNotification *)notification
{
    NSArray *notifications = [longLovedConnection beginLongLivedReadTransaction];
    NSDate *date = [[NSDate date] dateAtStartOfDay];//the beginning of today
    
    [longLovedConnection readWithBlock:^(YapDatabaseReadTransaction * _Nonnull transaction) {
        if ([transaction ext:@"SecIndex"]) {
            YapDatabaseSecondaryIndexTransaction* realTransaction = [transaction ext:@"SecIndex"];
            YapDatabaseQuery* query = [YapDatabaseQuery queryWithFormat:@"WHERE date > ?", date];
            [realTransaction enumerateKeysAndObjectsMatchingQuery:query
                                                       usingBlock:^(NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object, BOOL * _Nonnull stop) {
                if ([object isKindOfClass:[ITPerson class]]) {
                    ITPerson* person = (ITPerson*)object;
                    NSLog(@"date:%@", person.date);
                    NSLog(@"");
                }
            }];
        }
    }];
}
```

Sadly, I didn't find any items even I know there are several items created today match the query condition.

My problem is, Is it possible to query NSDate in SecondaryIndex? If yes, which SecondaryIndexType should I use? YapDatabaseSecondaryIndexTypeText or something else? And, is there any example to create a YapDatabaseQuery refer to NSDate to enumerate the items?

Best Regards,
-roby

**Comment by sbooth** [comment]
Have you considered storing the dates as time intervals (doubles) using `-timeIntervalSinceReferenceDate`? I think this would make the comparisons simpler.

**Comment by robbiehanson** [comment]
Good question. As @sbooth said, the end goal is to store the dates in the secondary index as doubles.

So first you'll want to switch to ```YapDatabaseSecondaryIndexTypeReal```. Second, you can store the NSDate into the dictionary as you're doing now.

```objective-c
YapDatabaseSecondaryIndexHandler* handler = [YapDatabaseSecondaryIndexHandler withRowBlock:^(NSMutableDictionary * _Nonnull dict, NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object, id  _Nonnull metadata) {
    if ([object isKindOfClass:[ITPerson class]]) {
        ITPerson* person = (ITPerson*)object;
        dict[@"date"] = person.date;
        dict[@"name"] = person.name;
    }
}];
```

In other words, if ```dict[@"date"] == NSDate```, then the SecondaryIndex will automatically convert it a double using ```timeIntervalSinceReferenceDate```. This can be seen on line [516](https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase/Extensions/SecondaryIndex/YapDatabaseSecondaryIndexTransaction.m#L516).

In fact, while we're on this topic, your previous YapDatabaseSecondaryIndexHandler likely wasn't working. You were storing a NSDate into a column with ```type == Text```. So you should have run into this error on line [542](https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase/Extensions/SecondaryIndex/YapDatabaseSecondaryIndexTransaction.m#L542). 

After you make this change, I believe your query should start working. Note: If the extension (using type == text) is already loaded into your database, then be sure to change the ```versionTag```, so the extension knows to re-populate itself.

And, just to be thorough, your query should work as-is:
```objective-c
YapDatabaseQuery* query = [YapDatabaseQuery queryWithFormat:@"WHERE date > ?", date];
```

When YapDatabaseSecondaryIndex sees this query, it will automatically convert your NSDate parameter to a double via ```timeIntervalSinceReferenceDate```. This can be seen on line [1147](https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase/Extensions/SecondaryIndex/YapDatabaseSecondaryIndexTransaction.m#L1147).

**Comment by robyzhou** [comment]
@sbooth @robbiehanson Thank you all for your help!

@robbiehanson , I wanna know why you use timeIntervalSinceReferenceDate but timeIntervalSince1970?

**Comment by robbiehanson** [comment]
Well, I had to pick one of the two. So I suppose my decision was a bit arbitrary. I guess I went with ```timeIntervalSinceReferenceDate``` since that is how NSDate stores the double value internally.

**Comment by robyzhou** [comment]
Got it! Thanks a lot!

**Comment by accatyyc** [comment]
Just wanted to add that this helped me as well!

Was trying to query for items that hadn't been visited for a week and the problem was the same. This might be nice to add to the wiki!
