### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by accatyyc** [yapstudios/YapDatabase#278]
Hey, just want to start with saying that this is a really great project, and we've great experiences moving to Yap from CoreData.

However, it may be confusing for new users trying it out by copying examples from the wiki, since very many of them use the old ways of registering grouping/sorting blocks, instead of (what I assume are), the new classes specifically designed for this (`YapDatabaseViewGrouping`, `YapDatabaseViewSorting`) etc.

When copying and pasting some of the examples (for example, most of those found [here](https://github.com/yapstudios/YapDatabase/wiki/FilteredViews)), the old block methods will work, and the functions accepting the new classes will accept these blocks __without any warnings__. Instead, the application will crash after registering the view with an `EXC_BAD_ACCESS`.

In my opinion, it would be great if examples using the old blocks was completely removed from the docs/wiki, and replaced by examples using the classes instead. New users will get by with using the classes, and existing code bases can keep using the blocks. The classes are both safer and easier to use (and I admit it took me a while to figure out that the blocks were deprecated, if they are?).

**Comment by robbiehanson** [comment]
Yes, the block methods are deprecated. Actually, they were deprecated some time ago, and all block methods should have been removed from the project by now.

I've updated the docs for the page you referenced:
https://github.com/yapstudios/YapDatabase/wiki/FilteredViews

However, I wasn't able to reproduce this:

> the old block methods will work, and the functions accepting the new classes will accept these blocks without any warnings

When I tried copying the examples from the FilteredViews wiki, I got compiler errors. Could you provide an example? (Along with the version of YapDatabase you're using.)

**Comment by accatyyc** [comment]
Sure. The following code compiles for me and crashes later:

```objc
    YapDatabaseViewSortingBlock sortingBlock;
    sortingBlock = ^NSComparisonResult (YapDatabaseReadTransaction *transaction, NSString *group, NSString *collection1, NSString *key1, id obj1, id meta1,
                                        NSString *collection2, NSString *key2, id obj2, id meta2){
        return NSOrderedAscending;
    };

    return [[YapDatabaseView alloc] initWithGrouping:[self groupingByAllowingAll]
                                             sorting:sortingBlock
                                          versionTag:@"2"
                                             options:options];
```

I'm using YapDatabse 2.8.1 and Xcode 7.2.

Also, you are probably aware, but the page for standard views also use the block methods: https://github.com/yapstudios/YapDatabase/wiki/Views

**Comment by robbiehanson** [comment]
Pushed a commit that should fix the issue. It will still compile, but it will throw an assertion right away (when you invoke the init method with the improper parameter type).

Also fixed the wiki: https://github.com/yapstudios/YapDatabase/wiki/Views

**Comment by accatyyc** [comment]
Nice! Thanks for the quick responses/fixes! (On behalf of new users trying the examples that is :smile:)
