### ISSUE TITLE
Poor documentation on metadata

### ISSUE THREAD

**Issue by accatyyc** [yapstudios/YapDatabase#279]
Hey, me again, with more documentation remarks!

I think metadata is a really great part of YapDatabase, but it's only very briefly mentioned in the wiki. I believe users would benefit from a wiki-page on metadata, containing some examples on what it could be used for. It took me quite a while to figure out how to incorporate it in my apps (and I do wish I had figured it out _much_ earlier!)

Apart from examples, it would be great if it explained pros/cons with metadata related to performance etc, and what functions could be used. For example, filtering/sorting objects on metadata only and what performance impacts it may have.

**Comment by robbiehanson** [comment]
Added: https://github.com/yapstudios/YapDatabase/wiki/Metadata

**Comment by accatyyc** [comment]
Nice! Thanks :clap:
