### ISSUE TITLE
How can I use a custom deserializer clause per query?

### ISSUE THREAD

**Issue by jsutwanttohelp** [yapstudios/YapDatabase#280]
From reading the code it seems that there isn't a way to use a custom deserializer and/or a custom select clause on a per query basis but maybe I missed something.

Here is an example.
The collection is a collection of images with these columns:
```
NSString - key
int - updateTime
NSData - imageData
```
If I want to retrieve key and imageData the overhead of deserializing updateTime is insignificant (since sqlite is row based and all columns are stored in one blob).

However if I want to retrieve key and updateTime the overhead of deserializing imageData is significant.

If YapDb doesn't support this I imagine the reasons are that:
1) It would complicate the API.
2) The overhead of deserializing is not that signifant since the design of sqlite requires that the imageData be retrieved from disk for the row to be fully decoded and YapDb requires that all columns are stored in a single sqlite column.
3) This would complicate YapDb's row caching logic.
4) The use case is considered marginal.

I would appreciate any advice on how I could hack something that enables this. I am also curious as to whether you would be open to accepting it as a patch.

Alternatively perhaps I should just store the updateTime in a secondaryIndex and just support secondaryIndex queries where the contents of the secondary index sqlite row is returned instead of the main tables's sqlite row.

**Comment by skeeet** [comment]
@jsutwanttohelp i'm not a real welder, but you probably can move updateTime to metadata and avoid overhead of deserializing whole object for this small update.

**Comment by robbiehanson** [comment]
Good question. As @skeeet pointed out, one solution is to store your updateTime in the metadata column (instead of the object column). In fact, I recently added a wiki article that discusses the metadata system within YapDatabase in more detail.

https://github.com/yapstudios/YapDatabase/wiki/Metadata

But even before you read that, you may want to read the FAQ article titled [Should I store images in YapDatabase?](https://github.com/yapstudios/YapDatabase/wiki/Frequently-Asked-Questions#storing_images).

**Comment by jsutwanttohelp** [comment]
Thanks! I missed that metadata can be retrieved without the object. Perhaps `enumerateKeysAndMetadataMatchingQuery` should included be in that wiki page.

Regarding whether image storage is a good use case for YapDB - I only meant to use an example where one column is intuitively much larger than the other and not required for a retrieval cases.
