### ISSUE TITLE
How to make transient properties in YapDatabase?

### ISSUE THREAD

**Issue by mzeeshanid** [yapstudios/YapDatabase#281]
What to do if I don't want to persist some properties in my model.

For example if I save the row height of dynamic sized cell in my model. It may become invalid if i change the font size. So i think it is useless to save it in database.

**Comment by corristo** [comment]
Are you using NSCoding as a serialization mechanism? Then just don't persist this property in NSCoding implementation.

**Comment by robbiehanson** [comment]
Thanks @corristo

**Comment by mzeeshanid** [comment]
Ok I got it.
Thanks a lot.
Actually i was using [AutoCoding](https://github.com/nicklockwood/AutoCoding) for NSCoding stuff and eventually I forgot.
