### ISSUE TITLE
Grouping a database view on a non-model value

### ISSUE THREAD

**Issue by accatyyc** [yapstudios/YapDatabase#282]
This is not exactly an issue, but more a question on the recommended way to achieve the following:

For example, we have a `YapDatabaseView` that should contain all objects in `collection` with a specific sorting and grouping. The first group, called `recent_items` should contain all items that were created after a specific a date, say `one hour ago`. 

Now obviously, `one hour ago` is a dynamic value. Every time it changes, the grouping block needs to be run again to make sure only the recent items are in the first group.

`one hour ago` is also not stored in the database, so there's no automatic way for the view to actually know that the grouping should have been updated.

Currently, we have considered some ways ways of doing this:

## 1. Unregister/register the view
This forces the grouping to run again. It does however, force it to run on _all_ objects in the database not covered in the view whitelist. It works, but it doesn't feel efficient.

## 2. Touching all the objects in the collection
Another way is to enumerate all objects in the view (or the collection) and just touch them. This allows the view to pick up any potential objects that should have changed groups. It also doesn't feel perfect, since there is actually nothing changing in any of the objects (and still, thousands of objects may not need to be regrouped).

## 3. Register grouping/sorting with a new version
A third way would be to use ` (void)setGrouping:(YapDatabaseViewGrouping *)grouping sorting:(YapDatabaseViewSorting *)sorting versionTag:(nullable NSString *)versionTag` in `YapDatabseViewTransaction` to update the grouping/sorting. This would force it to sort again, but we feel that it's essentially the same thing as unregistering and re-registering the view.

Is there any recommended/better/easier/cleverer way to achieve this?

**Comment by robbiehanson** [comment]
Is your ```recent_items``` group sorted by date? In other words, is the oldest item in that group (next to fall out of the ```one hour ago``` list) easy to find (because it's naturally at the beginning/end or the list) ?

**Comment by accatyyc** [comment]
No, they are sorted by another score.

**Comment by robbiehanson** [comment]
Ah, well in that case I'd recommend taking a look at [YapDatabaseActionManager](https://github.com/yapstudios/YapDatabase/tree/experimental/action-manager/YapDatabase/Extensions/ActionManager)

I gave a good overview of how this class works over on issue #235 

The idea for your use case would be something like this:

When an object is within the one hour time window (creationDate+1hour > now), then it automatically creates a YapActionItem. And when the actionItem fires, all it has to do is touch its row within the database (which will cause the YapDatabaseView to re-analyze it). Should be doable with just a few lines of code.

Here's some pseudo-code :

```objective-c
/**
 * This goes into one of your model objects.
**/
- (NSArray<YapActionItem*> *)yapActionItems
{
    YapActionItem *actionItem = nil;

    NSDate *now = [NSDate date];
    NSDate *nonRecentDate = [self.creationDate dateByAddingTimeInterval:(60 * 60)];

    if ([nonRecentDate isAfter:now]) // @see "NSDate+YapDatabase.h"
    {
        YapActionItemBlock block = ^(NSString *collection, NSString *key, id object, id metadata){
            
            [AppDelegate.rwDatabaseConnection asyncReadWriteWithBlock:^{
                [transaction touchObjectForKey:key inCollection:collection];
                
                // If you wanted to get more fancy, you could touch only the view you want to update.
                // (if you use this fancy method, you can skip the global touch method above)
                [[transaction ext:TheViewThatNeedsToUpdate] touchObjectForKey:key inCollection:collection];
            });
        };

        actionItem = [[YapActionItem alloc] initWithIdentifier:@"touch"
                                                          date:nonRecentDate  // do it now
                                                  retryTimeout:0.0
                                              requiresInternet:NO
                                                         block:block];
        return @[ oneTimeAction ];
    }

    return nil;
}
```

**Comment by accatyyc** [comment]
Thanks! Will take a look at actions!

**Comment by robbiehanson** [comment]
Closing this issue, as I believe the ActionManager will solve the issue for you. But feel free to ask questions about it in issue #235.

Also, just a heads up, I've been working on several improvements to the ActionManager. So the way you register the extension may change a bit (converting it into a proper extension subclass), but the "yapActionItems" method signature will remain the same.
