### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by johnhi2015** [yapstudios/YapDatabase#285]
How can i use a tool like sqlite3 command to view the whole db file to do debugging?

**Comment by accatyyc** [comment]
This isn't related to YapDatabase. Yap will create a sqlite file on the path you tell it to create a database. Just print that path and view it like you normally would a sqlite database.

**Comment by robbiehanson** [comment]
There are also regular apps you can use to inspect sqlite databases. Here's one I really like:

https://menial.co.uk/base/
