### ISSUE TITLE
YapDatabaseHooks extension doesn't seem to be respecting the allowedCollections property when specified

### ISSUE THREAD

**Issue by aranasaurus** [yapstudios/YapDatabase#288]
I've registered the hooks extension and given it a whitelist but my `didModifyRow` is still being called on collections not in the whitelist. 

In looking over the other extensions that _do_ respect this property's setting I see that their Transaction implementation has to check this property, and it doesn't seem that `YapDataBaseHooksTransaction.m` has any reference to `allowedCollections` whatsoever.

**Comment by robbiehanson** [comment]
Good catch! I pushed a fix.

**Comment by aranasaurus** [comment]
ha! I was just adding tests and the fix myself. Thanks!
