### ISSUE TITLE
YapDatabaseRelationshipNode protocol's yapDatabaseRelationshipEdgeDeleted requires a return value?

### ISSUE THREAD

**Issue by aranasaurus** [yapstudios/YapDatabase#289]
From what I can tell looking at `YapDatabaseRelationshipTransaction` it seems like the return value should be `nullable` but it is not marked as such in the declaration which makes it so that the protocol notification portion of the protocol approach is essentially unusable from Swift :(

Though I may just be missing something as I can't find any documentation about what this method is supposed to be returning, but figured from looking at the transaction code that it allows you to replace the edge rather than delete it if needed. But if I actually want it to be deleted, from Swift I'm left without an option.

**Comment by robbiehanson** [comment]
Investigating this now...

**Comment by robbiehanson** [comment]
You're right, it should be nullable. And, equally important, the documentation for this method is poor. Working on a fix.

(The return value isn't for changing the edge, but rather the node (object) itself.)

**Comment by aranasaurus** [comment]
Great!

Since you're going to be working on docs: from my experience with it yesterday I thought I'd also point out https://github.com/yapstudios/YapDatabase/wiki/Relationships#parent_child_relationship_notify says 

> The "Notify" section will describe the notify method, how it works, and how to implement it.

But this section doesn't exist as far as I can tell. And there's no mention of the above method, as you've already seen. And the header doc for it ends abruptly as though part of it got lopped off at some point.

Thanks for looking into it!

**Comment by robbiehanson** [comment]
Fixed the wiki too: https://github.com/yapstudios/YapDatabase/wiki/Relationships#notify

**Comment by aranasaurus** [comment]
Yay! Thanks a bunch!
