### ISSUE TITLE
Minimum supported OS X version & CloudKit Dependency

### ISSUE THREAD

**Issue by jasongrlicky** [yapstudios/YapDatabase#292]
Hey there, I've been really loving using this framework in my apps!

I need to support OS X down to version 10.8 with the one I'm working on now. I thought I was in luck, since YapDB's .podspec shows it as being compatible with 10.8. Unfortunately, I just updated YapDatabase because I've been moving my projects over to Carthage, and found that it now seems to be linked against CloudKit (which was only included in 10.10).

I noticed that the deployment target in YapDB was bumped to 10.10, which would make sense for supporting CloudKit, but is potentially bad news for me. I would love to help out by making a pull request weak-linking CloudKit and conditionally compiling in stuff that uses it in order to maintain 10.8 compatibility. Is 10.8 compatibility still a goal for this project?

Thanks so much!

**Comment by robbiehanson** [comment]
> Is 10.8 compatibility still a goal for this project?

If possible, I'd like that.

As far as I understand, the "core" of the project, and most extensions, should still support 10.8 just fine. It's only certain ones (such as YDBCloudKit) that are going to cause issues.

I've commented about Carthage support in YapDatabase before:
https://github.com/yapstudios/YapDatabase/issues/192#issuecomment-169399442

I'll be the first to admit that I'm not a Carthage expert. But I have noticed that the "bells and whistles" in CocoaPods make it possible (even easy) to include only parts of a framework. In the case of YapDatabase, there is the "core" (which actually comes in 2 flavors: "Standard" & "SQLCipher"), and then there are all the various extensions. It should be possible to install only the core, and all the extensions should be optional. I've managed to accomplish this for CocoaPods, but I'm not sure how to do this for Carthage.

> I would love to help out by making a pull request weak-linking CloudKit and conditionally compiling in stuff that uses it in order to maintain 10.8 compatibility.

That's a good idea. If you create the pull request, I'll happily merge it.

**Comment by jasongrlicky** [comment]
Hey @robbiehanson, thanks for the swift response! I've made a pull request (#293), though I'm quite new at the whole open-source-collaboration thing, so hopefully everything's in order.

**Comment by robbiehanson** [comment]
Pull request #293 has been pulled into "v2.9" branch, and will part of the official 2.9 release.

**Comment by jasongrlicky** [comment]
Thank you @robbiehanson ! :+1:
