### ISSUE TITLE
Logging w/ NSLog fails

### ISSUE THREAD

**Issue by mickeyl** [yapstudios/YapDatabase#294]
It does not compile:

YapDatabase/YapDatabase/Extensions/FilteredViews/YapDatabaseFilteredViewConnection.m:100:2: Called object type 'NSString *' is not a function or function pointer

P.S. When using NSLog, where/how would I define the log level I'm interested in?

**Comment by robbiehanson** [comment]
Thanks for letting me know about this. It's fixed in the "v2.9" branch, which should be officially released soon.

**Comment by mickeyl** [comment]
Excellent, thanks!
