### ISSUE TITLE
Slow R-Tree Query

### ISSUE THREAD

**Issue by strongwillow** [yapstudios/YapDatabase#295]
Hello,

I have thousands of polylines in my database. Each line has a type property. Queries against one or many types should be carried out fast. Each polyline is saved in its respective collection.

Problem is that it's slow, even slower than simple Realm index. The worst query time is about 12 seconds and in Realm it's always under 3 seconds. Is there a way to improve it?

Following the docs, my r-tree initialisation is:

        let rtreeSetup = YapDatabaseRTreeIndexSetup()
        
        rtreeSetup.setColumns(["minLng", "maxLng", "minLat", "maxLat"])
        
        let handler = YapDatabaseRTreeIndexHandler.withObjectBlock({ (d: NSMutableDictionary!, collection: String!, key: String!, object: AnyObject!) -> Void in
            print("handler invoked")
            
            if let item = object as? Trace {
                d["minLng"] = item.minLng
                d["maxLng"] = item.maxLng
                d["minLat"] = item.minLat
                d["maxLat"] = item.maxLat

            }
        })
        
        let ext = YapDatabaseRTreeIndex(setup: rtreeSetup, handler: handler, versionTag: "1.0")
        yapDb.registerExtension(ext, withName: "rtree")

And the range query:

    func rangeQuery(maxlat: Double, maxlng: Double, minlat: Double, minlng: Double, types: [Int]) -> [Trace] {

        var start = NSDate()
        
        var list = [maxlat, maxlng, minlat, minlng]
        let queryString = "WHERE maxLat <= ? AND maxLng <= ? AND minLat >= ? AND minLng >= ?"
        let query = YapDatabaseQuery(string: queryString, parameters: list)
        var ret = [Trace]()
        
        conn!.readWithBlock { (trans) -> Void in
            
            if let index = trans.ext("rtree") as? YapDatabaseRTreeIndexTransaction {
                let enumerateBlock: (String!, String!, AnyObject!, UnsafeMutablePointer<ObjCBool>) -> Void = {
                    (collection: String!, key: String!, object: AnyObject!, stop: UnsafeMutablePointer<ObjCBool>) in
                    
                    if let item = object as? Trace {
                        
                        if (types.indexOf(item.type) > -1) {
                            ret.append(item)
                        }
                    }
                }
                
                index.enumerateKeysAndObjectsMatchingQuery(query, usingBlock: enumerateBlock)
            }
        }
        
        
        print("search duration: ")
        print(NSDate().timeIntervalSinceDate(start))
        
        return ret
    }

**Comment by strongwillow** [comment]
Problem solved. It's because `enumerateKeysAndObjectsMatchingQuery` is too slow for objects creation. `enumerateKeysMatchingQuery` will solve all the problem.

**Comment by strongwillow** [comment]
I found a lead. `enumerateKeysAndObjectsMatchingQuery` is the expensive part here. Using `enumerateKeysMatchingQuery` is quite fast. 

`Trace` class contains several heavy coordinate lists. But only one of these lists is needed. So it comes down to this question: "Is is possible to selectively deserialise properties of an object?"

**Comment by sbooth** [comment]
Rather than doing that could you alter the design of `Trace` and extract out the coordinate lists to separate objects and retrieve them that way? Partial deserialization sounds like something that could easily leave objects in an undetermined state.

**Comment by strongwillow** [comment]
Thank you @sbooth . I separated the coordinate lists into different collections and things are better. But the result is not much better than Realm. 

Index is not the major problem here. I/O and serialisation is.

**Comment by robbiehanson** [comment]
@sbooth

Looking at the SQLite [documentation for R*Tree](https://www.sqlite.org/rtree.html), section 4: "Using R*Trees Effectively":

> Key Point: An R*Tree index does not normally provide the exact answer but merely reduces the set of potential answers from millions to [a lot less].

This makes me think that many people are going to end up with the same experience. They'll find that, while the R*Tree itself is incredibly fast, their particular query (as a whole) may be slow because they're trying to deserialize every possible object. And then they'll throw the baby out with the bathwater.

It may be ideal for us to figure out a way to combine an R*Tree query with a secondary index. In this example, he could easily setup a secondary index on 'Trace.type'. Then combining the R*Tree query and the secondary index into a single SQLite query under-the-hood would yield an optimal query.

The question for us is: "How can we improve the API to make this easy/possible to do?"

**Comment by sbooth** [comment]
@robbiehanson I definitely think it's reasonable to expect that combining the RTree query with a secondary index would yield performance improvements.  I also think you've hit the nail on the head with your question.  

I opened #297 to keep track since this issue is already closed.

**Comment by robbiehanson** [comment]
Good idea. Thanks!

**Comment by mickeyl** [comment]
> I found a lead. `enumerateKeysAndObjectsMatchingQuery` is the expensive part here. Using `enumerateKeysMatchingQuery` is quite fast.
> 
> `Trace` class contains several heavy coordinate lists. But only one of these lists is needed. So it comes down to this question: "Is is possible to selectively deserialise properties of an object?"

Can‘t you use the metadata for those properties?
