### ISSUE TITLE
Has anyone tried using YapDatabase on Linux or Windows?

### ISSUE THREAD

**Issue by jsutwanttohelp** [yapstudios/YapDatabase#296]
If not, do you have any advice on where the complexity would be in porting to either?

I've had good experience with Clang/LLVM and sqlite on both.

Thank you

**Comment by chrisballinger** [comment]
I think GNUstep might be too old for some of the Foundation related stuff, and you'd need a port of libdispatch

**Comment by jsutwanttohelp** [comment]
Thank you
