### ISSUE TITLE
v2.9 won't compile if included in another pod via cocoapods 0.39.0

### ISSUE THREAD

**Issue by pwerry** [yapstudios/YapDatabase#308]
Complains about the `<Reachability/Reachability.h>` import being a non-modular header - haven't come up with a workaround just yet aside from removing/excluding the `YapDatabaseActionManager` subspec

Fairly easy to reproduce:

1. Create a local development pod with a swift file that imports YapDatabase
2. Create a project with Podfile that includes development pod and YapDatabase v2.9 as dependencies

**Comment by pwerry** [comment]
Ignore - this is a pods configuration and compilation order issue. If your development pod has a dependency on a branch, you can just create a private repo and list the YapDatabase branch spec there.

**Comment by davidchiles** [comment]
I had this issue too with v2.9 when trying to use it in [YapTaskQueue](https://github.com/davidchiles/YapTaskQueue) for now I'll continue to use v2.8.x

In my podspec:
`s.dependency 'YapDatabase', '~> 2.9'` 

From: `pod spec lint YapTaskQueue.podspec --verbose`

```
 -> YapTaskQueue (0.1)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  <module-includes>:72:9: note: in file included from <module-includes>:72:
    - ERROR | xcodebuild:  YapDatabase/YapDatabase/Extensions/ActionManager/YapDatabaseActionManager.h:9:9: error: include of non-modular header inside framework module 'YapDatabase.YapDatabaseActionManager'
    - ERROR | xcodebuild:  YapTaskQueue/YapTaskQueue/Classes/YapTaskQueueBroker.swift:10:8: error: could not build Objective-C module 'YapDatabase'
```

@pwerry Could you reopen the issue?

**Comment by chrisballinger** [comment]
I've created a test podspec that depends on Reachability and imports it in the same exact way as the action manager. That compiles and works fine, so it is probably something funky about the Yap podpec or modulemap.

I haven't tried making a custom modulemap for this test project, but I suspect that there may be something there.

**Comment by chrisballinger** [comment]
Here's the result of my experimentation so far, now with a similar modulemap and subspecs: https://github.com/chrisballinger/ReachDepTest

Still can't reproduce..

**Comment by robbiehanson** [comment]
Is the issue specifically related to Swift projects ?

**Comment by chrisballinger** [comment]
Ohh perhaps, I didn't try with Swift but I am using framework modules which I figured would act the same. 

@davidchiles Also puzzling is that this might only be happening during the pod lint stage?

**Comment by chrisballinger** [comment]
Ok I finally reproduced it. Apparently this breaks for some reason:

* Main target -> Pod with Swift -> Reachability
* However... Main target with Swift -> Pod -> Reachability works fine

I wouldn't be surprised if you added a single Swift file to Yap it would break in a similar way. Strange that using with Obj-C with framework modules doesn't cause it to complain at all.
