### ISSUE TITLE
Corresponding objects sometimes missing when using allKeysInCollection

### ISSUE THREAD

**Issue by chrisballinger** [yapstudios/YapDatabase#310]
When using allKeysInCollection: and objectForKey:inCollection: together in the same transaction, occasionally we get nil returned for one of the keys present in the collection.

```obj-c
+ (NSArray *)allAccountsWithTransaction:(YapDatabaseReadTransaction*)transaction
{
    NSMutableArray *accounts = [NSMutableArray array];
    NSArray *allAccountKeys = [transaction allKeysInCollection:[OTRAccount collection]];
    [allAccountKeys enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
        [accounts addObject:[[transaction objectForKey:obj inCollection:[OTRAccount collection]]copy]];
    }];
    
    return accounts;
    
}
```

Obviously we should be checking for nil before inserting into the array but it seems curious that there would be a mismatch between the keys returned and what's actually present.

**Comment by robbiehanson** [comment]
Hmm... That's concerning.

Have you been able to catch this in the debugger ever? I'm wondering which path the code took within the ```objectForKey:inCollection:``` method.

**Comment by robbiehanson** [comment]
Btw - what version of YapDatabase ?

**Comment by chrisballinger** [comment]
2.8.3

I only noticed it through a crash report and haven't ever seen it locally. It seems to be very rare, only 5/481 crashes so far since our last release. All of the crashes seem to be happening on the same guy's iPhone 6S running 9.3.1, so I'm wondering if it's a rare db corruption issue. We are also running SQLCipher with db keys stored in the keychain protected until first unlock, but it probably would have never progressed to that step if the db failed to init.

**Comment by robbiehanson** [comment]
> All of the crashes seem to be happening on the same guy's iPhone 6S running 9.3.1, so I'm wondering if it's a rare db corruption issue.

I suppose that's possible...

The [How To Corrupt An SQLite Database File](https://www.sqlite.org/howtocorrupt.html) page lists "Memory corruption" as a potential culprit. And a memory corruption bug was discovered recently (issue #307). It's patched in the recently released v2.9.

So theoretically, if this was the culprit, it could have corrupted a page in the database that contained that account (the serialized object). And then the page was written to disk.

So it would be nice to get you to v2.9. But you may currently be blocked in doing so: issue #308 (Got any ideas on this one?)

**Comment by chrisballinger** [comment]
Good call on moving to v2.9. Moving discussion to #308

**Comment by chrisballinger** [comment]
We moved to 2.9 and I also added a nil check, so we'll probably never see a report for this again. :)
