### ISSUE TITLE
Nested Transactions

### ISSUE THREAD

**Issue by paulcarpenter** [yapstudios/YapDatabase#311]
Hi everybody. I'm currently considering migrating from my app's existing storage solution (Core Data with MagicalRecord) to something a little bit less finicky when it comes to threading and relationship management. I've been exploring how Yap can help me with this, and it seems like a great solution.

However, what does frustrate me a bit about Yap's architecture is that it doesn't allow for nested transactions. I understand the logic behind this (encouraging minimal activity beyond fetching/writing on the database queue, avoiding dealing with complicated queuing questions on the internal implementation) and by and large I agree with it. However, my current app (for better or worse) has a lot of code that's using what would become nested transactions on Yap.

For example, I want to fetch a List object, and then use a list of keys contained in that List to fetch its List Entries. Then I want to display a string with the List's name, its description, and its List Entries. There are three solutions I see here:
– Explicitly fetch both the List and its List Entries in one transaction block.
– Write a convenience method on List to fetch its List Entries. Call this method outside of the transaction block that finds the List in the first place.
– Write a convenience method on List that takes an optional transaction parameter. This method will be responsible for creating its own transaction or using the existing one.

None of these seem ideal to me – they all create code clutter in different ways, they all require me to be conscious of the underlying data store structure even in view controllers or view models, and they all require significant rewriting (or at least close and in-depth examination) of the significant amount of code I already have.

Instead, I looked into YapDatabaseConnection to see if I couldn't patch readWithBlock: and readWriteWithBlock: to allow for nested transactions. The fruit of my labors is here: https://github.com/paulcarpenter/NestedYap/commit/30f4f0c24c1e04be8d2bd364a7449c25a6da6821 (apologies for the awful indentation). I didn't change much, and my own tests seem to be working fine. I know that the patch I laid out here accepts that any given transaction might not be working with the latest possible data set, and it also gives me the opportunity to stupidly put a lot of disproportionate computation on the database queues. I recognize these problems and would plan to work away from them in the future.

For my immediate goal of migrating towards Yap, does anybody see why these changes would cause crashes or problems with the database's integrity?

Thanks in advance for any responses!

**Comment by robbiehanson** [comment]
I think what you're looking for already exists in YapDatabase (no patches necessary).

To summarize my understanding of the issue:
- you have scattered code that reads various objects from the database
- it would be very inconvenient (or impossible) to re-write the code to read everything in a single block
- the majority of this is reading objects for display in the user interface
- it's important that the scattered code reading from the database sees the exact same commit

If I've understood this correctly, you're in luck. The feature you're looking for is called a "longLivedReadTransaction". It's an advanced version of your "activeNestedReadTransaction".

These wiki articles should help:
- [LongLivedReadTransactions](https://github.com/yapstudios/YapDatabase/wiki/LongLivedReadTransactions)
- [YapDatabaseModifiedNotification](https://github.com/yapstudios/YapDatabase/wiki/YapDatabaseModifiedNotification)

**Comment by paulcarpenter** [comment]
Hi Robbie, thanks for you response! You've got a pretty good handle on the situation, and I did do extensive reading on the LongLivedReadTransactions. My problem really has to do with nested calls, though. From what I understand, even using a connection's longLivedReadTransaction doesn't allow me to call nested transaction blocks.

From what I can tell, though, longLivedReadTransactions don't help me in the following case:

`[databaseConnection beginLongLivedReadTransaction];

[databaseConnection readWithBlock:^(YapDatabaseReadTransaction *transaction) {
    MyClass *myObject = [transaction objectForKey@"myKey" inCollection:@"myCollection"];

    [myObject thisMethodTriesToReadWithBlockAndCreatesADeadlock];
}];`

This is what my own patch is designed to allow me to do without deadlocking. This is in order to avoid cluttering my code by changing hundreds of methods to accept optional transaction arguments (as the example given in the docs for dealing with deadlocking), and to make my higher-level code relatively unaware structure-wise of what the underlying storage engine is.

If I can actually write code like the above example and NOT deadlock with longLivedReadTransactions, please let me know and I'll go and bang my head against the documentation more.

Thanks a lot!

**Comment by robbiehanson** [comment]
Ah, gotcha. In that case:

```objective-c
static YapDatabaseReadTransaction *activeNestedReadTransaction;
static YapDatabaseReadWriteTransaction *activeNestedReadWriteTransaction;
```

These cannot be static. They must be on a per-connection basis. Move them into here (a few lines below where they are declared now):

```objective-c
@implementation YapDatabaseConnection {
@private

    YapDatabaseReadTransaction *activeNestedReadTransaction;
    YapDatabaseReadWriteTransaction *activeNestedReadWriteTransaction;
}
```

**Comment by paulcarpenter** [comment]
Ah, makes total sense. Thanks for taking the time to look this over!
