### ISSUE TITLE
CocoaLumberjack

### ISSUE THREAD

**Issue by calebd** [yapstudios/YapDatabase#312]
It would be great if YapDatabase did not force me to include CocoaLumberjack. It may be useful for the project itself but I do not wish to include it in my applications.

**Comment by chrisballinger** [comment]
https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase/Internal/YapDatabaseLogging.h#L69

**Comment by calebd** [comment]
> You are strongly discouraged from modifying this file. If you do, you make it more difficult on yourself to merge future bug fixes and improvements from the project. Instead, you should override the default values in your own application.

How are we expected to make that change? Maintain a fork that changes that value?

It would be far better if the framework provided a way to inject a logger ([like this](https://github.com/0xced/XCDYouTubeKit/blob/master/XCDYouTubeKit/XCDYouTubeLogger.h)) that could be easily configured.

**Comment by chrisballinger** [comment]
Add `-DYapDatabaseLoggingTechnique=YapDatabaseLoggingTechnique_Disabled` to your CFLAGS

**Comment by chrisballinger** [comment]
Here's a tip how to add that if you're using CocoaPods: https://guides.cocoapods.org/syntax/podfile.html#post_install

**Comment by calebd** [comment]
I'm not using CocoaPods.

**Comment by chrisballinger** [comment]
Carthage? There should be a way to modify the build settings, right? Or if integrated into your project directly that should be very simple.

**Comment by calebd** [comment]
Yes Carthage. It downloads the project from the remote and compiles the framework target. In order to change anything in the project I need to have a fork with the desired modifications (The same would be true of other package managers like Swift PM). Again, that is not a scalable solution to this problem. Relying on the fact that CocoaPods allows you to inject whatever you want into the build process is not good library design.

**Comment by JamieWhite** [comment]
To add to this the whole logging situation isn't great. Relying on a load of defines is bad design. Could we add improving this to a future milestone?

**Comment by accatyyc** [comment]
@JamieWhite Not sure defines are a problem really. Relying on defines in general may be bad practice, but logging is one of the cases where they really shine. This is because the logging statements won't even be compiled as part of the binary if not needed, depending on the logging level.

**Comment by simme** [comment]
I agree with @calebd on this one. Making logging an injection option would be much better. Dependencies with dependencies are a pain, especially now with the Swift 3 transition.

Define a protocol for logging and make it possible to provide logging objects conforming to this protocol.

**Comment by chrisballinger** [comment]
@simme Why are deps with deps a problem with Swift 3? Is it an issue with SPM?

**Comment by calebd** [comment]
SPM will have the same problem as Carthage. If the only way to remove the logging dependency is to modify the source, you will have to fork this repo, modify the code, and point to that instead of the canonical version.

**Comment by chrisballinger** [comment]
Is it really impossible to modify CFLAGS for Carthage or SPM? Not that I'm against the idea of an injectable solution, but plenty of libraries have ifdefs and sub dependencies for valid reasons.

**Comment by JamieWhite** [comment]
For Carthage it's definitely impossible.

**Comment by calebd** [comment]
The only way to do it would be to use command line arguments at build time to change build settings for the entire compile process.

**Comment by simme** [comment]
@chrisballinger because, in this case, CocoaLumberjack has a swift file that is not updated for Swift 3. Hence YapDatabase currently does not build with Carthage and Xcode 8.

For now I've written a tiny script that uses `sed` to just remove the CocoaLumberjack dependency from the Carthage file and change the logging constant in YapDatabase. :P
