### ISSUE TITLE
Wiki: Mention ability to change view grouping/sorting without reregistering

### ISSUE THREAD

**Issue by nolanw** [yapstudios/YapDatabase#313]
The [views article](https://github.com/yapstudios/YapDatabase/wiki/Views) has no mention of `-[YapDatabaseViewTransaction setGrouping:sorting:versionTag:]`. I managed to miss that very handy method the first dozen times I read through the headers. I ended up using some YapDatabaseFilteredViews just to avoid the unregister/reregister cycle, because I thought that was the only way to update grouping/sorting blocks. Entirely my fault, I'm not blaming anyone else! But it'd probably save the next person some time to mention that method's existence in that wiki article.

**Comment by mickeyl** [comment]
It's a Wiki, anyone can edit it. Did that now with https://github.com/yapstudios/YapDatabase/wiki/Views/7b12d54cabbc565168de40a1b7a4c550a04fed0e

**Comment by nolanw** [comment]
Oh right! Not sure how that slipped my mind. Thanks!
