### ISSUE TITLE
File relation

### ISSUE THREAD

**Issue by ERussel** [yapstudios/YapDatabase#314]
I want to create object to file relation, but after looking to the edge initialization method:

```
+ (instancetype)edgeWithName:(NSString *)name
          destinationFileURL:(NSURL *)destinationFileURL
             nodeDeleteRules:(YDB_NodeDeleteRules)rules;
```

i imagined the following case: in v1 of my application i insert object and create relation to file by providing destination file url, but after my application will be updated to version v2 absolute file path not guaranteed to be the same as in v1. Is this situation handled somehow by YapDatabase?

**Comment by robbiehanson** [comment]
>  Is this situation handled somehow by YapDatabase?

Yup. From [YapDatabaseRelationshipOptions.h](https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase/Extensions/Relationships/YapDatabaseRelationshipOptions.h#L148):

```objective-c
/**
 * Apple recommends persisting file locations using bookmarks.
 * 
 * From their documentation on the topic: https://goo.gl/0Uqn5J
 *
 *   If you want to save the location of a file persistently, use the bookmark capabilities of NSURL.
 *   A bookmark is an opaque data structure, enclosed in an NSData object, that describes the location of a file.
 *   Whereas path and file reference URLs are potentially fragile between launches of your app,
 *   a bookmark can usually be used to re-create a URL to a file even in cases where the file was moved or renamed.
 * 
 * The default serializer will attempt to use the bookmark capabilities of NSURL.
 * If this fails because the file doesn't exist, the serializer will fallback to a hybrid binary plist system.
 * It will look for a parent directory that does exist, generate a bookmark of that,
 * and store the remainder as a relative path.
 *
 * You can use your own serializer/deserializer if you need extra features.
**/
+ (YapDatabaseRelationshipFileURLSerializer)defaultFileURLSerializer;
+ (YapDatabaseRelationshipFileURLDeserializer)defaultFileURLDeserializer;
```

You can take a look at the implementation [here](https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase/Extensions/Relationships/YapDatabaseRelationshipOptions.m?ts=4#L95).
