### ISSUE TITLE
YapDatabaseRelationshipTransaction.sourceNodeForEdge should return nullable type

### ISSUE THREAD

**Issue by programmarchy** [yapstudios/YapDatabase#318]
In YapDatabaseRelationship.h:

`public func sourceNodeForEdge(edge: YapDatabaseRelationshipEdge) -> AnyObject`
`public func destinationNodeForEdge(edge: YapDatabaseRelationshipEdge) -> AnyObject`

Should instead return `AnyObject?` to be Swift compatible.

**Comment by robbiehanson** [comment]
Yup, good catch. Thanks.
