### ISSUE TITLE
Please create a new cocoapods version, since the current one is broken in XCode 7.3.1

### ISSUE THREAD

**Issue by barteljan** [yapstudios/YapDatabase#319]
You just have to fix the Reachability import in YapDatabaseActionManager.h 
(which was already done in MergeRequest #315)

Thank you :-)

**Comment by robbiehanson** [comment]
Thanks for reminding me!  ``` pod trunk push ``` is in progress...

**Comment by robbiehanson** [comment]
[Done](https://cocoapods.org/pods/YapDatabase)

**Comment by barteljan** [comment]
Thank you 👍
