### ISSUE TITLE
why yap is doing deserialization all objects stored in database?

### ISSUE THREAD

**Issue by linlinyao1** [yapstudios/YapDatabase#320]
I am using view extension to display objects, and when I register extension all 10 thousands objects stored in database are deserialized with mantle, and cpu usage goes to 100%

Is there a way to only deserialize some of them?

**Comment by robbiehanson** [comment]
I believe this [FAQ](https://github.com/yapstudios/YapDatabase/wiki/Frequently-Asked-Questions#registering_view) should help. It addresses several related concerns.

Let me know if you have any other questions.
