### ISSUE TITLE
Bookkeeping error in filtered views

### ISSUE THREAD

**Issue by heiberg** [yapstudios/YapDatabase#327]
I'm seeing a case where a filtered view is not showing the expected items after a write transaction.

The simplest reproduction I have is as follows:
## Setup
- Create a view which has a criteria for including objects in the grouping. Let's say that `object.isValid` must be `true`.
- Create a filtered view with this view as the parent. The filter block just includes everything from the parent view.
- Create a database object with `isValid = true` so that it is included in both views.

Now we would expect the two views to always include the same objects.
## Trigger error
- Open a read/write transaction on a connection.
- Change `isValid` to `false` on the single database object. Write the object.
- Both views would be empty if we committed the transaction now.
- Change `isValid` to `true` on the single database object. Write the object.
- End the transaction.

Now the regular view will include the modified object. But the filtered view will be empty.

The resulting `YapDatabaseModifiedNotification` looks like this:

```
NSConcreteNotification 0x7f81d14c8740 {name = YapDatabaseModifiedNotification; object = <YapDatabase: 0x7f81d143e500>; userInfo = {
    connection = "<YapDatabaseConnection: 0x7f81d145a590>";
    extensions =     {
        "Filtered View" =         {
            changes =             (
                "<YapDatabaseViewRowChange: Delete pre(0 -> ~) post(0 -> ~) group(Foobar) collectionKey(<YapCollectionKey collection(Foobar) key(41)>)",
                "<YapDatabaseViewSectionChange: Delete group(Foobar)"
            );
        };
        "Regular View" =         {
            changes =             (
                "<YapDatabaseViewRowChange: Delete pre(0 -> ~) post(0 -> ~) group(Foobar) collectionKey(<YapCollectionKey collection(Foobar) key(41)>)",
                "<YapDatabaseViewRowChange: Insert pre(~ -> 0) post(~ -> 0) group(Foobar) collectionKey(<YapCollectionKey collection(Foobar) key(41)>)"
            );
        };
    };
    metadataChanges = "<YapSet: 0x7f81d3e76d90>";
    objectChanges = "<YapSet: 0x7f81d3e76a70>";
    snapshot = 121;
}}
```

We see that the regular view experiences a delete followed by an insert. But the filtered view ends up deleting the empty group and not recreating it when the insertion happens afterwards.
## Troubleshooting

I ran into this in a way more convoluted setup, where items were missing after a multi-phase database maintenance pass. My project is Swift-only and I have TaylorSource stacked on top of YapDatabaseExtensions stacked on top of YapDatabase.

But simplifying the change set, capturing the above notification and stepping through the code has led me to believe that the bookkeeping error happens in `YapDatabaseFilteredViewTransaction`.

It is inside `YapDatabaseFilteredViewTransaction` that the `YapDatabaseViewSectionChange.deleteGroup` initializer is called and there is no call to `YapDatabaseViewSectionChange.insertGroup` anywhere in that file. The group is lost and never returns, even though it is non-empty in the parent view after the transaction is committed.

**Comment by rsenerol** [comment]
I think I'm experimenting the same issue. My configuration is the following:
YapDatabaseView-A
YapDatabaseFilteredView-B has YapDatabaseView-A as parent view.
YapDatabaseFIlteredView-C has YapDatabaseFilteredView-B as parent view.

When I update a row of YapDatabaseView-A, YapDatabaseFilteredView-B gets correctly updated and the row  gets deleted if the modified object does not pass the filter anymore. BUT YapDatabaseFIlteredView-C does not get updated as expected (numberOfItemsInAllGroups() returns a wrong value because after receiving the notifications).

Indeed, the resulting of YapDatabaseModifiedNotification looks like:

[NSConcreteNotification 0x7fe97ed0b8b0 {name = YapDatabaseModifiedNotification; object = <YapDatabase: 0x7fe97bdeef20>; userInfo = {
    connection = "<YapDatabaseConnection: 0x7fe97e099bd0>";
    extensions =  {
        "YapDatabaseView-A" = {
            changes =  (
                "<YapDatabaseViewRowChange: Update pre(1) post(1 -> 1) group(all) collectionKey(<YapCollectionKey collection(Foobar) key(28729298)>)"
            );
        };
        "YapDatabaseFilteredView-B" = {
            changes =  (
                "<YapDatabaseViewRowChange: Delete pre(0 -> ~) post(0 -> ~) group(all) collectionKey(<YapCollectionKey collection(Foobar) key(28729298)>)",
                "<YapDatabaseViewSectionChange: Delete group(all)"
            );
        };
    };
    metadataChanges = "<YapSet: 0x7fe97e708b50>";
    snapshot = 224;
}}] 

The notifications does not have anything related to YapDatabaseFIlteredView-C. The result expected is: YapDatabaseView-A (Update) -> YapDatabaseFIlteredView-B (Delete) -> YapDatabaseFIlteredView-C (Delete)

**Comment by heiberg** [comment]
It's been 4 years. Closing this to clean up my issue list.
