### ISSUE TITLE
Invalid connection state in preReadTransaction exception with empty changesets

### ISSUE THREAD

**Issue by ksuther** [yapstudios/YapDatabase#330]
I'm seeing the following exception occasionally:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid connection state in preReadTransaction: snapshot(274) != dbSnapshot(284): (
)'
```

With the following backtrace:

```
0   CoreFoundation                       0x00007fff91f6a024 __exceptionPreprocess + 148
1   libobjc.A.dylib                      0x00007fff98af176e objc_exception_throw + 42
2   CoreFoundation                       0x00007fff91f69e1a +[NSException raise:format:arguments:] + 105
3   Foundation                           0x00007fff8fe0b99b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
4   YapDatabase                          0x0000000105677ea9 -[YapDatabaseConnection preReadTransaction:] (YapDatabaseConnection.m:2346)
5   YapDatabase                          0x0000000105677258 __76-[YapDatabaseConnection asyncReadWithBlock:completionQueue:completionBlock:]_block_invoke (YapDatabaseConnection.m:1993)
6   libdispatch.dylib                    0x00007fff9096f700 _dispatch_call_block_and_release + 12
7   libdispatch.dylib                    0x00007fff9096be73 _dispatch_client_callout + 8
8   libdispatch.dylib                    0x00007fff9096f5cd _dispatch_queue_drain + 1100
9   libdispatch.dylib                    0x00007fff9096f030 _dispatch_queue_invoke + 202
10  libdispatch.dylib                    0x00007fff9096ebef _dispatch_root_queue_drain + 463
11  libdispatch.dylib                    0x00007fff9096ea1c _dispatch_worker_thread3 + 91
12  libsystem_pthread.dylib              0x00007fff93a56a9d _pthread_wqthread + 728
13  libsystem_pthread.dylib              0x00007fff93a543dd start_wqthread + 12
```

It seems suspicious that changesets is empty. The crash only occurs when changesets is empty (but not nil).

I'm entirely willing to accept that I'm doing something incorrectly on my end, but does anyone know what situations could cause changesets to be empty?

**Comment by robbiehanson** [comment]
Some questions to narrow the search:

- Are you accessing the same YapDatabase with multiple processes ?
- Are you running any vacuum methods (available via YapDatabaseConnection) ?
- Are you running any backup methods (available via YapDatabaseConnection) ?

**Comment by ksuther** [comment]
* No intentional multiprocess accesses, but it's possible if someone launches two copies and runs them in parallel. We show a warning when they do this but they can ignore it. Considering the crash is relatively infrequent, this seems like a possibility. If accessing with multiple processes can cause this then I'll try increasing the enforcement to prevent that from happening.
* No vacuums or backups.

Thanks!

**Comment by robbiehanson** [comment]
> Considering the crash is relatively infrequent, this seems like a possibility.

This seems like the most likely culprit.

> If accessing with multiple processes can cause this then I'll try increasing the enforcement to prevent that from happening.

Another option may be to allow it: https://github.com/yapstudios/YapDatabase/wiki/Multiprocess-Support

Obviously this also depends on whether doing so would affect other components of the app.
