### ISSUE TITLE
YapDatabaseCloudKit: Cast issue in hashRecordID:databaseIdentifier:

### ISSUE THREAD

**Issue by vzarubanov** [yapstudios/YapDatabase#345]
I'm trying to sync data with publicCloudDatabase.

YapDatabase (2.9.1)
YapDatabaseCloudKit -> YapDatabaseCloudKitTransaction.m -> line 1069

`memcpy(buffer, (void *)'_', 1);`   cause EXC_BAD_ACCESS crash. I am not sure that casting `char` to `void*` makes sense. 

Solution 1: I've changed `'_'` to `"_"` and now `char*` to `void*` casting seems working.
		`memcpy(buffer, (void *)"_", 1);`

Solution 2:  `char underscore = '_';`
		   `memcpy(buffer, (void *)(&underscore), 1);`

For both solutions sync works well. But I'm not sure which one was supposed to be here.

Please take a look on that.
Thanks.

**Comment by robbiehanson** [comment]
Good catch. And thanks for the solutions.
