### ISSUE TITLE
How to update database record

### ISSUE THREAD

**Issue by y0unghe** [yapstudios/YapDatabase#359]
I am using Mantle as model framework. I have a mode like below:

```
Season.h
@interface Season : MTLModel <MTLJSONSerializing>

@property (nonatomic, copy) NSNumber *seasonID;
@property (nonatomic, strong) NSArray *episodes;

Season.m
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             @"seasonID": @"id",
             @"episodes": @"episodes"
             };
}

Episode.h

@interface Episode : MTLModel <MTLJSONSerializing>

@property (nonatomic, copy) NSNumber *watched;
```

As you can see the season have many episodes. So I save the Season to database using YapDatabase:

```
[[DatabaseUtility sharedUtility].database.newConnection asyncReadWriteWithBlock:^(YapDatabaseReadWriteTransaction * _Nonnull transaction) {
            [transaction setObject:season forKey:season.seasonID.stringValue inCollection:kSeason];
        } completionBlock:^{

        }];
```

The situation is I want to update episode's watched value. So will below work?

```
    NSIndexPath *indexPath = [self.tableView indexPathForCell:cell];
    Episode *episode = self.season.episodes[indexPath.row];
    if (index == 0) {
        [[DatabaseUtility sharedUtility].database.newConnection asyncReadWriteWithBlock:^(YapDatabaseReadWriteTransaction * _Nonnull transaction) {
            Episode *currentEpisode = [[transaction objectForKey:episode.episodeID.stringValue inCollection:kEpisode] copy];
            currentEpisode.watched = @(YES);

            [transaction setObject:currentEpisode forKey:episode.episodeID.stringValue inCollection:kEpisode];
        } completionBlock:^{
            dispatch_async(dispatch_get_main_queue(), ^{
                cell.backgroundColor = [UIColor redColor];
            });
        }];
    }
```

**Comment by accatyyc** [comment]
Yes, that's the correct way to do it. However, I do recommend that you consider using [metadata](https://github.com/yapstudios/YapDatabase/wiki/Metadata) for storing this.

This is what I commonly use metadata for. Since `watched` isn't directly related to the model object, but is more of a user property, it feels better to have it as metadata. That way you can update the object without caring about keeping the old `watched`-value, and you can update the `watched`-value without touching the actual object.

**Comment by y0unghe** [comment]
@accatyyc Sorry I didn't copy the right code. I have updated the question, could you take a look again?

**Comment by accatyyc** [comment]
It is still correct to do it that way. But I do still recommend that you take a look at metadata.
