### ISSUE TITLE
YapDatabase >= 2.6 doesn't work with iOS7

### ISSUE THREAD

**Issue by Sur3** [yapstudios/YapDatabase#360]
Hi i ran into the problem, that YapDatabase/SQLCipher asked for CloudKit but CloudKit was introduced in iOS 8 so i couldn't compile YapDatabase on iOS 7 and needed to downgrade to YapDatabase 2.5.4, please use some precompiler-directive or wrapper function to disable or replace CloudKit in iOS 7.

This was introduced with bug #101

**Comment by Sur3** [comment]
I also read something about weak bindings, that would probably be the fastest workaround.

**Comment by robbiehanson** [comment]
The fix is to not include the YapDatabaseCloudKit in your project. Generally this is done via CocoaPods, by including only the 'core', and the extensions that you explicitly use.
