### ISSUE TITLE
Migrate to xCode 8

### ISSUE THREAD

**Issue by hellbit** [yapstudios/YapDatabase#363]
Hello guys! Thank you for your lyb. I have objc project and I try migrate to xcode 8 but I have problems with it. Did you try start using Yapdatabase with xcode 8? Thx

**Comment by robbiehanson** [comment]
How are you integrating YapDatabase with your project? CocoaPods? Carthage?

**Comment by hellbit** [comment]
I use CocoaPods

**Comment by kressm** [comment]
@robbiehanson @hellbit This is the error I am getting with xCode 8 and CocoaPods. 

Error: Include of non-modular header inside framework module 'YapDatabase'

My project is using Swift 2.3. 

In the "AppName-Bridging-Header.h" file I import the YapDatabase:

#import <YapDatabase/YapDatabase.h>

I'm at a loss as to what to do. I really need to be able to compile the project.

**Comment by accatyyc** [comment]
Are you compiling pods as frameworks? YapDatabase compiles fine in Xcode 8 for us. Try removing `use_frameworks!` from your Podfile (if you have it) and then run `pod install`.

**Comment by chrisballinger** [comment]
If you're using Swift you need `use_frameworks!`

**Comment by robfeldmann** [comment]
Has anyone figured this out because I too am running into this issue and am at a loss for what to do. 

I have the "Error: Include of non-modular header inside framework module 'YapDatabase'".

I also have the same error in /Pods/YapDatabase/Standard/Core/yap_vfs_shim.h, line 8:

#include "sqlite3.h"

Running release Xcode 8 and migrating my project to Swift 2.3.

**Comment by chrisballinger** [comment]
@robfeldmann `yap_vfs_shim.h` needs to be a private header. It should be a private header (YapDatabase/YapDatabase/Internal/yap_vfs_shim.h) not YapDatabase/Standard/Core/yap_vfs_shim.h.

**Comment by robfeldmann** [comment]
@chrisballinger By all indications it seems to be a private header (that is, it is declared private and it is marked private in Xcode's Target Membership pane. I did nothing to alter the cocoapod as it was defined.

**Comment by chrisballinger** [comment]
@robfeldmann Maybe try deleting your Pods folder and re-running `pod install`.
