### ISSUE TITLE
EXC_BAD_ACCESS on YapDatabaseConnection

### ISSUE THREAD

**Issue by luzianscherrer** [yapstudios/YapDatabase#366]
I've upgraded to Xcode 8 and YapDatabase 2.9.2. My code has been working fine before. 

Here's what's happening now:

    YapDatabaseConnection *dbWriteConnection;
    dbWriteConnection = [myDatabase newConnection];
    NSLog(@"Connection: %@", dbWriteConnection);

Output:

    Connection: <YapDatabaseConnection: 0x7fe368720b60>

Then later in the code:

    NSLog(@"Connection: %@", dbWriteConnection); // Crashes with EXC_BAD_ACCESS

Debugger:

    (lldb) po dbWriteConnection
    objc[2018]: pthread_rwlock_wrlock failed (11)
    0x00007fe368720b68

Huh? What's going on here? Whey does the YapDatabaseConnection change its address from 0x7fe368720b60 to 0x00007fe368720b68?

**Comment by luzianscherrer** [comment]
If I delcare the `YapDatabaseConnection *dbWriteConnection` as a strong property as in

    @property (nonatomic, strong) YapDatabaseConnection *dbWriteConnection;

then it is working fine. But why is `dbWriteConnection` released in the example above?

**Comment by accatyyc** [comment]
Impossible to tell without seeing the rest of the code - but if you're creating it in a method and not storing it in an instance variable/property, then it would go out of scope when that function ends. That in turn means it would be deallocated just like any other object. Could that be the problem?

**Comment by luzianscherrer** [comment]
Yes, I think you are right. I've migrated to property and now the deallocation problem is solved. This was not a YapDatabase issue I guess - sorry for the disturbance.
