### ISSUE TITLE
upgrade CocoaLumberjack to 3.x

### ISSUE THREAD

**Issue by sbhhbs** [yapstudios/YapDatabase#367]

**Comment by accatyyc** [comment]
Just FYI, this would break compatibility with Xcode < 8. What are the benefits of using 3.x?

**Comment by sbhhbs** [comment]
Currently YapDatabase point to a 2.x CocoaLumberjack, so pod will refuse to upgrade CocoaLumberjack to a 3.x version, which brings better support for swift 3.

**Comment by johnbryant** [comment]
I have the same problem, my app can not be built without cocoalumberjack 3.x in xcode8 swift3

**Comment by JamieWhite** [comment]
if it helps I've got a fork that removes Cocoalumberjack https://github.com/JamieWhite/YapDatabase/commits/NoLumberjack

**Comment by johnbryant** [comment]
@JamieWhite Thank u, but it still go something wrong showed in the image below.
![snip20160929_25](https://cloud.githubusercontent.com/assets/5527451/18922707/56385806-85dc-11e6-8820-a9f128e35a57.png)

**Comment by JamieWhite** [comment]
Ah you're using cocoapods. I'm using Carthage. I've just updated the Podspec so try again

**Comment by Niphery** [comment]
@JamieWhite 
`- `CocoaLumberjack` required by `Podfile`
- `CocoaLumberjack (= 3.0.0)` required by `Podfile.lock`
- `CocoaLumberjack (~> 2)` required by `YapDatabase/Standard/Core (2.9.3)``

**Comment by robbiehanson** [comment]
CocoaLumberjack v3.x is now supported in YapDatabase "v3.0" branch.
