### ISSUE TITLE
Cocoapods updates YapDatabase to 2.9.1

### ISSUE THREAD

**Issue by onfoot** [yapstudios/YapDatabase#368]
To note, I use `YapDatabase/SQLCipher/Core` and `YapDatabase/SQLCipher/Extensions/Views`.

After I already had 2.9.2 installed, upon a pods update a few days ago it was downgraded to 2.9.1 and won't go back.

Just to check, I removed the Pods subdirectory and the lock file and I still get the same version.

No one else with that issue?

**Comment by VaneCGo** [comment]
Yes, I have the same issue when using `pod 'YapDatabase/SQLCipher' `. I would like to install 2.9.3 since it has a workaround to fix an issue with Cocoapods 1.0. Do you still have this issue?

**Comment by onfoot** [comment]
Yes, still stuck on 2.9.1.

**Comment by VaneCGo** [comment]
Wondering if it's a podspec version issue. I see `CloudKit` iOS deployment target https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase.podspec#L176 is different from the pod itself: https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase.podspec#L17 . And maybe this is causing the issue 🤔

**Comment by VaneCGo** [comment]
Hey, @onfoot, while this is resolved, I'm doing this in my Podfile and it installs Yap 2.9.2. I hope it helps! `pod 'YapDatabase/SQLCipher', :git => 'https://github.com/yapstudios/YapDatabase.git', :tag => '2.9.3'`

**Comment by michaelkirk** [comment]
Seems like 2.9.3 was never published to cocoapods: https://github.com/CocoaPods/Specs/tree/master/Specs/c/2/8/YapDatabase

**Comment by robbiehanson** [comment]
>Seems like 2.9.3 was never published to cocoapods: 
You're right. I remember pushing it to cocoapods, but it must not have stuck.
I pushed it again, and it should be there now:
https://github.com/CocoaPods/Specs/tree/master/Specs/c/2/8/YapDatabase/2.9.3

**Comment by robbiehanson** [comment]
> Wondering if it's a podspec version issue. I see CloudKit iOS deployment target (iOS 8.0) is different from the pod itself (iOS 6.0) . And maybe this is causing the issue

If that's the case, it should be fixed due to this commit:
https://github.com/yapstudios/YapDatabase/commit/8ea3b2f216e5c30821093b5daae6587c5ba9d135

It's available in the "v3.0" branch, and should be pushed to master soon, and released.
