### ISSUE TITLE
Sync solution?

### ISSUE THREAD

**Issue by brendand** [yapstudios/YapDatabase#37]
I know this topic has been covered, but that topic has been closed. I commented there, but wasn't sure if it would be seen, so forgive me for opening a new issue.

I just wanted to see if there's any progress or best practices on implementing a generic sync solution for YapDatabase.

Currently I use iCloud sync by creating a structurally equivalent copy of my main sqlite file that contains only the incremental changes since the last time a sync had been performed. I store those change files in my iCloud container and then process it on the other side when I get a notification that they've been downloaded. After processing them, I trigger refreshes of my UI when processing has finished. 

It would be great if there was some solution built-in to YapDatabase to handle syncing changes between devices (Mac & iOS).

Is there anything inherent in YapDatabase that would ensure there would be no conflicts between primary keys generated on different devices at different times? I use a UUID for all my primary keys, so there's no conflicts when I generate data on any device. Looking into a YapDatabase it looks like you're using integer keys, so that might be a problem unless there's a secondary key which can uniquely identify a device.

**Comment by robbiehanson** [comment]
> The public database would be fine if I wanted to provide public access to all users of my app to a specific database. But it wouldn't work for the main scenario I was thinking about. Private syncing of data between different users.

Don't think of "public" as truly public. Instead, you may think of it as "protected". Meaning only YOU (the app developer) chooses who can access what within this scope. Thus you can put something in this protected scope, and enforce that only users ABC & XYZ have permission to access the zone/records.

**Comment by robbiehanson** [comment]
Closing this topic now, as v2.6 is officially released. More sync backends to be supported soon...

**Comment by iosdev-republicofapps** [comment]
Hi,

I would like to use and or help build a YapDatabaseRESTSync type extension: sync YapDatabase with a REST API backend.  I'll create a separate issue for that but any guidance would be appreciated!

Thanks
