### ISSUE TITLE
Is there a YapDatabaseCloudCore Example?

### ISSUE THREAD

**Issue by shsteven** [yapstudios/YapDatabase#379]
Hi @robbiehanson , 
Came across the awesome new extension [CloudCore](https://github.com/yapstudios/YapDatabase/wiki/YapDatabaseCloudCore) module in the Wiki page. 
do you have any example code for YapDatabaseCloudCore?

**Comment by robbiehanson** [comment]
Yup, check out the "CloudKitTodo" sample application (included in the project):

https://github.com/yapstudios/YapDatabase/tree/master/Examples/CloudKitTodo

**Comment by shsteven** [comment]
Brilliant. Thank you!
