### ISSUE TITLE
YapDatabase SQLite error code:6922, 'disk I/O error'

### ISSUE THREAD

**Issue by Leopoldog-playster** [yapstudios/YapDatabase#383]
Hello everyone! I'm currently working on integrating YapDatabase to our mobile app. I'm getting the following error: 
(6922) I/O error for database at /Users/leopoldo/Library/Developer/CoreSimulator/Devices/4AFCCB3F-D035-4E45-8C2A-CBFE84FB335E/data/Containers/Data/Application/C47D7C9E-C1BB-4F27-9B93-3B3C23FF36BF/Documents/AECore.sqlite.  SQLite error code:6922, 'disk I/O error'.

This happens when the application leaves memory just after performing a download followed by a  read&write transaction, i.e; when the user closes the app after downloading some an item.

I'm guessing the transaction might be getting interrupted by the "force close" of the app? How could I make sure that when the app is about yo leave memory (applicationWillTerminate:) all the pending transactions are committed before the software closes?

I haven't had any luck finding info on the web. There's not much about Yap.

Any suggestions?

Thanks in advance!

**Comment by N-ihad** [comment]
Experiencing same. When app is force closed, YapDatabase doesn't seem to commit transactions
