### ISSUE TITLE
Support for CocoaLumberjack 3.0?

### ISSUE THREAD

**Issue by arorajatin** [yapstudios/YapDatabase#386]
The application I am developing uses the latest version of CocoaLumberJack i.e. 3.0.0. Are we planning to update CocoaLumberjack anytime soon?

**Comment by Niphery** [comment]
Any Update on this?
Also personally the build process fail with carthage probably because of xcode 8.

**Comment by qiulang** [comment]
I got this problem to with pod
[!] Unable to satisfy the following requirements:


- `CocoaLumberjack` required by `Podfile`
- `CocoaLumberjack (= 3.1.0)` required by `Podfile.lock`
- `CocoaLumberjack (>= 2.0)` required by `XCDLumberjackNSLogger (1.1.1)`
- `CocoaLumberjack (~> 1.6.2)` required by `YapDatabase (1.2.1)`

**Comment by robbiehanson** [comment]
@chrisballinger 's pull request has been merged into "v3.0" branch.
