### ISSUE TITLE
Can we not use the word abortion?

### ISSUE THREAD

**Issue by sanjaykbhat** [yapstudios/YapDatabase#388]
In the below file: 
\YapDatabase\ Extensions\ SearchResults\ YapDatabaseSearchQueue.h
We are using the word abortion to indicate to abort the process. Considering that this is actually can be read in a different manner can we not change it exit, end, stop etc?

**Comment by JimRoepcke** [comment]
Does that word appear on line 1984?

You created your GitHub account today and you're already asking people to censor their repos, and not just this one. I'm curious, what is your agenda?

**Comment by uadev** [comment]
Just a troll.

**Comment by sanjaykbhat** [comment]
No Agenda. My company is using this library and our code scanner picked
this line up. I just wanted to clarify if the wording could be done better
since this isn't in anyway related to the scientific/medical definition.

**Comment by JimRoepcke** [comment]
If something aborts, it is aborted, and it is said to have undergone an abortion. The word does not strictly and exclusively refer to the aborting of fetuses, human or otherwise.

**Comment by robbiehanson** [comment]
The words in question are:

```objective-c
/**
 * In terms of operation, this method works in concert with the queue.
 * That is, when you invoke this method, then all queries in the queue prior to invoking this method
 * are marked for abortion. Meaning that you can invoke this method,
 * and then enqueue a new query in order to abort any prior searches, and start processing the newest query ASAP.
```

If the documentation was incorrect or ambiguous, then certainly I'd be happy to fix/improve it. Also, I would consider making changes if I had used curse words (I may have been guilty of this once or twice in the past, during a fit of debugging frustration). However, in this case, the term "queries in the queue [...] are marked for abortion" is a correct & non-ambiguous description of the method's execution. And it's clearly not designed to be purposefully offensive.

That being said, however, I do not believe this is the crux of your problem. Your company has made the decision to use a code scanner that searches for "dirty words or phrases".  I will assume there is a rational business reason behind this decision. The problem you have is

- the code scanner is scanning 3rd party libraries
- the code scanner isn't differentiating between comments, and strings presented to the end user
- the code scanner is tagging words which could have a "clean" meaning

Any software application of significant size will end up using a multitude of 3rd party open source libraries, which will equate to hundreds of thousands of lines of code. The chances that your code scanner will continue to run into issues in these libraries would seem high. What I'm trying to say is that you've made the decision not to fix the code scanner, or prevent it from scanning 3rd party open source libraries, but rather to get the 3rd party libraries themselves to change the words. This doesn't seem like a sustainable solution.

**Comment by sanjaykbhat** [comment]
Thanks for your detailed comments. I am already working on some of your suggestions. I am closing my issue since this seems like a clean case and the scanner tagged it falsely. We do tend to ignore external code. but in some cases the words used are indeed profanity and are so bad that they are worth a shot trying to get it fixed.
