### ISSUE TITLE
What if I wanna do something after an object finish its indexing?

### ISSUE THREAD

**Issue by tonychan818** [yapstudios/YapDatabase#390]
Now I have class A, class B.
in my situation, now it is.
class A saved.
trigger the class A did modify hook.
class B lookup for an object from class A, but it can't, because class A still not process it's index view.
class A index view processing.

what if I wanna class B lookup for object in class A's index view finished.
what can I do?

**Comment by robbiehanson** [comment]
When the database is modified, YapDatabase enumerates extensions in the order in which they were modified. From what I gather, you have an index extension & a hooks extension. And you want to be able to read the information from the index extension within the hooks extension (within didModifyRow). In that case, just make sure the hooks extension is registered AFTER the index extension, and you'll be able to read from it.
