### ISSUE TITLE
It costs really long time to initialize the data base while starting app

### ISSUE THREAD

**Issue by robyzhou** [yapstudios/YapDatabase#393]
Hi guys,

I found YapDatabase costs a long time to initialize the data base while starting app. Here is the log bellow:

>......
YapDatabase: Post-checkpoint (mode=truncate): result(0): frames(0) checkpointed(0)
YapDatabase: Post-checkpoint (mode=truncate): result(0): frames(0) checkpointed(0)
YapDatabase: Post-checkpoint (mode=truncate): result(0): frames(0) checkpointed(0)
YapDatabase: Post-checkpoint (mode=truncate): result(0): frames(0) checkpointed(0)
YapDatabase: Post-checkpoint (mode=truncate): result(0): frames(0) checkpointed(0)
YapDatabase: Post-checkpoint (mode=truncate): result(0): frames(0) checkpointed(0)
YapDatabase: Post-checkpoint (mode=truncate): result(0): frames(0) checkpointed(0)
YapDatabase: Post-checkpoint (mode=truncate): result(0): frames(0) checkpointed(0)
YapDatabase: Post-checkpoint (mode=truncate): result(0): frames(0) checkpointed(0)
YapDatabase: Post-checkpoint (mode=truncate): result(0): frames(0) checkpointed(0)
YapDatabase: Post-checkpoint (mode=truncate): result(0): frames(0) checkpointed(0)
YapDatabase: Post-checkpoint (mode=truncate): result(0): frames(0) checkpointed(0)
YapDatabase: Post-checkpoint (mode=truncate): result(0): frames(0) checkpointed(0)
YapDatabase: Post-checkpoint (mode=truncate): result(0): frames(0) checkpointed(0)
......

Actually, in my app, I created the connection in AppDelegate as bellow:
```
    self.db = [[YapDatabase alloc] initWithPath:dbPath];
    
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(yapDatabaseModified:)
                                                 name:YapDatabaseModifiedNotification
                                               object:self.db];
    
    //create extensions here
    [YapDBInitializer createYapDBExtension];
    
    self.writeConnection = [self.db newConnection];
    self.writeConnection.objectCacheLimit = 1000;
    
    self.readConnection = [self.db newConnection];
    [self.readConnection beginLongLivedReadTransaction];
    self.readConnection.objectCacheLimit = 1000;
```

The writeConnection was used to write objects to the database, and also usually used to read objects from the database when I need read the objects out just after writing it in.
The readConnection is a long-lived transactions, it was used only read objects from the database, and YapMapping was created from readConnection.
I have only the **two** connections in my app, no more.

Then, in the observer selector, I move the readConnection forward as bellow:
```
- (void)yapDatabaseModified:(NSNotification *)notification
{
    dispatch_async(mySerialQueue, ^{
        //notify the observers, we will move the readConnection forward
        [[NSNotificationCenter defaultCenter] postNotificationName:YapDatabaseWillUpdateNotification object:self];
        
        //move the readConnection forward
        NSArray* notifications = [self.readConnection beginLongLivedReadTransaction];
        
        //post the notifications to make the observers check what changed if needed, and action with the parameter
        if (notifications) {
            NSDictionary* dic = @{@"usrinfo": notifications};
            [[NSNotificationCenter defaultCenter] postNotificationName:YapDatabaseDidUpdateNotification
                                                                object:self
                                                              userInfo:dic];
        }
    });
}
```

It's nearly the key code I am using YapDatabase above, I have checked the readConnection was only used to read objects.

But, sometimes I get the logs as above, it costs about 10 seconds, and then the app works. Because my app need read data from database to initialize, so the app looks freeze there. I have checked that, YapDatabase keep invoking aggressiveTryTruncateLargeWAL frequently while starting app.

Do you guys have any suggestion on this issue? Thanks in advance.

roby

**Comment by Heinemark** [comment]
Did you solve the problem? Otherwise I can share my DatabaseManager which has a setup more like what's suggested in the documentation.

**Comment by robyzhou** [comment]
@Heinemark hi, sorry for my lately response, I just forgot it for a longgggg time. I have tried some way to speed up the app initialize, the performance has been promoted a little. And, if you are willing to send your DatabaseManager to me, I'd appreciate your help! Thanks in advance!

**Comment by robbiehanson** [comment]
This issue should have been fixed: https://github.com/yapstudios/YapDatabase/issues/197#issuecomment-318852193
