### ISSUE TITLE
Taking too Long while adding list of Objects

### ISSUE THREAD

**Issue by thesaad** [yapstudios/YapDatabase#394]
I am having issues while adding a list of objects in database. There are about 2000 objects and it takes more than 3 minutes to save all the records in database. My code is:

`for (NSXMLElement *item in rosterItems)
    {
        // During roster population, we need to filter out items for users who aren't actually in our roster.
        // That is, those users who have requested to be our buddy, but we haven't approved yet.
        // This is described in more detail in the method isRosterItem above.
        
        NSString *jidStr = [item attributeStringValueForName:@"jid"];
        XMPPJID *jid = [[XMPPJID jidWithString:jidStr] bareJID];
        
        if([[jid bare] isEqualToString:[[stream myJID] bare]])
        {
            // ignore self buddy
            return;
        }
        
        OTRXMPPBuddy *buddy = [self buddyWithJID:jid xmppStream:stream];
        
        NSString *subscription = [item attributeStringValueForName:@"subscription"];
        if ([subscription isEqualToString:@"remove"])
        {
            if (buddy)
            {
                [self.databaseConnection readWriteWithBlock:^(YapDatabaseReadWriteTransaction *transaction) {
                    [transaction setObject:nil forKey:buddy.uniqueId inCollection:[OTRXMPPBuddy collection]];
                }];
            }
        }
        else if(buddy)
        {
            [self.databaseConnection readWriteWithBlock:^(YapDatabaseReadWriteTransaction *transaction) {
                
                OTRXMPPBuddy *localBuddy = [[OTRXMPPBuddy fetchObjectWithUniqueID:buddy.uniqueId transaction:transaction] copy];
                if (!localBuddy) {
                    localBuddy = buddy;
                }
                
                if (![localBuddy isKindOfClass:[OTRXMPPBuddy class]]) {
                    OTRXMPPBuddy *xmppBuddy = [[OTRXMPPBuddy alloc] init];
                    [xmppBuddy mergeValuesForKeysFromModel:localBuddy];
                    [localBuddy removeWithTransaction:transaction];
                    localBuddy = xmppBuddy;
                }
                
                NSString *name = [item attributeStringValueForName:@"name"];
                
                if (name.length) {
                    localBuddy.displayName = name;
                }
                
                if ([self isPendingApprovalElement:item]) {
                    localBuddy.pendingApproval = YES;
                }
                else {
                    localBuddy.pendingApproval = NO;
                }
                
                
                [localBuddy saveWithTransaction:transaction];
            }];
        
        }
        
    }
    `

I know there is something wrong with the one-by-one insertion but can't find a way where I can collectively insert all records in a signle transaction.

**Comment by vkovtash** [comment]
Why don't you try something like this
```
[self.databaseConnection readWriteWithBlock:^(YapDatabaseReadWriteTransaction *transaction) 
{
	for (NSXMLElement *item in rosterItems)
	{
	// During roster population, we need to filter out items for users who aren't actually in our roster.
	// That is, those users who have requested to be our buddy, but we haven't approved yet.
	// This is described in more detail in the method isRosterItem above.

	    NSString *jidStr = [item attributeStringValueForName:@"jid"];
	    XMPPJID *jid = [[XMPPJID jidWithString:jidStr] bareJID];
    
	    if([[jid bare] isEqualToString:[[stream myJID] bare]])
	    {
	        // ignore self buddy
	        continue;
	    }
    
	    OTRXMPPBuddy *buddy = [self buddyWithJID:jid xmppStream:stream];
    
	    NSString *subscription = [item attributeStringValueForName:@"subscription"];
	    if ([subscription isEqualToString:@"remove"])
	    {
	        if (buddy)
	        {
	           [transaction setObject:nil forKey:buddy.uniqueId inCollection:[OTRXMPPBuddy collection]];
	        }
	    }
	    else if(buddy)
	    {
            
	            OTRXMPPBuddy *localBuddy = [[OTRXMPPBuddy fetchObjectWithUniqueID:buddy.uniqueId transaction:transaction] copy];
	            if (!localBuddy) {
	                localBuddy = buddy;
	            }
            
	            if (![localBuddy isKindOfClass:[OTRXMPPBuddy class]]) {
	                OTRXMPPBuddy *xmppBuddy = [[OTRXMPPBuddy alloc] init];
	                [xmppBuddy mergeValuesForKeysFromModel:localBuddy];
	                [localBuddy removeWithTransaction:transaction];
	                localBuddy = xmppBuddy;
	            }
            
	            NSString *name = [item attributeStringValueForName:@"name"];
            
	            if (name.length) {
	                localBuddy.displayName = name;
	            }
            
	            if ([self isPendingApprovalElement:item]) {
	                localBuddy.pendingApproval = YES;
	            }
	            else {
	                localBuddy.pendingApproval = NO;
	            }
            
	            [localBuddy saveWithTransaction:transaction];
	    }
	}
}];
```
