### ISSUE TITLE
Carthage build fails with 'YapDatabaseConnectionConfig.h' file not found

### ISSUE THREAD

**Issue by uthiel** [yapstudios/YapDatabase#416]
Carthage fails with

`Carthage/Checkouts/YapDatabase/YapDatabase/YapDatabase.h:7:9: fatal error: 'YapDatabaseConnectionConfig.h' file not found`

**Comment by uthiel** [comment]
Reason seems to be `YapDatabaseConnectionConfig.h` is missing from both the `.xcodeproj` and the `.modulemap` file.

**Comment by robbiehanson** [comment]
Should be fixed in commit #dcf12ff94c9c86d5069f3ed0689a97ff9ca9de2d
