### ISSUE TITLE
XCode 8.3.3: Build fails with error 'no such file or directory:YapDatabaseConnectionDefaults.m'

### ISSUE THREAD

**Issue by uthiel** [yapstudios/YapDatabase#417]
Steps to reproduce: 

1. Download current master, unzip, double-click on `YapDatabase.xcodeproj`
2. Select Target "YapDatabase-iOS > Generic iOS Device"
3. Press ⌘B

Result: `no such file or directory: 'YapDatabase-master/YapDatabase/Internal/YapDatabaseConnectionDefaults.m'`

**Comment by uthiel** [comment]
the file`YapDatabaseConnectionDefaults.h` is referenced in `YapDatabase.h` but missing from the repository.

**Comment by shiki** [comment]
I am also getting this issue in Carthage builds

**Comment by wh33landaxel** [comment]
Also getting this issue, is there any working fix for this?

**Comment by robbiehanson** [comment]
Should be fixed in commit dcf12ff94c9c86d5069f3ed0689a97ff9ca9de2d
