### ISSUE TITLE
Does not work with Xcode 9 beta 3

### ISSUE THREAD

**Issue by dhoskins** [yapstudios/YapDatabase#418]
`YapDatabase/Standard/Core`, has a dependency on CocoaLumberjack.

However CocoaLumberjack has a conflict with Xcode 9 beta 3 as described here: CocoaLumberjack/CocoaLumberjack#883

As such YapDatabase cannot currently be used with Xcode 9 beta 3.

**Comment by chrisballinger** [comment]
Just pin to the fixed CocoaLumberjack commit in your Podfile / Cartfile /
submodule.

**Comment by dhoskins** [comment]
Can you explain how I do this? My Podfile currently has no reference to CocoaLumberjack.

**Comment by chrisballinger** [comment]
Add a reference to it.

```ruby
pod 'CocoaLumberjack/Swift', :git => '
https://github.com/CocoaLumberjack/CocoaLumberjack.git', :commit =>
'acc32864538c5d75b41a4bfa364b1431cf89954d' # Fixes compile error on Xcode 9
```

**Comment by dhoskins** [comment]
Huh.  TIL you cannot have multiple versions of a single Cocoapod in your project.  Thanks.
