### ISSUE TITLE
YDBLogError - In the release builds how to dump YapDB logs specifically error logs in my app's log file.

### ISSUE THREAD

**Issue by realrider** [yapstudios/YapDatabase#432]
Need to check if there are some db errors in the app when the issues are reported by the customer.
Is it possible to log the YDBLogError statements to the app logging file ?
In the release builds how to dump YapDB logs specifically error logs in my app's log file.
Debug builds, I download the app from app container and read the error statements written by the YapDB.

**Comment by robbiehanson** [comment]
Yes, there is. YapDatabase uses [CocoaLumberjack](https://github.com/CocoaLumberjack/CocoaLumberjack) (as configured in [YapDatabaseLogging.h](https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase/Internal/YapDatabaseLogging.h))

This is a professional logging framework, and there's all kinds of cool stuff you can do with it.

You can find a bunch of docs [here](https://github.com/CocoaLumberjack/CocoaLumberjack/tree/master/Documentation).
And there's a good [Getting Started](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/GettingStarted.md) article that shows you how to log to a file.
