### ISSUE TITLE
Initialisers are marked non-nullable in header, but can return nil

### ISSUE THREAD

**Issue by marcpalmer** [yapstudios/YapDatabase#433]
https://github.com/yapstudios/YapDatabase/blob/ce9c8dbceefc7fe4b47d1a91b3004f1f0451ae1a/YapDatabase/YapDatabase.m#L407

The YapDatabase initialisers can return nil but are not marked as doing so in the ObjC header, due to the `NS_ASSUME_NONNULL_BEGIN` wrapper macro.

**Comment by marcpalmer** [comment]
The problem is that in Swift you can write:

```
let db: YapDatabase = YapDatabase(path: .... )
```
This is bad when the initialiser has returned nil, for example if the file is already open.

**Comment by robbiehanson** [comment]
Good catch. Thanks for mentioning it.

**Comment by marcpalmer** [comment]
No peoblem - thanks for YapDatabase!

We actually hit this problem in Swift, where the initialiser would fail and return a nil swift was not expecting, when the file/folder could not be opened. It was quite obscure!
