### ISSUE TITLE
Can't share YapDatabase with iOS app extensions and keep database open in background.

### ISSUE THREAD

**Issue by charlesmchen** [yapstudios/YapDatabase#436]
To share a `YapDatabase` between an iOS app and iOS app extension (e.g. a share extension), the database file must reside in the "shared data container".  

iOS terminates app almost immediately if they retain a file lock on any file in the shared data container while being suspended.  This means that our iOS main app (which keeps a YapDatabase open at all times) is terminated every time it is sent to the background.  

These are `0xdead10cc` terminations and often don't yield crash logs on the device, but always show up in the device console logs.

From Apple's documentation https://developer.apple.com/library/content/technotes/tn2151/_index.html
`
The exception code 0xdead10cc indicates that an application has been terminated by the OS because it held on to a file lock or sqlite database lock during suspension. If your application is performing operations on a locked file or sqlite database at suspension time, it must request additional background execution time to complete those operations and relinquish the lock before suspending.
`

Note: These crashes don't occur in the simulator and won't occur on devices in a debugging session.

The repro is simple:

* Create an app with an "app group" and "shared data container". 
  * Since you'll need to run on a device to repro, you'll need to configure valid app ids / app groups in developer center.
  * Make sure app's name appears verbatim in your app id to simplify searching later.  
* NOTE: you don't actually need to create an app extension, although you normally wouldn't bother placing your database files in the "shared data container" if you weren't trying to share them with an app extension.
* Open a YapDatabase using a file in the "shared data container".
* Launch app on a physical device (development signing works fine).
* Kill and relaunch app (iOS won't kill apps for this reason while debugging).
* Open MacOS Console app and attach to your device.  Search for your app's name to filter the console contents.
* Launch app then send it to the background.
* In a few seconds iOS will kill the app.  
* Look for console entries like this:

`
default	18:59:59.000000 -0500	SpringBoard	 Forcing crash report of <FBApplicationProcess: 0x13905acd0; Signal; pid: 3063> (reason: 4, description: <FBApplicationProcess: 0x13905acd0; Signal; pid: 3063> was suspended with locked system files: 
	/var/mobile/Containers/Shared/AppGroup/2EB19A11-7D28-FFFF-92C3-DFF21A3B0F3A/database/Signal.sqlite)
`

* Closing our YapDatabase instance whenever the app enters the background will be highly inconvenient.
* iOS won't kill the app so long as it is in the background and not suspended (e.g. has a valid background task).  But you can only use a background task to prevent suspension for so long.

**Comment by charlesmchen** [comment]
This issue only occurs if you've enabled `SQLCipher` by setting a `cipherKeyBlock` in `YapDatabaseOptions`.

**Comment by chrisballinger** [comment]
@charlesmchen Thank you for such a detailed analysis! I also use Yap+SQLCipher in my projects and was planning to eventually use a shared database for app extensions.  :)

Does it happen when using the SQLCipher subspec without a cipherKeyBlock? Perhaps there's a bug upstream in SQLCipher...

**Comment by charlesmchen** [comment]
Hi @chrisballinger. Investigation is still ongoing but I plan on closing this issue, as this is _not_ a `YapDatabase` issue..  AFAIK the problem is in `SQLCipher` and/or `SQLite`. I've got a minimal repro and I'll probably open an issue against `SQLCipher` soon.

**Comment by brodybits** [comment]
FYI explanation by @sjlombardo is in <https://github.com/sqlcipher/sqlcipher/issues/255#issuecomment-355063368>

**Comment by charlesmchen** [comment]
cc @chrisballinger @brodybits 

There is a fix for this now.  The `SQLCipher` patch will be in a forthcoming release.  

We've got a proposed patch to `YapDatabase` in our fork:  https://github.com/signalapp/YapDatabase/pull/1  I'll open a PR against `YapDatabase` once the `SQLCipher` patch is released.  

There's a bunch of info in the comments in our `YapDatabase` PR.

**Comment by chrisballinger** [comment]
@charlesmchen Thank you for your work on this! Sounds like it was a really crazy rabbit hole to go down.

**Comment by charlesmchen** [comment]
Hi @chrisballinger .  @sjlombardo and the team at SQLCipher did the heavy lifting, and were also wonderful collaborators as we worked on this issue.  We're still testing these changes, but they look good so far.

**Comment by GlacierSecurityInc** [comment]
FYI, for anyone using the updated YapDatabaseCryptoUtils to handle this issue and still struggling with this:

We are currently attempting to move our existing database to shared space and then use convertDatabaseIfNecessary. It seems that if the database was originally created with YapDatabaseCipherCompatability_Version3, the conversion will fail at the point of trying to execute: "PRAGMA journal_mode = WAL." Or at least that's what was happening for us. We needed to run the "PRAGMA cipher_compatibility = YapDatabaseCipherCompatability_Version3" command first, which is not currently an option in the conversion routine (unless I'm missing something).

Even after this fix, it says the conversion is successful, but still crashes after being backgrounded. I've verified that the header is now unencrypted, and everything works fine while it's open. I'm guessing our issue is due to a 2nd (non-Yap) sqlite database instance being used, which hasn't yet been converted. I'll report back when I have more info.

**Comment by GlacierSecurityInc** [comment]
Confirmed that our current issue is related to the non-Yap instance. Thanks for all the work with converting Yap!

@chrisballinger I'm not sure if you've played with this yet in ChatSecure, but it seems that the IOCipher/media instance in shared space causes a crash too. Journal mode is explicitly set to WAL in sqlfs for that database instance, and crashes when the app is backgrounded. A fix seems messy and would involve libsqlfs and IOCipher.
