### ISSUE TITLE
YapDatabaseFilteredView abysmal performance

### ISSUE THREAD

**Issue by mickeyl** [yapstudios/YapDatabase#445]
For trying out YapDatabase, I just switched my app to using it. I have severe performance problems when filtering my list of `SongModel` objects — although the number is only below 600 (every song contains about 1K of data).

Here's the view creation:

```
-(void)registerDatabaseViews
{
    UILocalizedIndexedCollation* localizedIndexedCollation =  [UILocalizedIndexedCollation currentCollation];

    YapDatabaseViewGrouping* grouping = [YapDatabaseViewGrouping withRowBlock:^NSString * _Nullable(YapDatabaseReadTransaction * _Nonnull transaction, NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object, id  _Nullable metadata) {

        if ( [object isKindOfClass:SongModel.class] )
        {
            SongModel* song = (SongModel*)object;
            NSInteger section = [localizedIndexedCollation sectionForObject:song collationStringSelector:@selector(title)];
            return [localizedIndexedCollation.sectionIndexTitles objectAtIndex:section];
        }
        return nil;
    }];

    YapDatabaseViewSorting* sorting = [YapDatabaseViewSorting withRowBlock:^NSComparisonResult(YapDatabaseReadTransaction * _Nonnull transaction, NSString * _Nonnull group, NSString * _Nonnull collection1, NSString * _Nonnull key1, id  _Nonnull object1, id  _Nullable metadata1, NSString * _Nonnull collection2, NSString * _Nonnull key2, id  _Nonnull object2, id  _Nullable metadata2) {

        SongModel* song1 = (SongModel*)object1;
        SongModel* song2 = (SongModel*)object2;
        return [song1.title compare:song2.title];
    }];

    YapDatabaseAutoView* view = [[YapDatabaseAutoView alloc] initWithGrouping:grouping sorting:sorting versionTag:@"1"];
    [_db registerExtension:view withName:@"songlist"];

    YapDatabaseViewFiltering* filtering = [YapDatabaseViewFiltering withObjectBlock:^BOOL(YapDatabaseReadTransaction * _Nonnull transaction, NSString * _Nonnull group, NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object) {

        return YES;

    }];
    YapDatabaseFilteredView* filteredView = [[YapDatabaseFilteredView alloc] initWithParentViewName:@"songlist" filtering:filtering versionTag:@"0"];
    [_db registerExtension:filteredView withName:@"filtered-songlist"];
}
```

In my view controller, whenever the text in the filter bar changes, I call:

```
-(void)searchBar:(UISearchBar *)searchBar textDidChange:(NSString *)searchText
{
    YapDatabaseViewFiltering* filtering = [YapDatabaseViewFiltering withObjectBlock:^BOOL(YapDatabaseReadTransaction * _Nonnull transaction, NSString * _Nonnull group, NSString * _Nonnull collection, NSString * _Nonnull key, SongModel* _Nonnull song) {

        return [song matchesAgainstFilterString:searchText];

    }];

    dispatch_async( dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{

        [[[Session sharedSession] databaseConnection] readWriteWithBlock:^(YapDatabaseReadWriteTransaction * _Nonnull transaction) {

            [[transaction ext:@"filtered-songlist"] setFiltering:filtering versionTag:[NSString stringWithFormat:@"%u",(uint)_filterVersion++]];

        }];

    });
}
```

Calling `setFiltering` seems to take about 5-6 seconds in the simulator(!), I didn't dare to try on an actual device yet.

The table view updating routine is using the code provided in the Wiki.

Please tell me I'm doing something wrong!

**Comment by chrisballinger** [comment]
It looks like FTS is what you want instead: https://github.com/yapstudios/YapDatabase/wiki/Full-Text-Search

**Comment by mickeyl** [comment]
Thanks for the recommendation. I did some basic profiling and it looks like `initWithCode` is the actual culprit. Obviously `NSKeyedArchiver` is pretty slow. As far as I understand it, using FTS would (after an initial run) spare us from decoding every object to check whether the predicate matches.

In the meantime I'm (ab)using the key to store the relevant information, which also eliminates the need to pull the objects out of the database. Perhaps I need to move to a custom deserializer.

**Comment by uthiel** [comment]
I'm using FTS, incidentally with a Song database as well, containing ~8000 songs. In the sim, searching for a song title takes 0.05s from the time to press a key in the search field until the filtered result appears. On an iPhone 6 it is ~0.2s.

**Comment by chrisballinger** [comment]
I really really really recommend using FTS rather than a custom deserializer. No matter how well you optimize the deserializer you'll never be able to beat the right tool for the job. Sqlite's FTS, and Yap's FTS SearchView are really nice. We have 1000 camps and 20,000+ events in iBurn and searching the entire data set is instantaneous and fully animated.

**Comment by mickeyl** [comment]
Thanks for all your answers. For the time being, performance is ok by only looking at the keys, but I will consider using FTS.

**Comment by chrisballinger** [comment]
In that case, metadata blobs might be what you're looking for: https://github.com/yapstudios/YapDatabase/wiki/Metadata
