### ISSUE TITLE
Leveraging iOS cell prefetching

### ISSUE THREAD

**Issue by mickeyl** [yapstudios/YapDatabase#446]
Since iOS 10, there are protocols available to inform Table/Collection views about prefetching when scrolling. I wonder about the best way to integrate this with YapDatabase. Prefetching is supposed to happen on a background task in order not to block the main thread – I thought about prefilling the cache by querying the database without using the actual objects. Did anyone go this route yet?

**Comment by robbiehanson** [comment]
Good question.

> I thought about prefilling the [database] cache by querying the database without using the actual objects

This is the exactly what I generally recommend. (Often referred to as warming up the cache.)

In terms of fetching items from the database on the main thread, there are 2 primary areas of overhead:
1. the disk IO required to fetch the object(s) from the database
2. the CPU required to deserialize the object(s)

However, if the object is in the (database) cache, then you skip the overhead of both of these items. Meaning that the database fetch essentially becomes a dictionary lookup.

So make sure your database connection has a generous cache size, and then implement the prefetching as needed.

Also recommended: Use a [shared uiDatabaseConnection](https://github.com/yapstudios/YapDatabase/wiki/Performance-Pro#sharing_the_ui_databaseconnection) throughout your app. This will ensure that your cache remains warm when navigating between different viewControllers.
