### ISSUE TITLE
Cancelling async read(/readWrite) blocks

### ISSUE THREAD

**Issue by mickeyl** [yapstudios/YapDatabase#449]
I wonder whether it would be possible to cancel asynchronous read(/readWrite) blocks. Especially with UI programming (think UI{Table|Collection}ViewPrefetchingDataSource) you get informed that certain results are no longer likely to be displayed. It might be useful to cancel queued database access blocks then.

**Comment by robbiehanson** [comment]
This is likely best handled outside the context of the database code. For example, instead of doing this:

```objective-c
- (void)doBackgroundRead:(id)context
{
    [bgReadConnection asyncReadWithBlock:^(YapDatabaseReadTransaction *transaction){
        // do stuff...
    }];
}
```

You do something like this instead:

```objective-c
- (void)enqueueBackgroundRead:(id)context
{
    NSUInteger newCount = [atomicStuffToRead pushObject:context];
    if (newCount == 1) {
        [self dequeueBackgroundReads];
    }
}

- (void)dequeueBackgroundReads
{
    [bgReadConnection asyncReadWithBlock:^(YapDatabaseReadTransaction *transaction){
        NSArray *contexts = [atomicStuffToRead popAllObjects];
        // read all contexts...
    }];
}
```

And then you could expand upon this concept "de-enqueue" background reads when you find out you no longer need them.

Let me know what you think.
