### ISSUE TITLE
A way to check for database file integrity?

### ISSUE THREAD

**Issue by mickeyl** [yapstudios/YapDatabase#455]
Use-case: I sometimes update a "read-only" database that resides on my server. The app regularly checks whether there is a new version of the database available and if so, downloads it in the background to a "database-next" file in the home directory. On a restart of the app (whenever this will occur), I check whether there is a "database-next" file laying around and plan to copy this over the "old" database file before launching the regular app code.

Now as an additional safety net, I'd like to check whether the database has not been corrupted before copying it over and trying to open it. Would such an API be possible in YapDatabase?

**Comment by robbiehanson** [comment]
I think @uthiel has the right idea here. Performing a quick hash on the file itself is going to be the fastest & most reliable method of testing the integrity of a file.
