### ISSUE TITLE
Use unified logging

### ISSUE THREAD

**Issue by mickeyl** [yapstudios/YapDatabase#461]
Now that Apple provides a sophisticated logging framework, it would be great to have YapDatabase support it – at least if we are targeting the versions where it's available:

iOS 10.0+
macOS 10.12+
tvOS 10.0+
watchOS 3.0+

**Comment by robbiehanson** [comment]
I believe this only requires adding another logging technique to YapDatabaseLogging.h ?

**Comment by robbiehanson** [comment]
Unified logging is now built into CocoaLumberjack, which is used by YapDatabase.

In the future, it might be nice if YapDatabase didn't directly require CocoaLumberjack, but instead used some kind of closure-based system. This would allow the database user to forward the database logs to their own logging system, whatever it may be.
