### ISSUE TITLE
[Bug]Get a object from a incorrect collection

### ISSUE THREAD

**Issue by robyzhou** [yapstudios/YapDatabase#474]
Hi,

I have used YapDatabase in our app for nearly 3 years, and I found the issue occurs occasionally. Which is, I get a object not belong to the collection I am using.

Sometimes, it occurs when I registering a extension, sometimes, it occurs while enumerating objects in a collection, and other situations. Notice, the code is right most of the time, the issue occurs occasionally.

For instance, I write objects of Class1 into collection_1, and write objects of Class2 into collection_2. Then, when I enumerating the objects in collection_1, sometimes I will get a object of Class2, that's not right.

I have checked, and ensured, that I didn't write the object in a incorrect collection.

Do you guys have any suggestions and clues for me to check it out?

Thanks in advance.

**Comment by michaelkirk-signal** [comment]
> For instance, I write objects of Class1 into connection_1

Just to be clear - do you mean into **collection_1**?

Can you provide any example code?

**Comment by robyzhou** [comment]
@michaelkirk-signal sorry for that, I just modified it. Thanks!

**Comment by robyzhou** [comment]
@michaelkirk-signal Yes, I mean collection_1. Sorry for that, I just modified it. Thanks!

**Comment by robyzhou** [comment]
@michaelkirk-signal 

Example1: save object into collection Collection_RecommendSquareItem

I try to save object into collection Collection_RecommendSquareItem, then the related extension code will be invoked to grouping and sorting the object. As you seen, the type objects should be YapRecommendSquareItem, and they are in collection Collection_RecommendSquareItem. While sorting, I got some crash with info that the item is not a YapRecommendSquareItem object, but a YapLikelist object, YapLikelist is another class.


Code here:

```
- (void)saveInTransaction:(YapDatabaseReadWriteTransaction*)transaction
{
    void (^block)(YapDatabaseReadWriteTransaction*) = ^(YapDatabaseReadWriteTransaction* transaction) {
        YapRecommendSquareItem *item = nil;
        NSString* primaryKey = [YapRecommendSquareItem primaryKeyWithUIN:self.userAdapter.contactID type:self.type];
        item = [transaction objectForKey:primaryKey inCollection:Collection_RecommendSquareItem];
        if (!item) {
            item = [[YapRecommendSquareItem alloc] init];
        }
        ......
        
        [transaction setObject:item
                        forKey:item.RecommendSquareItem_PrimaryKey
                  inCollection:Collection_RecommendSquareItem];
    };
    
    if (transaction) {
        block(transaction);
    }
    else {
        [[ObjectManager shareManager].writeConnection readWriteWithBlock:^(YapDatabaseReadWriteTransaction * _Nonnull transaction) {
            block(transaction);
        }];
    }
}


- (void)initRecommendSquareItemExtension
{
    YapDatabaseViewGrouping* grouping = [YapDatabaseViewGrouping withRowBlock:^NSString * _Nullable(YapDatabaseReadTransaction * _Nonnull transaction, NSString * _Nonnull collection, NSString * _Nonnull key, id  _Nonnull object, id  _Nullable metadata) {
        NSString* groupingName = nil;
        if ([object isKindOfClass:[YapRecommendSquareItem class]]) {
            groupingName = GroupingName_RecommendSquareItem;
        }
        
        return groupingName;
    }];
        
    YapDatabaseViewSorting* sorting = [YapDatabaseViewSorting withRowBlock:^NSComparisonResult(YapDatabaseReadTransaction * _Nonnull transaction, NSString * _Nonnull group, NSString * _Nonnull collection1, NSString * _Nonnull key1, id  _Nonnull object1, id  _Nonnull metadata1, NSString * _Nonnull collection2, NSString * _Nonnull key2, id  _Nonnull object2, id  _Nonnull metadata2) {
        NSComparisonResult result = NSOrderedSame;
        if ([group isEqualToString:GroupingName_RecommendSquareItem]) {
            YapRecommendSquareItem* item1 = (YapRecommendSquareItem*)object1;
            YapRecommendSquareItem* item2 = (YapRecommendSquareItem*)object2;
            if ([item1.RecommendSquareItem_SortID integerValue] > [item2.RecommendSquareItem_SortID integerValue]) {
                result = NSOrderedDescending;
            }
            else if ([item1.RecommendSquareItem_SortID integerValue] < [item2.RecommendSquareItem_SortID integerValue]) {
                result = NSOrderedAscending;
            }
        }
            
        return result;
    }];
        
    YapDatabaseAutoView* view = [[YapDatabaseAutoView alloc] initWithGrouping:grouping sorting:sorting versionTag:YapViewVersion_RecommendSquareItem_SortIDAscending];
        
    [[ObjectManager shareManager].db registerExtension:view withName:YapViewName_RecommendSquareItem_SortIDAscending];
}
```

Screenshot here:
![Uploading WX20180905-162652.png…]()

**Comment by robbiehanson** [comment]
You might try using YapDatabaseHooks extension. Use the `didModifyRow`, and add an assertion to ensure there's a correct match between Class & collection.

**Comment by robyzhou** [comment]
> You might try using YapDatabaseHooks extension. Use the `didModifyRow`, and add an assertion to ensure there's a correct match between Class & collection.

Thanks @robbiehanson , I will try this. Feed you back later.

**Comment by mdescalzo** [comment]
@robyzhou Did you find a solution to this problem?  I've been running into the same bug and have yet to figure it out.

**Comment by robyzhou** [comment]
@mdescalzo not yet, actually I am working on another project recently, you can try the suggestion by robbiehanson above.

> You might try using YapDatabaseHooks extension. Use the didModifyRow, and add an assertion to ensure there's a correct match between Class & collection.

**Comment by mdescalzo** [comment]
@robbiehanson Do you have a short code snippet/sample on YapDatabaseHooks implementation I could look at?

**Comment by robbiehanson** [comment]
For those looking for sample code, something like this should work:

```swift
let hooks = YapDatabaseHooks()
		
hooks.willModifyRow = {(transaction, collection, key, proxyObject, proxyMetadata, flags) in
   if collection == "foobar" {
      precondition(proxyObject.realObject is FooBar, "Oops!")
   }
}

let extName = Ext_Hooks
database.asyncRegister(hooks, withName: extName) {(ready) in
   
   if !ready {
      DDLogError("Error registering \(extName) !!!")
   }
}
```
