### ISSUE TITLE
Hello, I want know how to watch the data on simulator using Yap . I want know what it actually wrote. 

### ISSUE THREAD

**Issue by bingchenqin** [yapstudios/YapDatabase#476]
Thank you.

**Comment by mickeyl** [comment]
I don't know what exactly you're after, but I'm using the [sqlite browser](https://sqlitebrowser.org/) for inspecting the database.

**Comment by robbiehanson** [comment]
Another utility that may be useful is the YapDatabaseHooks extension. It will notify you about changes to the database such as when rows get inserted, modified or deleted. If you're trying to make some kind of real-time monitoring solution for your app, this may be the place to start.

**Comment by robbiehanson** [comment]
> I want know what it actually wrote.

If you're asking about the actual 1's and 0's that were written to disk:
```
[YapDatabaseConnection serializedObjectForKey:inCollection:]
```
