### ISSUE TITLE
Userinfo keys used by YapDatabaseModifiedNotification defined in YapDatabaseViewPrivate.h should be public

### ISSUE THREAD

**Issue by uthiel** [yapstudios/YapDatabase#478]
When a `YapDatabaseModifiedNotification` is posted, the `userInfo` dictionary has details about what actually changed. 

Among others, the `YapDatabaseExtensionsKey` is a `NSDictionary` with individual changeset info per extension.  Embedded into this dictionary is an `NSArray` containing the actual `YapDatabaseViewRowChange` objects. The key for this array is defined in `YapDatabaseViewPrivate.h`:

    /**
     * Keys for changeset dictionary.
    **/
    
    static NSString *const changeset_key_changes    = @"changes";

`YapDatabaseViewPrivate.h` is not included in the modulemap and therefore not part of the public API. Parties interested in the array containing the actual changes have to hard code the key name into their own code which is obviously not ideal.

As far as I can tell, this key should be part of the public API.

**Comment by uthiel** [comment]
Can someone (maybe Robbie) please comment on why this issue hasn't been commented on yet?

**Comment by robbiehanson** [comment]
Yes, you're absolutely correct. This value should be exposed in the public headers.
