### ISSUE TITLE
Remove deprecation of OSAtomic.h

### ISSUE THREAD

**Issue by yingzhang524** [yapstudios/YapDatabase#483]
The OSAtomic deprecated since iOS 10. Is there plan to remove this deprecation?

**Comment by robbiehanson** [comment]
I believe this has been fixed. Which file(s) are causing the warnings ?

The most recent related fix is commit #3156b068b33a99ca03af6d2e7aa6ce2879fee65b

**Comment by yingzhang524** [comment]
Thanks for the quick response. I tried the latest build but I got a error of  "Use of unresolved identifier 'YapDatabaseCrossProcessNotification'", any idea about how to fix it? Do you have any other commit you recommend to use?

**Comment by robbiehanson** [comment]
This might be related to the CocoaPods issue I'm fighting with right now: [link](https://github.com/yapstudios/YapDatabase/pull/479#issuecomment-455461958)

But perhaps not. Can you try the latest tag in master: commit  #3a7bfc57b95863db6353170cce9032d6c1688103

Also, are you using CocoaPods, Carthage, other ?
Swift or Objective-C ?

**Comment by yingzhang524** [comment]
CocoaPods 1.5.3, swift, static compiling(use_modular_headers!). I was using #3a7bfc57b95863db6353170cce9032d6c1688103 when I got error.

**Comment by robbiehanson** [comment]
I wasn't able to reproduce with:

- iOS project
- CocoaPods v1.6.0.beta.2
- Swift
- YapDatabase v3.1.2 (just released!)

Perhaps I fixed the problem with v3.1.2 release ?

**Comment by yingzhang524** [comment]
The new version 3.1.2 works! Now the only minor issue is that the dependency lib CocoaLumberJack still has many asl_* and OSAtomic* deprecations on iOS 10. Is there any plan to remove them?

Thanks!

**Comment by yingzhang524** [comment]
The OSAtomic deprecation is addressed in the latest commit of CocoaLumberJack .

**Comment by robbiehanson** [comment]
Excellent news! For other people with a similar question:

CocoaLumberjack is just a dependency of YapDatabase. YapDatabase specifies this in its [Podspec](https://github.com/yapstudios/YapDatabase/blob/master/YapDatabase.podspec), but does so without specifying a version (of CocoaLumberjack). So you're free to explicitly add CocoaLumberjack to your own Podfile, with an explicit version/commit. This allows you to pull the version of CocoaLumberjack that you want/need. (For example, to fix annoying warnings.)
