### ISSUE TITLE
Xcode project doesn't build due to files not being included in project

### ISSUE THREAD

**Issue by gcox** [yapstudios/YapDatabase#495]
The Xcode project no longer builds due to several files not being included in the project

Files in question:
* YapDatabaseTypes.h
* YapDatabaseConnectionProxy.h/m
* YapDatabaseConnectionPool.h/m
* YapDatabaseCollectionConfig.h/m
* YapDatabaseConnectionConfig.h/m
* YDBLogMessage.h/m
* YapDatabaseLogging.m doesn't exist, but is in the compile sources build phase

**Comment by grzegorzkrukowski** [comment]
Can this be included into original release ? Right now this project doesn't compile.

**Comment by matthewreagan** [comment]
This also means that trying to install YapDatabase into a project via Carthage also fails out-of-the-box.

**Comment by mucholove** [comment]
Bump.
