### ISSUE TITLE
while I am running pod install cam getting error

### ISSUE THREAD

**Issue by ramchandaluri** [yapstudios/YapDatabase#501]
[!] CocoaPods could not find compatible versions for pod "YapDatabase/SQLCipher":
  In Podfile:
    ChatSecureCore (from `ChatSecureCore.podspec`) was resolved to 0.1.0, which depends on
      YapDatabase/SQLCipher (~> 3.1.3)

    YapDatabase/SQLCipher (from `Submodules/YapDatabase/YapDatabase.podspec`)

**Comment by robbiehanson** [comment]
It may be that ChatSecureCore isn't yet compatible with YapDatabase v4.0+. (I'm guessing.) You may try tweaking your Podfile to ensure only YapDatabase v3.X is used.
