### ISSUE TITLE
4.0 change: No way to set objectPolicy and metadataPolicy globally

### ISSUE THREAD

**Issue by ksuther** [yapstudios/YapDatabase#502]
Feedback on cbc69683919ea4d045372cdef6812b52b0a5708b in 4.0.

As far as I can tell there's no way to set a database-wide default `objectPolicy` and `metadataPolicy`. This is a bit of a drag as we don't necessarily know the names of all the collections in order to specify the policies during database setup.

Ideas:
- Allow `setObjectPolicy:forCollection:` to set a policy for a `nil` collection and use that as the default policy. It looks like the method implementation already accepts `nil` and turns it into `@""`, it's just that the consumer of `getObjectPolicies:metadataPolicies:` doesn't seem to check `@""` as a fallback.
- Re-add new methods to set default object and metadata policies that are used as a fallback

Happy to make a PR that does one of those, but not sure what the design intention was when making this change.

**Comment by robbiehanson** [comment]
Ah, good find. Yup, I forgot the `setDefaultObjectPolicy` method.
