### ISSUE TITLE
Implement YapDatabaseRelationshipNode in Swift struct?

### ISSUE THREAD

**Issue by hujunfeng** [yapstudios/YapDatabase#515]
With YapDatabase 4, we can now use Swift struct directly like this:

```
struct Bar: Codable { // Just implement Codable
  // ...
}

// Register it
db.registerCodableSerialization(Bar.self, forCollection: "bars")

// And you're done.
// Now you can read & write your custom objects with the database.

let bar = Bar()

connection.readWrite {(transaction) in
  transaction.setObject(bar, forKey: "2", inCollection: "bars")
}

connection.read {(transaction) in
  let bar = transaction.object(forKey: "2", inCollection: "bars") as? Bar
}
```

This is an example from the [wiki](https://github.com/yapstudios/YapDatabase/wiki/Hello-World#codable).

However, there is an issue when implementing YapDatabaseRelationshipNode in Swift structs. This protocol is defined in Objective-C. Currently, it seems that it is not possible to use it with Swift structs:

```
extension Bar: YapDatabaseRelationshipNode { }
// error: Non-class type 'Bar' cannot conform to class protocol 'YapDatabaseRelationshipNode'
```

Any suggestions on how to resolve this issue? Or any other way to achieve automatic YapDatabaseRelationship edge creation without this protocol?

**Comment by robbiehanson** [comment]
Great question.

Swift has the concept of class-only protocols, and it appears that it automatically imports objective-c protocols as:

```Swift
protocol Foobar: class {
// ...
}
```

This is what's causing the error. And I don't know if there's a way to tell swift to import the protocol without the class-only restriction. But there is another way around it.

I pushed a fix to the branch named 'issue515'. Can you give it a try?

**Comment by robbiehanson** [comment]
Update: Make sure you get commit dda1ece (as the first commit won't work)

**Comment by hujunfeng** [comment]
I did a quick test with a few simple examples. The workaround works very well! Thanks a lot for the quick fix.

Next, I'll try to integrate the fix into our project. I will update the result in a couple of days.

**Comment by robbiehanson** [comment]
I pushed another commit to the branch that fixes the `NS_ASSUME_NONNULL_End` typo.

**Comment by hujunfeng** [comment]
I have tried the fix in our main project. It is working fine, I didn't encounter any issue. My problem is resolved. 👍

**Comment by robbiehanson** [comment]
Branch merged into master, and scheduled for inclusion in next release
